FROM node:25-alpine

WORKDIR /app

COPY package.json pnpm-lock.yaml ./

RUN corepack enable && corepack prepare pnpm@10.30.3 --activate && pnpm install

COPY . .

EXPOSE 5173

CMD ["pnpm", "dev", "--host"]
