# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: check-added-large-files
          - id: check-toml
          - id: check-yaml
            args:
                - --unsafe
          - id: end-of-file-fixer
            exclude: |
                (?x)^(
                    frontend/src/client/.*|
                    backend/app/email-templates/build/.*
                )$
          - id: trailing-whitespace
            exclude: ^frontend/src/client/.*
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.15.0
      hooks:
          - id: ruff
            args:
                - --fix
          - id: ruff-format
    - repo: local
      hooks:
          - id: basedpyright
            name: basedpyright
            entry: python scripts/pre-commit/run_basedpyright.py
            language: system
            files: ^backend/.*\.py$
            pass_filenames: false

          - id: pytest
            name: pytest
            entry: python scripts/pre-commit/run_tests.py
            language: system
            files: ^backend/
            pass_filenames: false

          - id: check-RMPC-comments
            name: Check for RMPC comments
            entry: python scripts/pre-commit/check_remove_comments.py
            language: python
            files: \.py$

          - id: vue-tsc
            name: vue-tsc
            entry: bash -c "cd frontend && pnpm vue-tsc --noEmit --project tsconfig.app.json"
            language: system
            files: ^frontend/src/.*\.(ts|vue)$
            pass_filenames: false

          - id: sort-locales
            name: Sort locale JSON files
            entry: node scripts/pre-commit/sort_locales.js
            language: node
            files: ^frontend/src/locales/.*/.*\.json$
            pass_filenames: false

ci:
    autofix_commit_msg: 🎨 [pre-commit.ci] Auto format from pre-commit.com hooks
    autoupdate_commit_msg: ⬆ [pre-commit.ci] pre-commit autoupdate
