// This file is auto-generated by @hey-api/openapi-ts

/**
 * BookingCreate
 * User only provides the slot and optional notes. user_id is set server-side.
 */
export type BookingCreate = {
  /**
   * Duty Slot Id
   */
  duty_slot_id: string
  /**
   * Notes
   */
  notes?: string | null
}

/**
 * BookingListResponse
 */
export type BookingListResponse = {
  /**
   * Items
   */
  items: Array<BookingRead>
  /**
   * Total
   */
  total: number
  /**
   * Skip
   */
  skip: number
  /**
   * Limit
   */
  limit: number
}

/**
 * BookingRead
 */
export type BookingRead = {
  /**
   * Duty Slot Id
   */
  duty_slot_id: string
  /**
   * User Id
   */
  user_id: string
  /**
   * Status
   */
  status?: 'confirmed' | 'cancelled'
  /**
   * Notes
   */
  notes?: string | null
  /**
   * Id
   */
  id: string
  /**
   * Created At
   */
  created_at: string
  /**
   * Updated At
   */
  updated_at: string
}

/**
 * BookingUpdate
 */
export type BookingUpdate = {
  /**
   * Status
   */
  status?: ('confirmed' | 'cancelled') | null
  /**
   * Notes
   */
  notes?: string | null
}

/**
 * DutySlotCreate
 */
export type DutySlotCreate = {
  /**
   * Event Id
   */
  event_id: string
  /**
   * Title
   */
  title: string
  /**
   * Description
   */
  description?: string | null
  /**
   * Date
   */
  date: string
  /**
   * Start Time
   */
  start_time?: string | null
  /**
   * End Time
   */
  end_time?: string | null
  /**
   * Location
   */
  location?: string | null
  /**
   * Category
   */
  category?: string | null
  /**
   * Max Bookings
   */
  max_bookings?: number
}

/**
 * DutySlotListResponse
 */
export type DutySlotListResponse = {
  /**
   * Items
   */
  items: Array<DutySlotRead>
  /**
   * Total
   */
  total: number
  /**
   * Skip
   */
  skip: number
  /**
   * Limit
   */
  limit: number
}

/**
 * DutySlotRead
 */
export type DutySlotRead = {
  /**
   * Event Id
   */
  event_id: string
  /**
   * Title
   */
  title: string
  /**
   * Description
   */
  description?: string | null
  /**
   * Date
   */
  date: string
  /**
   * Start Time
   */
  start_time?: string | null
  /**
   * End Time
   */
  end_time?: string | null
  /**
   * Location
   */
  location?: string | null
  /**
   * Category
   */
  category?: string | null
  /**
   * Max Bookings
   */
  max_bookings?: number
  /**
   * Id
   */
  id: string
  /**
   * Created At
   */
  created_at: string
  /**
   * Updated At
   */
  updated_at: string
  /**
   * Current Bookings
   */
  current_bookings?: number
}

/**
 * DutySlotUpdate
 */
export type DutySlotUpdate = {
  /**
   * Title
   */
  title?: string | null
  /**
   * Description
   */
  description?: string | null
  /**
   * Date
   */
  date?: string | null
  /**
   * Start Time
   */
  start_time?: string | null
  /**
   * End Time
   */
  end_time?: string | null
  /**
   * Location
   */
  location?: string | null
  /**
   * Category
   */
  category?: string | null
  /**
   * Max Bookings
   */
  max_bookings?: number | null
}

/**
 * EventCreate
 */
export type EventCreate = {
  /**
   * Name
   */
  name: string
  /**
   * Description
   */
  description?: string | null
  /**
   * Start Date
   */
  start_date: string
  /**
   * End Date
   */
  end_date: string
  /**
   * Status
   */
  status?: 'draft' | 'published' | 'archived'
  /**
   * Created By Id
   */
  created_by_id?: string | null
}

/**
 * EventListResponse
 */
export type EventListResponse = {
  /**
   * Items
   */
  items: Array<EventRead>
  /**
   * Total
   */
  total: number
  /**
   * Skip
   */
  skip: number
  /**
   * Limit
   */
  limit: number
}

/**
 * EventRead
 */
export type EventRead = {
  /**
   * Name
   */
  name: string
  /**
   * Description
   */
  description?: string | null
  /**
   * Start Date
   */
  start_date: string
  /**
   * End Date
   */
  end_date: string
  /**
   * Status
   */
  status?: 'draft' | 'published' | 'archived'
  /**
   * Created By Id
   */
  created_by_id?: string | null
  /**
   * Id
   */
  id: string
  /**
   * Created At
   */
  created_at: string
  /**
   * Updated At
   */
  updated_at: string
}

/**
 * EventUpdate
 */
export type EventUpdate = {
  /**
   * Name
   */
  name?: string | null
  /**
   * Description
   */
  description?: string | null
  /**
   * Start Date
   */
  start_date?: string | null
  /**
   * End Date
   */
  end_date?: string | null
  /**
   * Status
   */
  status?: ('draft' | 'published' | 'archived') | null
}

/**
 * ProfileInit
 * Profile data from Auth0 ID token for user initialization.
 */
export type ProfileInit = {
  /**
   * Email
   */
  email?: string | null
  /**
   * Name
   */
  name?: string | null
  /**
   * Nickname
   */
  nickname?: string | null
}

/**
 * UserCreate
 */
export type UserCreate = {
  /**
   * Auth0 Sub
   * Auth0 subject identifier
   */
  auth0_sub: string
  /**
   * Email
   * User's email address
   */
  email?: string | null
  /**
   * Name
   * User's display name
   */
  name?: string | null
  /**
   * Roles
   * List of role identifiers
   */
  roles?: Array<string>
  /**
   * Is Active
   * Whether the user is active
   */
  is_active?: boolean
}

/**
 * UserProfile
 */
export type UserProfile = {
  /**
   * Sub
   */
  sub: string
  /**
   * Name
   */
  name?: string | null
  /**
   * Nickname
   */
  nickname?: string | null
  /**
   * Email
   */
  email?: string | null
  /**
   * Picture
   */
  picture?: string | null
  /**
   * Bio
   */
  bio?: string | null
  /**
   * Email Verified
   */
  email_verified?: boolean | null
  /**
   * Roles
   * User's roles
   */
  roles?: Array<string>
  /**
   * Is Admin
   * Whether user has admin role
   */
  is_admin?: boolean
  /**
   * Is Active
   * Whether user is active
   */
  is_active?: boolean
}

/**
 * UserProfileUpdate
 */
export type UserProfileUpdate = {
  /**
   * Name
   * User's display name
   */
  name?: string | null
  /**
   * Nickname
   * User's nickname
   */
  nickname?: string | null
  /**
   * Picture
   * URL to user's profile picture
   */
  picture?: string | null
  /**
   * Bio
   * User's biography
   */
  bio?: string | null
}

/**
 * UserRead
 */
export type UserRead = {
  /**
   * Id
   */
  id: string
  /**
   * Auth0 Sub
   */
  auth0_sub: string
  /**
   * Email
   */
  email?: string | null
  /**
   * Name
   */
  name?: string | null
  /**
   * Roles
   */
  roles: Array<string>
  /**
   * Is Active
   */
  is_active: boolean
  /**
   * Created At
   */
  created_at: string
  /**
   * Updated At
   */
  updated_at: string
}

/**
 * UserUpdate
 */
export type UserUpdate = {
  /**
   * Email
   * User's email address
   */
  email?: string | null
  /**
   * Name
   * User's display name
   */
  name?: string | null
  /**
   * Roles
   * List of role identifiers
   */
  roles?: Array<string> | null
  /**
   * Is Active
   * Whether the user is active
   */
  is_active?: boolean | null
}

export type ValidationErrorItem = {
  loc: Array<string | number>
  msg: string
  type: string
}

export type ProblemDetails = {
  type: string
  code?: string
  title: string
  status: number
  detail?: string
  instance?: string
  errors?: Array<ValidationErrorItem>
}

export type HealthHealthCheckData = {
  body?: never
  path?: never
  query?: never
  url: '/api/v1/healthz'
}

export type HealthHealthCheckErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type HealthHealthCheckError = HealthHealthCheckErrors[keyof HealthHealthCheckErrors]

export type HealthHealthCheckResponses = {
  /**
   * Successful Response
   */
  200: unknown
}

export type HealthReadinessCheckData = {
  body?: never
  path?: never
  query?: never
  url: '/api/v1/readyz'
}

export type HealthReadinessCheckErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type HealthReadinessCheckError = HealthReadinessCheckErrors[keyof HealthReadinessCheckErrors]

export type HealthReadinessCheckResponses = {
  /**
   * Successful Response
   */
  200: unknown
}

export type UsersUpdateUserProfileData = {
  body: UserProfileUpdate
  path?: never
  query?: never
  url: '/api/v1/users/me'
}

export type UsersUpdateUserProfileErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type UsersUpdateUserProfileError =
  UsersUpdateUserProfileErrors[keyof UsersUpdateUserProfileErrors]

export type UsersUpdateUserProfileResponses = {
  /**
   * Successful Response
   */
  200: UserProfile
}

export type UsersUpdateUserProfileResponse =
  UsersUpdateUserProfileResponses[keyof UsersUpdateUserProfileResponses]

export type UsersGetCurrentUserProfileData = {
  /**
   * Profile Init
   */
  body?: ProfileInit | null
  path?: never
  query?: never
  url: '/api/v1/users/me'
}

export type UsersGetCurrentUserProfileErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type UsersGetCurrentUserProfileError =
  UsersGetCurrentUserProfileErrors[keyof UsersGetCurrentUserProfileErrors]

export type UsersGetCurrentUserProfileResponses = {
  /**
   * Successful Response
   */
  200: UserProfile
}

export type UsersGetCurrentUserProfileResponse =
  UsersGetCurrentUserProfileResponses[keyof UsersGetCurrentUserProfileResponses]

export type UsersGetAuth0ManagementUrlData = {
  body?: never
  path?: never
  query?: never
  url: '/api/v1/users/auth0-management-url'
}

export type UsersGetAuth0ManagementUrlErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type UsersGetAuth0ManagementUrlError =
  UsersGetAuth0ManagementUrlErrors[keyof UsersGetAuth0ManagementUrlErrors]

export type UsersGetAuth0ManagementUrlResponses = {
  /**
   * Response Users-Get Auth0 Management Url
   * Successful Response
   */
  200: {
    [key: string]: string
  }
}

export type UsersGetAuth0ManagementUrlResponse =
  UsersGetAuth0ManagementUrlResponses[keyof UsersGetAuth0ManagementUrlResponses]

export type UsersListUsersData = {
  body?: never
  path?: never
  query?: {
    /**
     * Skip
     */
    skip?: number
    /**
     * Limit
     */
    limit?: number
  }
  url: '/api/v1/users/'
}

export type UsersListUsersErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type UsersListUsersError = UsersListUsersErrors[keyof UsersListUsersErrors]

export type UsersListUsersResponses = {
  /**
   * Response Users-List Users
   * Successful Response
   */
  200: Array<UserRead>
}

export type UsersListUsersResponse = UsersListUsersResponses[keyof UsersListUsersResponses]

export type UsersCreateUserData = {
  body: UserCreate
  path?: never
  query?: never
  url: '/api/v1/users/'
}

export type UsersCreateUserErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type UsersCreateUserError = UsersCreateUserErrors[keyof UsersCreateUserErrors]

export type UsersCreateUserResponses = {
  /**
   * Successful Response
   */
  201: UserRead
}

export type UsersCreateUserResponse = UsersCreateUserResponses[keyof UsersCreateUserResponses]

export type UsersDeleteUserData = {
  body?: never
  path: {
    /**
     * User Id
     */
    user_id: string
  }
  query?: never
  url: '/api/v1/users/{user_id}'
}

export type UsersDeleteUserErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type UsersDeleteUserError = UsersDeleteUserErrors[keyof UsersDeleteUserErrors]

export type UsersDeleteUserResponses = {
  /**
   * Successful Response
   */
  200: UserRead
}

export type UsersDeleteUserResponse = UsersDeleteUserResponses[keyof UsersDeleteUserResponses]

export type UsersGetUserData = {
  body?: never
  path: {
    /**
     * User Id
     */
    user_id: string
  }
  query?: never
  url: '/api/v1/users/{user_id}'
}

export type UsersGetUserErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type UsersGetUserError = UsersGetUserErrors[keyof UsersGetUserErrors]

export type UsersGetUserResponses = {
  /**
   * Successful Response
   */
  200: UserRead
}

export type UsersGetUserResponse = UsersGetUserResponses[keyof UsersGetUserResponses]

export type UsersUpdateUserData = {
  body: UserUpdate
  path: {
    /**
     * User Id
     */
    user_id: string
  }
  query?: never
  url: '/api/v1/users/{user_id}'
}

export type UsersUpdateUserErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type UsersUpdateUserError = UsersUpdateUserErrors[keyof UsersUpdateUserErrors]

export type UsersUpdateUserResponses = {
  /**
   * Successful Response
   */
  200: UserRead
}

export type UsersUpdateUserResponse = UsersUpdateUserResponses[keyof UsersUpdateUserResponses]

export type EventsListEventsData = {
  body?: never
  path?: never
  query?: {
    /**
     * Skip
     */
    skip?: number
    /**
     * Limit
     */
    limit?: number
    /**
     * Search
     */
    search?: string | null
    /**
     * Status
     */
    status?: ('draft' | 'published' | 'archived') | null
  }
  url: '/api/v1/events/'
}

export type EventsListEventsErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type EventsListEventsError = EventsListEventsErrors[keyof EventsListEventsErrors]

export type EventsListEventsResponses = {
  /**
   * Successful Response
   */
  200: EventListResponse
}

export type EventsListEventsResponse = EventsListEventsResponses[keyof EventsListEventsResponses]

export type EventsCreateEventData = {
  body: EventCreate
  path?: never
  query?: never
  url: '/api/v1/events/'
}

export type EventsCreateEventErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type EventsCreateEventError = EventsCreateEventErrors[keyof EventsCreateEventErrors]

export type EventsCreateEventResponses = {
  /**
   * Successful Response
   */
  201: EventRead
}

export type EventsCreateEventResponse = EventsCreateEventResponses[keyof EventsCreateEventResponses]

export type EventsDeleteEventData = {
  body?: never
  path: {
    /**
     * Event Id
     */
    event_id: string
  }
  query?: never
  url: '/api/v1/events/{event_id}'
}

export type EventsDeleteEventErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type EventsDeleteEventError = EventsDeleteEventErrors[keyof EventsDeleteEventErrors]

export type EventsDeleteEventResponses = {
  /**
   * Successful Response
   */
  204: void
}

export type EventsDeleteEventResponse = EventsDeleteEventResponses[keyof EventsDeleteEventResponses]

export type EventsGetEventData = {
  body?: never
  path: {
    /**
     * Event Id
     */
    event_id: string
  }
  query?: never
  url: '/api/v1/events/{event_id}'
}

export type EventsGetEventErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type EventsGetEventError = EventsGetEventErrors[keyof EventsGetEventErrors]

export type EventsGetEventResponses = {
  /**
   * Successful Response
   */
  200: EventRead
}

export type EventsGetEventResponse = EventsGetEventResponses[keyof EventsGetEventResponses]

export type EventsUpdateEventData = {
  body: EventUpdate
  path: {
    /**
     * Event Id
     */
    event_id: string
  }
  query?: never
  url: '/api/v1/events/{event_id}'
}

export type EventsUpdateEventErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type EventsUpdateEventError = EventsUpdateEventErrors[keyof EventsUpdateEventErrors]

export type EventsUpdateEventResponses = {
  /**
   * Successful Response
   */
  200: EventRead
}

export type EventsUpdateEventResponse = EventsUpdateEventResponses[keyof EventsUpdateEventResponses]

export type DutySlotsListDutySlotsData = {
  body?: never
  path?: never
  query?: {
    /**
     * Event Id
     */
    event_id?: string | null
    /**
     * Category
     */
    category?: string | null
    /**
     * Search
     */
    search?: string | null
    /**
     * Skip
     */
    skip?: number
    /**
     * Limit
     */
    limit?: number
  }
  url: '/api/v1/duty-slots/'
}

export type DutySlotsListDutySlotsErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type DutySlotsListDutySlotsError =
  DutySlotsListDutySlotsErrors[keyof DutySlotsListDutySlotsErrors]

export type DutySlotsListDutySlotsResponses = {
  /**
   * Successful Response
   */
  200: DutySlotListResponse
}

export type DutySlotsListDutySlotsResponse =
  DutySlotsListDutySlotsResponses[keyof DutySlotsListDutySlotsResponses]

export type DutySlotsCreateDutySlotData = {
  body: DutySlotCreate
  path?: never
  query?: never
  url: '/api/v1/duty-slots/'
}

export type DutySlotsCreateDutySlotErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type DutySlotsCreateDutySlotError =
  DutySlotsCreateDutySlotErrors[keyof DutySlotsCreateDutySlotErrors]

export type DutySlotsCreateDutySlotResponses = {
  /**
   * Successful Response
   */
  201: DutySlotRead
}

export type DutySlotsCreateDutySlotResponse =
  DutySlotsCreateDutySlotResponses[keyof DutySlotsCreateDutySlotResponses]

export type DutySlotsDeleteDutySlotData = {
  body?: never
  path: {
    /**
     * Slot Id
     */
    slot_id: string
  }
  query?: never
  url: '/api/v1/duty-slots/{slot_id}'
}

export type DutySlotsDeleteDutySlotErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type DutySlotsDeleteDutySlotError =
  DutySlotsDeleteDutySlotErrors[keyof DutySlotsDeleteDutySlotErrors]

export type DutySlotsDeleteDutySlotResponses = {
  /**
   * Successful Response
   */
  204: void
}

export type DutySlotsDeleteDutySlotResponse =
  DutySlotsDeleteDutySlotResponses[keyof DutySlotsDeleteDutySlotResponses]

export type DutySlotsGetDutySlotData = {
  body?: never
  path: {
    /**
     * Slot Id
     */
    slot_id: string
  }
  query?: never
  url: '/api/v1/duty-slots/{slot_id}'
}

export type DutySlotsGetDutySlotErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type DutySlotsGetDutySlotError = DutySlotsGetDutySlotErrors[keyof DutySlotsGetDutySlotErrors]

export type DutySlotsGetDutySlotResponses = {
  /**
   * Successful Response
   */
  200: DutySlotRead
}

export type DutySlotsGetDutySlotResponse =
  DutySlotsGetDutySlotResponses[keyof DutySlotsGetDutySlotResponses]

export type DutySlotsUpdateDutySlotData = {
  body: DutySlotUpdate
  path: {
    /**
     * Slot Id
     */
    slot_id: string
  }
  query?: never
  url: '/api/v1/duty-slots/{slot_id}'
}

export type DutySlotsUpdateDutySlotErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type DutySlotsUpdateDutySlotError =
  DutySlotsUpdateDutySlotErrors[keyof DutySlotsUpdateDutySlotErrors]

export type DutySlotsUpdateDutySlotResponses = {
  /**
   * Successful Response
   */
  200: DutySlotRead
}

export type DutySlotsUpdateDutySlotResponse =
  DutySlotsUpdateDutySlotResponses[keyof DutySlotsUpdateDutySlotResponses]

export type BookingsListMyBookingsData = {
  body?: never
  path?: never
  query?: {
    /**
     * Skip
     */
    skip?: number
    /**
     * Limit
     */
    limit?: number
    /**
     * Status
     */
    status?: string | null
  }
  url: '/api/v1/bookings/me'
}

export type BookingsListMyBookingsErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type BookingsListMyBookingsError =
  BookingsListMyBookingsErrors[keyof BookingsListMyBookingsErrors]

export type BookingsListMyBookingsResponses = {
  /**
   * Successful Response
   */
  200: BookingListResponse
}

export type BookingsListMyBookingsResponse =
  BookingsListMyBookingsResponses[keyof BookingsListMyBookingsResponses]

export type BookingsCreateBookingData = {
  body: BookingCreate
  path?: never
  query?: never
  url: '/api/v1/bookings/'
}

export type BookingsCreateBookingErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type BookingsCreateBookingError =
  BookingsCreateBookingErrors[keyof BookingsCreateBookingErrors]

export type BookingsCreateBookingResponses = {
  /**
   * Successful Response
   */
  201: BookingRead
}

export type BookingsCreateBookingResponse =
  BookingsCreateBookingResponses[keyof BookingsCreateBookingResponses]

export type BookingsCancelBookingData = {
  body?: never
  path: {
    /**
     * Booking Id
     */
    booking_id: string
  }
  query?: never
  url: '/api/v1/bookings/{booking_id}'
}

export type BookingsCancelBookingErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type BookingsCancelBookingError =
  BookingsCancelBookingErrors[keyof BookingsCancelBookingErrors]

export type BookingsCancelBookingResponses = {
  /**
   * Successful Response
   */
  200: BookingRead
}

export type BookingsCancelBookingResponse =
  BookingsCancelBookingResponses[keyof BookingsCancelBookingResponses]

export type BookingsGetBookingData = {
  body?: never
  path: {
    /**
     * Booking Id
     */
    booking_id: string
  }
  query?: never
  url: '/api/v1/bookings/{booking_id}'
}

export type BookingsGetBookingErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type BookingsGetBookingError = BookingsGetBookingErrors[keyof BookingsGetBookingErrors]

export type BookingsGetBookingResponses = {
  /**
   * Successful Response
   */
  200: BookingRead
}

export type BookingsGetBookingResponse =
  BookingsGetBookingResponses[keyof BookingsGetBookingResponses]

export type BookingsUpdateBookingData = {
  body: BookingUpdate
  path: {
    /**
     * Booking Id
     */
    booking_id: string
  }
  query?: never
  url: '/api/v1/bookings/{booking_id}'
}

export type BookingsUpdateBookingErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type BookingsUpdateBookingError =
  BookingsUpdateBookingErrors[keyof BookingsUpdateBookingErrors]

export type BookingsUpdateBookingResponses = {
  /**
   * Successful Response
   */
  200: BookingRead
}

export type BookingsUpdateBookingResponse =
  BookingsUpdateBookingResponses[keyof BookingsUpdateBookingResponses]

export type ClientOptions = {
  baseURL: `${string}://${string}` | (string & {})
}
