// This file is auto-generated by @hey-api/openapi-ts

/**
 * AddSlotsResponse
 */
export type AddSlotsResponse = {
  event: EventRead
  /**
   * Slots Added
   */
  slots_added: number
}

/**
 * AddSlotsToEvent
 */
export type AddSlotsToEvent = {
  /**
   * Start Date
   */
  start_date: string
  /**
   * End Date
   */
  end_date: string
  /**
   * Location
   */
  location?: string | null
  /**
   * Category
   */
  category?: string | null
  schedule: SlotGenerationConfig
}

/**
 * AffectedBookingInfo
 */
export type AffectedBookingInfo = {
  /**
   * Booking Id
   */
  booking_id: string
  /**
   * User Id
   */
  user_id: string
  /**
   * Slot Title
   */
  slot_title: string
  /**
   * Slot Date
   */
  slot_date: string
  /**
   * Slot Start Time
   */
  slot_start_time?: string | null
  /**
   * Slot End Time
   */
  slot_end_time?: string | null
}

/**
 * BookingCreate
 * User only provides the slot and optional notes. user_id is set server-side.
 */
export type BookingCreate = {
  /**
   * Duty Slot Id
   */
  duty_slot_id: string
  /**
   * Notes
   */
  notes?: string | null
}

/**
 * BookingRead
 */
export type BookingRead = {
  /**
   * Duty Slot Id
   */
  duty_slot_id?: string | null
  /**
   * User Id
   */
  user_id: string
  /**
   * Status
   */
  status?: 'confirmed' | 'cancelled'
  /**
   * Notes
   */
  notes?: string | null
  /**
   * Id
   */
  id: string
  /**
   * Created At
   */
  created_at: string
  /**
   * Updated At
   */
  updated_at: string
  /**
   * Cancellation Reason
   */
  cancellation_reason?: string | null
  /**
   * Cancelled Slot Title
   */
  cancelled_slot_title?: string | null
  /**
   * Cancelled Slot Date
   */
  cancelled_slot_date?: string | null
  /**
   * Cancelled Slot Start Time
   */
  cancelled_slot_start_time?: string | null
  /**
   * Cancelled Slot End Time
   */
  cancelled_slot_end_time?: string | null
  /**
   * Cancelled Event Name
   */
  cancelled_event_name?: string | null
}

/**
 * BookingReadWithSlot
 * BookingRead enriched with nested slot + event name (for /me endpoint).
 */
export type BookingReadWithSlot = {
  /**
   * Duty Slot Id
   */
  duty_slot_id?: string | null
  /**
   * User Id
   */
  user_id: string
  /**
   * Status
   */
  status?: 'confirmed' | 'cancelled'
  /**
   * Notes
   */
  notes?: string | null
  /**
   * Id
   */
  id: string
  /**
   * Created At
   */
  created_at: string
  /**
   * Updated At
   */
  updated_at: string
  /**
   * Cancellation Reason
   */
  cancellation_reason?: string | null
  /**
   * Cancelled Slot Title
   */
  cancelled_slot_title?: string | null
  /**
   * Cancelled Slot Date
   */
  cancelled_slot_date?: string | null
  /**
   * Cancelled Slot Start Time
   */
  cancelled_slot_start_time?: string | null
  /**
   * Cancelled Slot End Time
   */
  cancelled_slot_end_time?: string | null
  /**
   * Cancelled Event Name
   */
  cancelled_event_name?: string | null
  duty_slot?: DutySlotSummary | null
}

/**
 * BookingUpdate
 */
export type BookingUpdate = {
  /**
   * Status
   */
  status?: ('confirmed' | 'cancelled') | null
  /**
   * Notes
   */
  notes?: string | null
  /**
   * Cancellation Reason
   */
  cancellation_reason?: string | null
}

/**
 * DutySlotCreate
 */
export type DutySlotCreate = {
  /**
   * Event Id
   */
  event_id: string
  /**
   * Title
   */
  title: string
  /**
   * Description
   */
  description?: string | null
  /**
   * Date
   */
  date: string
  /**
   * Start Time
   */
  start_time?: string | null
  /**
   * End Time
   */
  end_time?: string | null
  /**
   * Location
   */
  location?: string | null
  /**
   * Category
   */
  category?: string | null
  /**
   * Max Bookings
   */
  max_bookings?: number
  /**
   * Batch Id
   */
  batch_id?: string | null
}

/**
 * DutySlotListResponse
 */
export type DutySlotListResponse = {
  /**
   * Items
   */
  items: Array<DutySlotRead>
  /**
   * Total
   */
  total: number
  /**
   * Skip
   */
  skip: number
  /**
   * Limit
   */
  limit: number
}

/**
 * DutySlotRead
 */
export type DutySlotRead = {
  /**
   * Event Id
   */
  event_id: string
  /**
   * Title
   */
  title: string
  /**
   * Description
   */
  description?: string | null
  /**
   * Date
   */
  date: string
  /**
   * Start Time
   */
  start_time?: string | null
  /**
   * End Time
   */
  end_time?: string | null
  /**
   * Location
   */
  location?: string | null
  /**
   * Category
   */
  category?: string | null
  /**
   * Max Bookings
   */
  max_bookings?: number
  /**
   * Batch Id
   */
  batch_id?: string | null
  /**
   * Id
   */
  id: string
  /**
   * Created At
   */
  created_at: string
  /**
   * Updated At
   */
  updated_at: string
  /**
   * Current Bookings
   */
  current_bookings?: number
}

/**
 * DutySlotSummary
 * Lightweight slot info nested inside a booking response.
 */
export type DutySlotSummary = {
  /**
   * Id
   */
  id: string
  /**
   * Event Id
   */
  event_id: string
  /**
   * Title
   */
  title: string
  /**
   * Date
   */
  date: string
  /**
   * Start Time
   */
  start_time?: string | null
  /**
   * End Time
   */
  end_time?: string | null
  /**
   * Location
   */
  location?: string | null
  /**
   * Category
   */
  category?: string | null
  /**
   * Event Name
   */
  event_name?: string | null
}

/**
 * DutySlotUpdate
 */
export type DutySlotUpdate = {
  /**
   * Title
   */
  title?: string | null
  /**
   * Description
   */
  description?: string | null
  /**
   * Date
   */
  date?: string | null
  /**
   * Start Time
   */
  start_time?: string | null
  /**
   * End Time
   */
  end_time?: string | null
  /**
   * Location
   */
  location?: string | null
  /**
   * Category
   */
  category?: string | null
  /**
   * Max Bookings
   */
  max_bookings?: number | null
}

/**
 * EventCreate
 */
export type EventCreate = {
  /**
   * Name
   */
  name: string
  /**
   * Description
   */
  description?: string | null
  /**
   * Start Date
   */
  start_date: string
  /**
   * End Date
   */
  end_date: string
  /**
   * Status
   */
  status?: 'draft' | 'published' | 'archived'
  /**
   * Created By Id
   */
  created_by_id?: string | null
  /**
   * Event Group Id
   */
  event_group_id?: string | null
  /**
   * Location
   */
  location?: string | null
  /**
   * Category
   */
  category?: string | null
}

/**
 * EventCreateWithSlots
 */
export type EventCreateWithSlots = {
  /**
   * Name
   */
  name: string
  /**
   * Description
   */
  description?: string | null
  /**
   * Start Date
   */
  start_date: string
  /**
   * End Date
   */
  end_date: string
  /**
   * Location
   */
  location?: string | null
  /**
   * Category
   */
  category?: string | null
  /**
   * Event Group Id
   */
  event_group_id?: string | null
  new_event_group?: EventGroupCreate | null
  schedule: SlotGenerationConfig
}

/**
 * EventCreateWithSlotsResponse
 */
export type EventCreateWithSlotsResponse = {
  event: EventRead
  /**
   * Duty Slots Created
   */
  duty_slots_created: number
  event_group?: EventGroupRead | null
}

/**
 * EventGroupCreate
 */
export type EventGroupCreate = {
  /**
   * Name
   */
  name: string
  /**
   * Description
   */
  description?: string | null
  /**
   * Start Date
   */
  start_date: string
  /**
   * End Date
   */
  end_date: string
  /**
   * Status
   */
  status?: 'draft' | 'published' | 'archived'
  /**
   * Created By Id
   */
  created_by_id?: string | null
}

/**
 * EventGroupListResponse
 */
export type EventGroupListResponse = {
  /**
   * Items
   */
  items: Array<EventGroupRead>
  /**
   * Total
   */
  total: number
  /**
   * Skip
   */
  skip: number
  /**
   * Limit
   */
  limit: number
}

/**
 * EventGroupRead
 */
export type EventGroupRead = {
  /**
   * Name
   */
  name: string
  /**
   * Description
   */
  description?: string | null
  /**
   * Start Date
   */
  start_date: string
  /**
   * End Date
   */
  end_date: string
  /**
   * Status
   */
  status?: 'draft' | 'published' | 'archived'
  /**
   * Id
   */
  id: string
  /**
   * Created By Id
   */
  created_by_id?: string | null
  /**
   * Created At
   */
  created_at: string
  /**
   * Updated At
   */
  updated_at: string
}

/**
 * EventGroupUpdate
 */
export type EventGroupUpdate = {
  /**
   * Name
   */
  name?: string | null
  /**
   * Description
   */
  description?: string | null
  /**
   * Start Date
   */
  start_date?: string | null
  /**
   * End Date
   */
  end_date?: string | null
  /**
   * Status
   */
  status?: ('draft' | 'published' | 'archived') | null
}

/**
 * EventListResponse
 */
export type EventListResponse = {
  /**
   * Items
   */
  items: Array<EventRead>
  /**
   * Total
   */
  total: number
  /**
   * Skip
   */
  skip: number
  /**
   * Limit
   */
  limit: number
}

/**
 * EventRead
 */
export type EventRead = {
  /**
   * Name
   */
  name: string
  /**
   * Description
   */
  description?: string | null
  /**
   * Start Date
   */
  start_date: string
  /**
   * End Date
   */
  end_date: string
  /**
   * Status
   */
  status?: 'draft' | 'published' | 'archived'
  /**
   * Created By Id
   */
  created_by_id?: string | null
  /**
   * Event Group Id
   */
  event_group_id?: string | null
  /**
   * Location
   */
  location?: string | null
  /**
   * Category
   */
  category?: string | null
  /**
   * Id
   */
  id: string
  /**
   * Created At
   */
  created_at: string
  /**
   * Updated At
   */
  updated_at: string
  /**
   * Slot Duration Minutes
   */
  slot_duration_minutes?: number | null
  /**
   * Default Start Time
   */
  default_start_time?: string | null
  /**
   * Default End Time
   */
  default_end_time?: string | null
  /**
   * People Per Slot
   */
  people_per_slot?: number | null
  /**
   * Schedule Overrides
   */
  schedule_overrides?: Array<{
    [key: string]: unknown
  }> | null
}

/**
 * EventUpdate
 */
export type EventUpdate = {
  /**
   * Name
   */
  name?: string | null
  /**
   * Description
   */
  description?: string | null
  /**
   * Start Date
   */
  start_date?: string | null
  /**
   * End Date
   */
  end_date?: string | null
  /**
   * Status
   */
  status?: ('draft' | 'published' | 'archived') | null
  /**
   * Event Group Id
   */
  event_group_id?: string | null
  /**
   * Location
   */
  location?: string | null
  /**
   * Category
   */
  category?: string | null
}

/**
 * EventUpdateWithSlots
 */
export type EventUpdateWithSlots = {
  /**
   * Name
   */
  name?: string | null
  /**
   * Description
   */
  description?: string | null
  /**
   * Start Date
   */
  start_date?: string | null
  /**
   * End Date
   */
  end_date?: string | null
  /**
   * Location
   */
  location?: string | null
  /**
   * Category
   */
  category?: string | null
  schedule: SlotGenerationConfig
}

/**
 * ExcludedSlot
 */
export type ExcludedSlot = {
  /**
   * Date
   */
  date: string
  /**
   * Start Time
   */
  start_time: string
  /**
   * End Time
   */
  end_time: string
}

/**
 * MyBookingsListResponse
 */
export type MyBookingsListResponse = {
  /**
   * Items
   */
  items: Array<BookingReadWithSlot>
  /**
   * Total
   */
  total: number
  /**
   * Skip
   */
  skip: number
  /**
   * Limit
   */
  limit: number
}

/**
 * ProfileInit
 * Profile data from Auth0 ID token for user initialization.
 */
export type ProfileInit = {
  /**
   * Email
   */
  email?: string | null
  /**
   * Name
   */
  name?: string | null
  /**
   * Nickname
   */
  nickname?: string | null
  /**
   * Picture
   */
  picture?: string | null
  /**
   * Email Verified
   */
  email_verified?: boolean | null
}

/**
 * ScheduleOverride
 */
export type ScheduleOverride = {
  /**
   * Date
   */
  date: string
  /**
   * Start Time
   */
  start_time: string
  /**
   * End Time
   */
  end_time: string
}

/**
 * SlotBatchRead
 */
export type SlotBatchRead = {
  /**
   * Event Id
   */
  event_id: string
  /**
   * Label
   */
  label?: string | null
  /**
   * Start Date
   */
  start_date: string
  /**
   * End Date
   */
  end_date: string
  /**
   * Location
   */
  location?: string | null
  /**
   * Category
   */
  category?: string | null
  /**
   * Default Start Time
   */
  default_start_time?: string | null
  /**
   * Default End Time
   */
  default_end_time?: string | null
  /**
   * Slot Duration Minutes
   */
  slot_duration_minutes?: number | null
  /**
   * People Per Slot
   */
  people_per_slot?: number | null
  /**
   * Remainder Mode
   */
  remainder_mode?: ('drop' | 'short' | 'extend') | null
  /**
   * Schedule Overrides
   */
  schedule_overrides?: Array<{
    [key: string]: unknown
  }> | null
  /**
   * Id
   */
  id: string
  /**
   * Created At
   */
  created_at: string
  /**
   * Updated At
   */
  updated_at: string
}

/**
 * SlotBookingEntry
 * A confirmed booking for a slot, with basic user info.
 */
export type SlotBookingEntry = {
  /**
   * Id
   */
  id: string
  /**
   * User Id
   */
  user_id: string
  /**
   * User Name
   */
  user_name?: string | null
  /**
   * User Email
   */
  user_email?: string | null
  /**
   * User Picture
   */
  user_picture?: string | null
  /**
   * Notes
   */
  notes?: string | null
  /**
   * Created At
   */
  created_at: string
}

/**
 * SlotGenerationConfig
 */
export type SlotGenerationConfig = {
  /**
   * Default Start Time
   */
  default_start_time: string
  /**
   * Default End Time
   */
  default_end_time: string
  /**
   * Slot Duration Minutes
   */
  slot_duration_minutes: number
  /**
   * People Per Slot
   */
  people_per_slot?: number
  /**
   * Remainder Mode
   */
  remainder_mode?: 'drop' | 'short' | 'extend'
  /**
   * Overrides
   */
  overrides?: Array<ScheduleOverride>
  /**
   * Excluded Slots
   */
  excluded_slots?: Array<ExcludedSlot>
}

/**
 * SlotRegenerationResult
 */
export type SlotRegenerationResult = {
  event: EventRead
  /**
   * Slots Added
   */
  slots_added: number
  /**
   * Slots Removed
   */
  slots_removed: number
  /**
   * Slots Kept
   */
  slots_kept: number
  /**
   * Affected Bookings
   */
  affected_bookings: Array<AffectedBookingInfo>
}

/**
 * UserAvailabilityCreate
 */
export type UserAvailabilityCreate = {
  /**
   * Availability Type
   */
  availability_type: 'fully_available' | 'specific_dates' | 'time_range'
  /**
   * Notes
   */
  notes?: string | null
  /**
   * Default Start Time
   */
  default_start_time?: string | null
  /**
   * Default End Time
   */
  default_end_time?: string | null
  /**
   * Dates
   */
  dates?: Array<string | UserAvailabilityDateInput>
}

/**
 * UserAvailabilityDateInput
 */
export type UserAvailabilityDateInput = {
  /**
   * Date
   */
  date: string
  /**
   * Start Time
   */
  start_time?: string | null
  /**
   * End Time
   */
  end_time?: string | null
}

/**
 * UserAvailabilityDateRead
 */
export type UserAvailabilityDateRead = {
  /**
   * Id
   */
  id: string
  /**
   * Slot Date
   */
  slot_date: string
  /**
   * Start Time
   */
  start_time?: string | null
  /**
   * End Time
   */
  end_time?: string | null
}

/**
 * UserAvailabilityRead
 */
export type UserAvailabilityRead = {
  /**
   * Availability Type
   */
  availability_type: 'fully_available' | 'specific_dates' | 'time_range'
  /**
   * Notes
   */
  notes?: string | null
  /**
   * Default Start Time
   */
  default_start_time?: string | null
  /**
   * Default End Time
   */
  default_end_time?: string | null
  /**
   * Id
   */
  id: string
  /**
   * User Id
   */
  user_id: string
  /**
   * Event Group Id
   */
  event_group_id: string
  /**
   * Available Dates
   */
  available_dates?: Array<UserAvailabilityDateRead>
  /**
   * Created At
   */
  created_at: string
  /**
   * Updated At
   */
  updated_at: string
}

/**
 * UserAvailabilityWithUser
 * Extended read schema for admin view — includes basic user info.
 */
export type UserAvailabilityWithUser = {
  /**
   * Availability Type
   */
  availability_type: 'fully_available' | 'specific_dates' | 'time_range'
  /**
   * Notes
   */
  notes?: string | null
  /**
   * Default Start Time
   */
  default_start_time?: string | null
  /**
   * Default End Time
   */
  default_end_time?: string | null
  /**
   * Id
   */
  id: string
  /**
   * User Id
   */
  user_id: string
  /**
   * Event Group Id
   */
  event_group_id: string
  /**
   * Available Dates
   */
  available_dates?: Array<UserAvailabilityDateRead>
  /**
   * Created At
   */
  created_at: string
  /**
   * Updated At
   */
  updated_at: string
  /**
   * User Full Name
   */
  user_full_name?: string | null
  /**
   * User Email
   */
  user_email?: string | null
}

/**
 * UserCreate
 */
export type UserCreate = {
  /**
   * Auth0 Sub
   * Auth0 subject identifier
   */
  auth0_sub: string
  /**
   * Email
   * User's email address
   */
  email?: string | null
  /**
   * Name
   * User's display name
   */
  name?: string | null
  /**
   * Picture
   * URL to user's profile picture
   */
  picture?: string | null
  /**
   * Email Verified
   * Whether the user's email is verified
   */
  email_verified?: boolean
  /**
   * Roles
   * List of role identifiers
   */
  roles?: Array<string>
  /**
   * Is Active
   * Whether the user is active
   */
  is_active?: boolean
}

/**
 * UserProfile
 */
export type UserProfile = {
  /**
   * Sub
   */
  sub: string
  /**
   * Name
   */
  name?: string | null
  /**
   * Nickname
   */
  nickname?: string | null
  /**
   * Email
   */
  email?: string | null
  /**
   * Picture
   */
  picture?: string | null
  /**
   * Bio
   */
  bio?: string | null
  /**
   * Email Verified
   */
  email_verified?: boolean
  /**
   * Roles
   * User's roles
   */
  roles?: Array<string>
  /**
   * Is Admin
   * Whether user has admin role
   */
  is_admin?: boolean
  /**
   * Is Active
   * Whether user is active
   */
  is_active?: boolean
}

/**
 * UserProfileUpdate
 */
export type UserProfileUpdate = {
  /**
   * Name
   * User's display name
   */
  name?: string | null
  /**
   * Nickname
   * User's nickname
   */
  nickname?: string | null
  /**
   * Picture
   * URL to user's profile picture
   */
  picture?: string | null
  /**
   * Bio
   * User's biography
   */
  bio?: string | null
}

/**
 * UserRead
 */
export type UserRead = {
  /**
   * Id
   */
  id: string
  /**
   * Auth0 Sub
   */
  auth0_sub: string
  /**
   * Email
   */
  email?: string | null
  /**
   * Name
   */
  name?: string | null
  /**
   * Picture
   */
  picture?: string | null
  /**
   * Roles
   */
  roles: Array<string>
  /**
   * Is Active
   */
  is_active: boolean
  /**
   * Created At
   */
  created_at: string
  /**
   * Updated At
   */
  updated_at: string
}

/**
 * UserUpdate
 */
export type UserUpdate = {
  /**
   * Email
   * User's email address
   */
  email?: string | null
  /**
   * Name
   * User's display name
   */
  name?: string | null
  /**
   * Roles
   * List of role identifiers
   */
  roles?: Array<string> | null
  /**
   * Is Active
   * Whether the user is active
   */
  is_active?: boolean | null
}

export type ValidationErrorItem = {
  loc: Array<string | number>
  msg: string
  type: string
}

export type ProblemDetails = {
  type: string
  code?: string
  title: string
  status: number
  detail?: string
  instance?: string
  errors?: Array<ValidationErrorItem>
}

export type HealthHealthCheckData = {
  body?: never
  path?: never
  query?: never
  url: '/api/v1/healthz'
}

export type HealthHealthCheckErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type HealthHealthCheckError = HealthHealthCheckErrors[keyof HealthHealthCheckErrors]

export type HealthHealthCheckResponses = {
  /**
   * Successful Response
   */
  200: unknown
}

export type HealthReadinessCheckData = {
  body?: never
  path?: never
  query?: never
  url: '/api/v1/readyz'
}

export type HealthReadinessCheckErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type HealthReadinessCheckError = HealthReadinessCheckErrors[keyof HealthReadinessCheckErrors]

export type HealthReadinessCheckResponses = {
  /**
   * Successful Response
   */
  200: unknown
}

export type UsersUpdateUserProfileData = {
  body: UserProfileUpdate
  path?: never
  query?: never
  url: '/api/v1/users/me'
}

export type UsersUpdateUserProfileErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type UsersUpdateUserProfileError =
  UsersUpdateUserProfileErrors[keyof UsersUpdateUserProfileErrors]

export type UsersUpdateUserProfileResponses = {
  /**
   * Successful Response
   */
  200: UserProfile
}

export type UsersUpdateUserProfileResponse =
  UsersUpdateUserProfileResponses[keyof UsersUpdateUserProfileResponses]

export type UsersGetCurrentUserProfileData = {
  /**
   * Profile Init
   */
  body?: ProfileInit | null
  path?: never
  query?: never
  url: '/api/v1/users/me'
}

export type UsersGetCurrentUserProfileErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type UsersGetCurrentUserProfileError =
  UsersGetCurrentUserProfileErrors[keyof UsersGetCurrentUserProfileErrors]

export type UsersGetCurrentUserProfileResponses = {
  /**
   * Successful Response
   */
  200: UserProfile
}

export type UsersGetCurrentUserProfileResponse =
  UsersGetCurrentUserProfileResponses[keyof UsersGetCurrentUserProfileResponses]

export type UsersGetAuth0ManagementUrlData = {
  body?: never
  path?: never
  query?: never
  url: '/api/v1/users/auth0-management-url'
}

export type UsersGetAuth0ManagementUrlErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type UsersGetAuth0ManagementUrlError =
  UsersGetAuth0ManagementUrlErrors[keyof UsersGetAuth0ManagementUrlErrors]

export type UsersGetAuth0ManagementUrlResponses = {
  /**
   * Response Users-Get Auth0 Management Url
   * Successful Response
   */
  200: {
    [key: string]: string
  }
}

export type UsersGetAuth0ManagementUrlResponse =
  UsersGetAuth0ManagementUrlResponses[keyof UsersGetAuth0ManagementUrlResponses]

export type UsersListUsersData = {
  body?: never
  path?: never
  query?: {
    /**
     * Skip
     */
    skip?: number
    /**
     * Limit
     */
    limit?: number
  }
  url: '/api/v1/users/'
}

export type UsersListUsersErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type UsersListUsersError = UsersListUsersErrors[keyof UsersListUsersErrors]

export type UsersListUsersResponses = {
  /**
   * Response Users-List Users
   * Successful Response
   */
  200: Array<UserRead>
}

export type UsersListUsersResponse = UsersListUsersResponses[keyof UsersListUsersResponses]

export type UsersCreateUserData = {
  body: UserCreate
  path?: never
  query?: never
  url: '/api/v1/users/'
}

export type UsersCreateUserErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type UsersCreateUserError = UsersCreateUserErrors[keyof UsersCreateUserErrors]

export type UsersCreateUserResponses = {
  /**
   * Successful Response
   */
  201: UserRead
}

export type UsersCreateUserResponse = UsersCreateUserResponses[keyof UsersCreateUserResponses]

export type UsersDeleteUserData = {
  body?: never
  path: {
    /**
     * User Id
     */
    user_id: string
  }
  query?: never
  url: '/api/v1/users/{user_id}'
}

export type UsersDeleteUserErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type UsersDeleteUserError = UsersDeleteUserErrors[keyof UsersDeleteUserErrors]

export type UsersDeleteUserResponses = {
  /**
   * Successful Response
   */
  200: UserRead
}

export type UsersDeleteUserResponse = UsersDeleteUserResponses[keyof UsersDeleteUserResponses]

export type UsersGetUserData = {
  body?: never
  path: {
    /**
     * User Id
     */
    user_id: string
  }
  query?: never
  url: '/api/v1/users/{user_id}'
}

export type UsersGetUserErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type UsersGetUserError = UsersGetUserErrors[keyof UsersGetUserErrors]

export type UsersGetUserResponses = {
  /**
   * Successful Response
   */
  200: UserRead
}

export type UsersGetUserResponse = UsersGetUserResponses[keyof UsersGetUserResponses]

export type UsersUpdateUserData = {
  body: UserUpdate
  path: {
    /**
     * User Id
     */
    user_id: string
  }
  query?: never
  url: '/api/v1/users/{user_id}'
}

export type UsersUpdateUserErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type UsersUpdateUserError = UsersUpdateUserErrors[keyof UsersUpdateUserErrors]

export type UsersUpdateUserResponses = {
  /**
   * Successful Response
   */
  200: UserRead
}

export type UsersUpdateUserResponse = UsersUpdateUserResponses[keyof UsersUpdateUserResponses]

export type EventsListEventsData = {
  body?: never
  path?: never
  query?: {
    /**
     * Skip
     */
    skip?: number
    /**
     * Limit
     */
    limit?: number
    /**
     * Search
     */
    search?: string | null
    /**
     * Status
     */
    status?: ('draft' | 'published' | 'archived') | null
    /**
     * My Bookings
     */
    my_bookings?: boolean
  }
  url: '/api/v1/events/'
}

export type EventsListEventsErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type EventsListEventsError = EventsListEventsErrors[keyof EventsListEventsErrors]

export type EventsListEventsResponses = {
  /**
   * Successful Response
   */
  200: EventListResponse
}

export type EventsListEventsResponse = EventsListEventsResponses[keyof EventsListEventsResponses]

export type EventsCreateEventData = {
  body: EventCreate
  path?: never
  query?: never
  url: '/api/v1/events/'
}

export type EventsCreateEventErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type EventsCreateEventError = EventsCreateEventErrors[keyof EventsCreateEventErrors]

export type EventsCreateEventResponses = {
  /**
   * Successful Response
   */
  201: EventRead
}

export type EventsCreateEventResponse = EventsCreateEventResponses[keyof EventsCreateEventResponses]

export type EventsDeleteEventData = {
  body?: never
  path: {
    /**
     * Event Id
     */
    event_id: string
  }
  query?: {
    /**
     * Cancellation Reason
     */
    cancellation_reason?: string | null
  }
  url: '/api/v1/events/{event_id}'
}

export type EventsDeleteEventErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type EventsDeleteEventError = EventsDeleteEventErrors[keyof EventsDeleteEventErrors]

export type EventsDeleteEventResponses = {
  /**
   * Successful Response
   */
  204: void
}

export type EventsDeleteEventResponse = EventsDeleteEventResponses[keyof EventsDeleteEventResponses]

export type EventsGetEventData = {
  body?: never
  path: {
    /**
     * Event Id
     */
    event_id: string
  }
  query?: never
  url: '/api/v1/events/{event_id}'
}

export type EventsGetEventErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type EventsGetEventError = EventsGetEventErrors[keyof EventsGetEventErrors]

export type EventsGetEventResponses = {
  /**
   * Successful Response
   */
  200: EventRead
}

export type EventsGetEventResponse = EventsGetEventResponses[keyof EventsGetEventResponses]

export type EventsUpdateEventData = {
  body: EventUpdate
  path: {
    /**
     * Event Id
     */
    event_id: string
  }
  query?: never
  url: '/api/v1/events/{event_id}'
}

export type EventsUpdateEventErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type EventsUpdateEventError = EventsUpdateEventErrors[keyof EventsUpdateEventErrors]

export type EventsUpdateEventResponses = {
  /**
   * Successful Response
   */
  200: EventRead
}

export type EventsUpdateEventResponse = EventsUpdateEventResponses[keyof EventsUpdateEventResponses]

export type EventsCreateEventWithSlotsData = {
  body: EventCreateWithSlots
  path?: never
  query?: never
  url: '/api/v1/events/with-slots'
}

export type EventsCreateEventWithSlotsErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type EventsCreateEventWithSlotsError =
  EventsCreateEventWithSlotsErrors[keyof EventsCreateEventWithSlotsErrors]

export type EventsCreateEventWithSlotsResponses = {
  /**
   * Successful Response
   */
  201: EventCreateWithSlotsResponse
}

export type EventsCreateEventWithSlotsResponse =
  EventsCreateEventWithSlotsResponses[keyof EventsCreateEventWithSlotsResponses]

export type EventsAddSlotsToEventData = {
  body: AddSlotsToEvent
  path: {
    /**
     * Event Id
     */
    event_id: string
  }
  query?: never
  url: '/api/v1/events/{event_id}/add-slots'
}

export type EventsAddSlotsToEventErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type EventsAddSlotsToEventError =
  EventsAddSlotsToEventErrors[keyof EventsAddSlotsToEventErrors]

export type EventsAddSlotsToEventResponses = {
  /**
   * Successful Response
   */
  201: AddSlotsResponse
}

export type EventsAddSlotsToEventResponse =
  EventsAddSlotsToEventResponses[keyof EventsAddSlotsToEventResponses]

export type EventsRegenerateEventSlotsData = {
  body: EventUpdateWithSlots
  path: {
    /**
     * Event Id
     */
    event_id: string
  }
  query?: {
    /**
     * Dry Run
     */
    dry_run?: boolean
    /**
     * Batch Id
     */
    batch_id?: string | null
  }
  url: '/api/v1/events/{event_id}/regenerate-slots'
}

export type EventsRegenerateEventSlotsErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type EventsRegenerateEventSlotsError =
  EventsRegenerateEventSlotsErrors[keyof EventsRegenerateEventSlotsErrors]

export type EventsRegenerateEventSlotsResponses = {
  /**
   * Successful Response
   */
  200: SlotRegenerationResult
}

export type EventsRegenerateEventSlotsResponse =
  EventsRegenerateEventSlotsResponses[keyof EventsRegenerateEventSlotsResponses]

export type EventsListBatchesData = {
  body?: never
  path: {
    /**
     * Event Id
     */
    event_id: string
  }
  query?: never
  url: '/api/v1/events/{event_id}/batches'
}

export type EventsListBatchesErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type EventsListBatchesError = EventsListBatchesErrors[keyof EventsListBatchesErrors]

export type EventsListBatchesResponses = {
  /**
   * Response Events-List Batches
   * Successful Response
   */
  200: Array<SlotBatchRead>
}

export type EventsListBatchesResponse = EventsListBatchesResponses[keyof EventsListBatchesResponses]

export type EventsDeleteBatchData = {
  body?: never
  path: {
    /**
     * Event Id
     */
    event_id: string
    /**
     * Batch Id
     */
    batch_id: string
  }
  query?: {
    /**
     * Cancellation Reason
     */
    cancellation_reason?: string | null
  }
  url: '/api/v1/events/{event_id}/batches/{batch_id}'
}

export type EventsDeleteBatchErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type EventsDeleteBatchError = EventsDeleteBatchErrors[keyof EventsDeleteBatchErrors]

export type EventsDeleteBatchResponses = {
  /**
   * Successful Response
   */
  204: void
}

export type EventsDeleteBatchResponse = EventsDeleteBatchResponses[keyof EventsDeleteBatchResponses]

export type DutySlotsListDutySlotsData = {
  body?: never
  path?: never
  query?: {
    /**
     * Event Id
     */
    event_id?: string | null
    /**
     * Category
     */
    category?: string | null
    /**
     * Search
     */
    search?: string | null
    /**
     * Skip
     */
    skip?: number
    /**
     * Limit
     */
    limit?: number
  }
  url: '/api/v1/duty-slots/'
}

export type DutySlotsListDutySlotsErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type DutySlotsListDutySlotsError =
  DutySlotsListDutySlotsErrors[keyof DutySlotsListDutySlotsErrors]

export type DutySlotsListDutySlotsResponses = {
  /**
   * Successful Response
   */
  200: DutySlotListResponse
}

export type DutySlotsListDutySlotsResponse =
  DutySlotsListDutySlotsResponses[keyof DutySlotsListDutySlotsResponses]

export type DutySlotsCreateDutySlotData = {
  body: DutySlotCreate
  path?: never
  query?: never
  url: '/api/v1/duty-slots/'
}

export type DutySlotsCreateDutySlotErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type DutySlotsCreateDutySlotError =
  DutySlotsCreateDutySlotErrors[keyof DutySlotsCreateDutySlotErrors]

export type DutySlotsCreateDutySlotResponses = {
  /**
   * Successful Response
   */
  201: DutySlotRead
}

export type DutySlotsCreateDutySlotResponse =
  DutySlotsCreateDutySlotResponses[keyof DutySlotsCreateDutySlotResponses]

export type DutySlotsDeleteDutySlotData = {
  body?: never
  path: {
    /**
     * Slot Id
     */
    slot_id: string
  }
  query?: {
    /**
     * Cancellation Reason
     */
    cancellation_reason?: string | null
  }
  url: '/api/v1/duty-slots/{slot_id}'
}

export type DutySlotsDeleteDutySlotErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type DutySlotsDeleteDutySlotError =
  DutySlotsDeleteDutySlotErrors[keyof DutySlotsDeleteDutySlotErrors]

export type DutySlotsDeleteDutySlotResponses = {
  /**
   * Successful Response
   */
  204: void
}

export type DutySlotsDeleteDutySlotResponse =
  DutySlotsDeleteDutySlotResponses[keyof DutySlotsDeleteDutySlotResponses]

export type DutySlotsGetDutySlotData = {
  body?: never
  path: {
    /**
     * Slot Id
     */
    slot_id: string | null
  }
  query?: never
  url: '/api/v1/duty-slots/{slot_id}'
}

export type DutySlotsGetDutySlotErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type DutySlotsGetDutySlotError = DutySlotsGetDutySlotErrors[keyof DutySlotsGetDutySlotErrors]

export type DutySlotsGetDutySlotResponses = {
  /**
   * Successful Response
   */
  200: DutySlotRead
}

export type DutySlotsGetDutySlotResponse =
  DutySlotsGetDutySlotResponses[keyof DutySlotsGetDutySlotResponses]

export type DutySlotsUpdateDutySlotData = {
  body: DutySlotUpdate
  path: {
    /**
     * Slot Id
     */
    slot_id: string
  }
  query?: never
  url: '/api/v1/duty-slots/{slot_id}'
}

export type DutySlotsUpdateDutySlotErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type DutySlotsUpdateDutySlotError =
  DutySlotsUpdateDutySlotErrors[keyof DutySlotsUpdateDutySlotErrors]

export type DutySlotsUpdateDutySlotResponses = {
  /**
   * Successful Response
   */
  200: DutySlotRead
}

export type DutySlotsUpdateDutySlotResponse =
  DutySlotsUpdateDutySlotResponses[keyof DutySlotsUpdateDutySlotResponses]

export type DutySlotsListSlotBookingsData = {
  body?: never
  path: {
    /**
     * Slot Id
     */
    slot_id: string
  }
  query?: never
  url: '/api/v1/duty-slots/{slot_id}/bookings'
}

export type DutySlotsListSlotBookingsErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type DutySlotsListSlotBookingsError =
  DutySlotsListSlotBookingsErrors[keyof DutySlotsListSlotBookingsErrors]

export type DutySlotsListSlotBookingsResponses = {
  /**
   * Response Duty-Slots-List Slot Bookings
   * Successful Response
   */
  200: Array<SlotBookingEntry>
}

export type DutySlotsListSlotBookingsResponse =
  DutySlotsListSlotBookingsResponses[keyof DutySlotsListSlotBookingsResponses]

export type BookingsListMyBookingsData = {
  body?: never
  path?: never
  query?: {
    /**
     * Skip
     */
    skip?: number
    /**
     * Limit
     */
    limit?: number
    /**
     * Status
     */
    status?: string | null
    /**
     * Date From
     */
    date_from?: string | null
    /**
     * Date To
     */
    date_to?: string | null
  }
  url: '/api/v1/bookings/me'
}

export type BookingsListMyBookingsErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type BookingsListMyBookingsError =
  BookingsListMyBookingsErrors[keyof BookingsListMyBookingsErrors]

export type BookingsListMyBookingsResponses = {
  /**
   * Successful Response
   */
  200: MyBookingsListResponse
}

export type BookingsListMyBookingsResponse =
  BookingsListMyBookingsResponses[keyof BookingsListMyBookingsResponses]

export type BookingsCreateBookingData = {
  body: BookingCreate
  path?: never
  query?: never
  url: '/api/v1/bookings/'
}

export type BookingsCreateBookingErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type BookingsCreateBookingError =
  BookingsCreateBookingErrors[keyof BookingsCreateBookingErrors]

export type BookingsCreateBookingResponses = {
  /**
   * Successful Response
   */
  201: BookingRead
}

export type BookingsCreateBookingResponse =
  BookingsCreateBookingResponses[keyof BookingsCreateBookingResponses]

export type BookingsCancelBookingData = {
  body?: never
  path: {
    /**
     * Booking Id
     */
    booking_id: string
  }
  query?: never
  url: '/api/v1/bookings/{booking_id}'
}

export type BookingsCancelBookingErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type BookingsCancelBookingError =
  BookingsCancelBookingErrors[keyof BookingsCancelBookingErrors]

export type BookingsCancelBookingResponses = {
  /**
   * Successful Response
   */
  200: BookingRead
}

export type BookingsCancelBookingResponse =
  BookingsCancelBookingResponses[keyof BookingsCancelBookingResponses]

export type BookingsGetBookingData = {
  body?: never
  path: {
    /**
     * Booking Id
     */
    booking_id: string
  }
  query?: never
  url: '/api/v1/bookings/{booking_id}'
}

export type BookingsGetBookingErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type BookingsGetBookingError = BookingsGetBookingErrors[keyof BookingsGetBookingErrors]

export type BookingsGetBookingResponses = {
  /**
   * Successful Response
   */
  200: BookingRead
}

export type BookingsGetBookingResponse =
  BookingsGetBookingResponses[keyof BookingsGetBookingResponses]

export type BookingsUpdateBookingData = {
  body: BookingUpdate
  path: {
    /**
     * Booking Id
     */
    booking_id: string
  }
  query?: never
  url: '/api/v1/bookings/{booking_id}'
}

export type BookingsUpdateBookingErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type BookingsUpdateBookingError =
  BookingsUpdateBookingErrors[keyof BookingsUpdateBookingErrors]

export type BookingsUpdateBookingResponses = {
  /**
   * Successful Response
   */
  200: BookingRead
}

export type BookingsUpdateBookingResponse =
  BookingsUpdateBookingResponses[keyof BookingsUpdateBookingResponses]

export type BookingsDismissBookingData = {
  body?: never
  path: {
    /**
     * Booking Id
     */
    booking_id: string
  }
  query?: never
  url: '/api/v1/bookings/{booking_id}/dismiss'
}

export type BookingsDismissBookingErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type BookingsDismissBookingError =
  BookingsDismissBookingErrors[keyof BookingsDismissBookingErrors]

export type BookingsDismissBookingResponses = {
  /**
   * Successful Response
   */
  204: void
}

export type BookingsDismissBookingResponse =
  BookingsDismissBookingResponses[keyof BookingsDismissBookingResponses]

export type EventGroupsListEventGroupsData = {
  body?: never
  path?: never
  query?: {
    /**
     * Skip
     */
    skip?: number
    /**
     * Limit
     */
    limit?: number
    /**
     * Search
     */
    search?: string | null
    /**
     * Status
     */
    status?: ('draft' | 'published' | 'archived') | null
  }
  url: '/api/v1/event-groups/'
}

export type EventGroupsListEventGroupsErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type EventGroupsListEventGroupsError =
  EventGroupsListEventGroupsErrors[keyof EventGroupsListEventGroupsErrors]

export type EventGroupsListEventGroupsResponses = {
  /**
   * Successful Response
   */
  200: EventGroupListResponse
}

export type EventGroupsListEventGroupsResponse =
  EventGroupsListEventGroupsResponses[keyof EventGroupsListEventGroupsResponses]

export type EventGroupsCreateEventGroupData = {
  body: EventGroupCreate
  path?: never
  query?: never
  url: '/api/v1/event-groups/'
}

export type EventGroupsCreateEventGroupErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type EventGroupsCreateEventGroupError =
  EventGroupsCreateEventGroupErrors[keyof EventGroupsCreateEventGroupErrors]

export type EventGroupsCreateEventGroupResponses = {
  /**
   * Successful Response
   */
  201: EventGroupRead
}

export type EventGroupsCreateEventGroupResponse =
  EventGroupsCreateEventGroupResponses[keyof EventGroupsCreateEventGroupResponses]

export type EventGroupsDeleteEventGroupData = {
  body?: never
  path: {
    /**
     * Group Id
     */
    group_id: string
  }
  query?: never
  url: '/api/v1/event-groups/{group_id}'
}

export type EventGroupsDeleteEventGroupErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type EventGroupsDeleteEventGroupError =
  EventGroupsDeleteEventGroupErrors[keyof EventGroupsDeleteEventGroupErrors]

export type EventGroupsDeleteEventGroupResponses = {
  /**
   * Successful Response
   */
  204: void
}

export type EventGroupsDeleteEventGroupResponse =
  EventGroupsDeleteEventGroupResponses[keyof EventGroupsDeleteEventGroupResponses]

export type EventGroupsGetEventGroupData = {
  body?: never
  path: {
    /**
     * Group Id
     */
    group_id: string
  }
  query?: never
  url: '/api/v1/event-groups/{group_id}'
}

export type EventGroupsGetEventGroupErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type EventGroupsGetEventGroupError =
  EventGroupsGetEventGroupErrors[keyof EventGroupsGetEventGroupErrors]

export type EventGroupsGetEventGroupResponses = {
  /**
   * Successful Response
   */
  200: EventGroupRead
}

export type EventGroupsGetEventGroupResponse =
  EventGroupsGetEventGroupResponses[keyof EventGroupsGetEventGroupResponses]

export type EventGroupsUpdateEventGroupData = {
  body: EventGroupUpdate
  path: {
    /**
     * Group Id
     */
    group_id: string
  }
  query?: never
  url: '/api/v1/event-groups/{group_id}'
}

export type EventGroupsUpdateEventGroupErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type EventGroupsUpdateEventGroupError =
  EventGroupsUpdateEventGroupErrors[keyof EventGroupsUpdateEventGroupErrors]

export type EventGroupsUpdateEventGroupResponses = {
  /**
   * Successful Response
   */
  200: EventGroupRead
}

export type EventGroupsUpdateEventGroupResponse =
  EventGroupsUpdateEventGroupResponses[keyof EventGroupsUpdateEventGroupResponses]

export type EventGroupsListGroupAvailabilitiesData = {
  body?: never
  path: {
    /**
     * Group Id
     */
    group_id: string
  }
  query?: {
    /**
     * Skip
     */
    skip?: number
    /**
     * Limit
     */
    limit?: number
  }
  url: '/api/v1/event-groups/{group_id}/availabilities'
}

export type EventGroupsListGroupAvailabilitiesErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type EventGroupsListGroupAvailabilitiesError =
  EventGroupsListGroupAvailabilitiesErrors[keyof EventGroupsListGroupAvailabilitiesErrors]

export type EventGroupsListGroupAvailabilitiesResponses = {
  /**
   * Response Event-Groups-List Group Availabilities
   * Successful Response
   */
  200: Array<UserAvailabilityWithUser>
}

export type EventGroupsListGroupAvailabilitiesResponse =
  EventGroupsListGroupAvailabilitiesResponses[keyof EventGroupsListGroupAvailabilitiesResponses]

export type EventGroupsDeleteMyAvailabilityData = {
  body?: never
  path: {
    /**
     * Group Id
     */
    group_id: string
  }
  query?: never
  url: '/api/v1/event-groups/{group_id}/availability/me'
}

export type EventGroupsDeleteMyAvailabilityErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type EventGroupsDeleteMyAvailabilityError =
  EventGroupsDeleteMyAvailabilityErrors[keyof EventGroupsDeleteMyAvailabilityErrors]

export type EventGroupsDeleteMyAvailabilityResponses = {
  /**
   * Successful Response
   */
  204: void
}

export type EventGroupsDeleteMyAvailabilityResponse =
  EventGroupsDeleteMyAvailabilityResponses[keyof EventGroupsDeleteMyAvailabilityResponses]

export type EventGroupsGetMyAvailabilityData = {
  body?: never
  path: {
    /**
     * Group Id
     */
    group_id: string
  }
  query?: never
  url: '/api/v1/event-groups/{group_id}/availability/me'
}

export type EventGroupsGetMyAvailabilityErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type EventGroupsGetMyAvailabilityError =
  EventGroupsGetMyAvailabilityErrors[keyof EventGroupsGetMyAvailabilityErrors]

export type EventGroupsGetMyAvailabilityResponses = {
  /**
   * Successful Response
   */
  200: UserAvailabilityRead
}

export type EventGroupsGetMyAvailabilityResponse =
  EventGroupsGetMyAvailabilityResponses[keyof EventGroupsGetMyAvailabilityResponses]

export type EventGroupsSetMyAvailabilityData = {
  body: UserAvailabilityCreate
  path: {
    /**
     * Group Id
     */
    group_id: string
  }
  query?: never
  url: '/api/v1/event-groups/{group_id}/availability'
}

export type EventGroupsSetMyAvailabilityErrors = {
  /**
   * Bad Request
   */
  400: ProblemDetails
  /**
   * Unauthorized
   */
  401: ProblemDetails
  /**
   * Forbidden
   */
  403: ProblemDetails
  /**
   * Not Found
   */
  404: ProblemDetails
  /**
   * Conflict
   */
  409: ProblemDetails
  /**
   * Validation Error
   */
  422: ProblemDetails
  /**
   * Too Many Requests
   */
  429: ProblemDetails
  /**
   * Internal Server Error
   */
  500: ProblemDetails
}

export type EventGroupsSetMyAvailabilityError =
  EventGroupsSetMyAvailabilityErrors[keyof EventGroupsSetMyAvailabilityErrors]

export type EventGroupsSetMyAvailabilityResponses = {
  /**
   * Successful Response
   */
  201: UserAvailabilityRead
}

export type EventGroupsSetMyAvailabilityResponse =
  EventGroupsSetMyAvailabilityResponses[keyof EventGroupsSetMyAvailabilityResponses]

export type ClientOptions = {
  baseURL: `${string}://${string}` | (string & {})
}
