// This file is auto-generated by @hey-api/openapi-ts
import { z } from 'zod'

/**
 * EventRead
 */
export const zEventRead = z.object({
  name: z.string(),
  description: z.optional(z.union([z.string(), z.null()])),
  start_date: z.iso.date(),
  end_date: z.iso.date(),
  status: z.optional(z.enum(['draft', 'published', 'archived'])),
  created_by_id: z.optional(z.union([z.uuid(), z.null()])),
  event_group_id: z.optional(z.union([z.uuid(), z.null()])),
  location: z.optional(z.union([z.string(), z.null()])),
  category: z.optional(z.union([z.string(), z.null()])),
  id: z.uuid(),
  created_at: z.iso.datetime(),
  updated_at: z.iso.datetime(),
  slot_duration_minutes: z.optional(z.union([z.int(), z.null()])),
  default_start_time: z.optional(z.union([z.iso.time(), z.null()])),
  default_end_time: z.optional(z.union([z.iso.time(), z.null()])),
  people_per_slot: z.optional(z.union([z.int(), z.null()])),
  schedule_overrides: z.optional(z.union([z.array(z.object({})), z.null()])),
})

/**
 * AddSlotsResponse
 */
export const zAddSlotsResponse = z.object({
  event: zEventRead,
  slots_added: z.int(),
})

/**
 * ScheduleOverride
 */
export const zScheduleOverride = z.object({
  date: z.iso.date(),
  start_time: z.iso.time(),
  end_time: z.iso.time(),
})

/**
 * ExcludedSlot
 */
export const zExcludedSlot = z.object({
  date: z.iso.date(),
  start_time: z.iso.time(),
  end_time: z.iso.time(),
})

/**
 * SlotGenerationConfig
 */
export const zSlotGenerationConfig = z.object({
  default_start_time: z.iso.time(),
  default_end_time: z.iso.time(),
  slot_duration_minutes: z.int(),
  people_per_slot: z.optional(z.int()).default(1),
  remainder_mode: z.optional(z.enum(['drop', 'short', 'extend'])),
  overrides: z.optional(z.array(zScheduleOverride)).default([]),
  excluded_slots: z.optional(z.array(zExcludedSlot)).default([]),
})

/**
 * AddSlotsToEvent
 */
export const zAddSlotsToEvent = z.object({
  start_date: z.iso.date(),
  end_date: z.iso.date(),
  location: z.optional(z.union([z.string(), z.null()])),
  category: z.optional(z.union([z.string(), z.null()])),
  schedule: zSlotGenerationConfig,
})

/**
 * AffectedBookingInfo
 */
export const zAffectedBookingInfo = z.object({
  booking_id: z.uuid(),
  user_id: z.uuid(),
  slot_title: z.string(),
  slot_date: z.iso.date(),
  slot_start_time: z.optional(z.union([z.iso.time(), z.null()])),
  slot_end_time: z.optional(z.union([z.iso.time(), z.null()])),
})

/**
 * BookingCreate
 * User only provides the slot and optional notes. user_id is set server-side.
 */
export const zBookingCreate = z
  .object({
    duty_slot_id: z.uuid(),
    notes: z.optional(z.union([z.string(), z.null()])),
  })
  .register(z.globalRegistry, {
    description: 'User only provides the slot and optional notes. user_id is set server-side.',
  })

/**
 * BookingRead
 */
export const zBookingRead = z.object({
  duty_slot_id: z.optional(z.union([z.uuid(), z.null()])),
  user_id: z.uuid(),
  status: z.optional(z.enum(['confirmed', 'cancelled'])),
  notes: z.optional(z.union([z.string(), z.null()])),
  id: z.uuid(),
  created_at: z.iso.datetime(),
  updated_at: z.iso.datetime(),
  cancellation_reason: z.optional(z.union([z.string(), z.null()])),
  cancelled_slot_title: z.optional(z.union([z.string(), z.null()])),
  cancelled_slot_date: z.optional(z.union([z.iso.date(), z.null()])),
  cancelled_slot_start_time: z.optional(z.union([z.iso.time(), z.null()])),
  cancelled_slot_end_time: z.optional(z.union([z.iso.time(), z.null()])),
  cancelled_event_name: z.optional(z.union([z.string(), z.null()])),
})

/**
 * DutySlotSummary
 * Lightweight slot info nested inside a booking response.
 */
export const zDutySlotSummary = z
  .object({
    id: z.uuid(),
    event_id: z.uuid(),
    title: z.string(),
    date: z.iso.date(),
    start_time: z.optional(z.union([z.iso.time(), z.null()])),
    end_time: z.optional(z.union([z.iso.time(), z.null()])),
    location: z.optional(z.union([z.string(), z.null()])),
    category: z.optional(z.union([z.string(), z.null()])),
    event_name: z.optional(z.union([z.string(), z.null()])),
  })
  .register(z.globalRegistry, {
    description: 'Lightweight slot info nested inside a booking response.',
  })

/**
 * BookingReadWithSlot
 * BookingRead enriched with nested slot + event name (for /me endpoint).
 */
export const zBookingReadWithSlot = z
  .object({
    duty_slot_id: z.optional(z.union([z.uuid(), z.null()])),
    user_id: z.uuid(),
    status: z.optional(z.enum(['confirmed', 'cancelled'])),
    notes: z.optional(z.union([z.string(), z.null()])),
    id: z.uuid(),
    created_at: z.iso.datetime(),
    updated_at: z.iso.datetime(),
    cancellation_reason: z.optional(z.union([z.string(), z.null()])),
    cancelled_slot_title: z.optional(z.union([z.string(), z.null()])),
    cancelled_slot_date: z.optional(z.union([z.iso.date(), z.null()])),
    cancelled_slot_start_time: z.optional(z.union([z.iso.time(), z.null()])),
    cancelled_slot_end_time: z.optional(z.union([z.iso.time(), z.null()])),
    cancelled_event_name: z.optional(z.union([z.string(), z.null()])),
    duty_slot: z.optional(z.union([zDutySlotSummary, z.null()])),
  })
  .register(z.globalRegistry, {
    description: 'BookingRead enriched with nested slot + event name (for /me endpoint).',
  })

/**
 * BookingReminderCreate
 * User provides the offset and channels; remind_at is computed server-side.
 */
export const zBookingReminderCreate = z
  .object({
    offset_minutes: z.unknown(),
    channels: z.optional(z.array(z.enum(['email', 'push', 'telegram'])).min(1)).default(['push']),
  })
  .register(z.globalRegistry, {
    description: 'User provides the offset and channels; remind_at is computed server-side.',
  })

/**
 * BookingReminderRead
 */
export const zBookingReminderRead = z.object({
  id: z.uuid(),
  booking_id: z.uuid(),
  offset_minutes: z.int(),
  channels: z.array(z.string()),
  remind_at: z.iso.datetime(),
  status: z.enum(['pending', 'sent', 'cancelled', 'expired']),
  created_at: z.iso.datetime(),
})

/**
 * BookingReminderListResponse
 */
export const zBookingReminderListResponse = z.object({
  items: z.array(zBookingReminderRead),
})

/**
 * BookingUpdate
 */
export const zBookingUpdate = z.object({
  status: z.optional(z.union([z.enum(['confirmed', 'cancelled']), z.null()])),
  notes: z.optional(z.union([z.string(), z.null()])),
  cancellation_reason: z.optional(z.union([z.string(), z.null()])),
})

/**
 * BookingsByHour
 */
export const zBookingsByHour = z.object({
  hour: z.int(),
  booking_count: z.int(),
})

/**
 * BookingsTrendPoint
 */
export const zBookingsTrendPoint = z.object({
  date: z.iso.date(),
  confirmed: z.int(),
  cancelled: z.int(),
})

/**
 * CalendarFeedRead
 * Response for calendar feed management endpoints.
 */
export const zCalendarFeedRead = z
  .object({
    id: z.uuid(),
    feed_url: z.string(),
    is_enabled: z.boolean(),
    last_accessed_at: z.optional(z.union([z.iso.datetime(), z.null()])),
    created_at: z.iso.datetime(),
  })
  .register(z.globalRegistry, {
    description: 'Response for calendar feed management endpoints.',
  })

/**
 * CategoryBreakdown
 */
export const zCategoryBreakdown = z.object({
  category: z.union([z.string(), z.null()]),
  slot_count: z.int(),
  total_capacity: z.int(),
  confirmed_bookings: z.int(),
  fill_rate: z.number(),
})

/**
 * DashboardBookingItem
 * Booking with inline slot info for calendar display — avoids N+1.
 */
export const zDashboardBookingItem = z
  .object({
    id: z.uuid(),
    slot_id: z.uuid(),
    date: z.iso.date(),
    title: z.string(),
    start_time: z.optional(z.union([z.iso.time(), z.null()])),
    end_time: z.optional(z.union([z.iso.time(), z.null()])),
  })
  .register(z.globalRegistry, {
    description: 'Booking with inline slot info for calendar display — avoids N+1.',
  })

/**
 * DashboardEvent
 * Slim event for the dashboard calendar.
 */
export const zDashboardEvent = z
  .object({
    id: z.uuid(),
    name: z.string(),
    status: z.string(),
    description: z.optional(z.union([z.string(), z.null()])),
    location: z.optional(z.union([z.string(), z.null()])),
    start_date: z.iso.date(),
    end_date: z.iso.date(),
  })
  .register(z.globalRegistry, {
    description: 'Slim event for the dashboard calendar.',
  })

/**
 * DashboardEventGroup
 * Slim event group for the dashboard calendar.
 */
export const zDashboardEventGroup = z
  .object({
    id: z.uuid(),
    name: z.string(),
    start_date: z.iso.date(),
    end_date: z.iso.date(),
  })
  .register(z.globalRegistry, {
    description: 'Slim event group for the dashboard calendar.',
  })

/**
 * DashboardFeedResponse
 */
export const zDashboardFeedResponse = z.object({
  events: z.array(zDashboardEvent),
  event_count: z.int(),
  event_groups: z.array(zDashboardEventGroup),
  bookings: z.array(zDashboardBookingItem),
  booking_count: z.int(),
  pending_user_count: z.optional(z.union([z.int(), z.null()])),
})

/**
 * ReminderOffsetEntry
 * A single default reminder: offset + which channels to use.
 */
export const zReminderOffsetEntry = z
  .object({
    offset_minutes: z.unknown(),
    channels: z.optional(z.array(z.enum(['email', 'push', 'telegram'])).min(1)).default(['push']),
  })
  .register(z.globalRegistry, {
    description: 'A single default reminder: offset + which channels to use.',
  })

/**
 * DefaultReminderOffsetsRead
 */
export const zDefaultReminderOffsetsRead = z.object({
  default_reminder_offsets: z.array(zReminderOffsetEntry),
})

/**
 * DefaultReminderOffsetsUpdate
 */
export const zDefaultReminderOffsetsUpdate = z.object({
  default_reminder_offsets: z.array(zReminderOffsetEntry).max(5),
})

/**
 * DemoDataCreatedResponse
 */
export const zDemoDataCreatedResponse = z.object({
  event_groups_created: z.int(),
  events_created: z.int(),
  users_created: z.int(),
  duty_slots_created: z.int(),
  bookings_created: z.int(),
})

/**
 * DemoDataDeletedResponse
 */
export const zDemoDataDeletedResponse = z.object({
  events_deleted: z.int(),
  event_groups_deleted: z.int(),
  users_deleted: z.int(),
  duty_slots_deleted: z.int(),
  bookings_deleted: z.int(),
})

/**
 * DemoDataParams
 */
export const zDemoDataParams = z.object({
  num_events: z.optional(z.int().gte(1).lte(50)).default(10),
  num_event_groups: z.optional(z.int().gte(0).lte(10)).default(3),
  num_users: z.optional(z.int().gte(0).lte(20)).default(5),
  num_slots_per_event: z.optional(z.int().gte(1).lte(20)).default(4),
  publish_events: z.optional(z.boolean()).default(true),
})

/**
 * DutySlotCreate
 */
export const zDutySlotCreate = z.object({
  event_id: z.uuid(),
  title: z.string(),
  description: z.optional(z.union([z.string(), z.null()])),
  date: z.iso.date(),
  start_time: z.optional(z.union([z.iso.time(), z.null()])),
  end_time: z.optional(z.union([z.iso.time(), z.null()])),
  location: z.optional(z.union([z.string(), z.null()])),
  category: z.optional(z.union([z.string(), z.null()])),
  max_bookings: z.optional(z.int()).default(1),
  batch_id: z.optional(z.union([z.uuid(), z.null()])),
})

/**
 * DutySlotRead
 */
export const zDutySlotRead = z.object({
  event_id: z.uuid(),
  title: z.string(),
  description: z.optional(z.union([z.string(), z.null()])),
  date: z.iso.date(),
  start_time: z.optional(z.union([z.iso.time(), z.null()])),
  end_time: z.optional(z.union([z.iso.time(), z.null()])),
  location: z.optional(z.union([z.string(), z.null()])),
  category: z.optional(z.union([z.string(), z.null()])),
  max_bookings: z.optional(z.int()).default(1),
  batch_id: z.optional(z.union([z.uuid(), z.null()])),
  id: z.uuid(),
  created_at: z.iso.datetime(),
  updated_at: z.iso.datetime(),
  current_bookings: z.optional(z.int()).default(0),
  is_booked_by_me: z.optional(z.boolean()).default(false),
})

/**
 * DutySlotListResponse
 */
export const zDutySlotListResponse = z.object({
  items: z.array(zDutySlotRead),
  total: z.int(),
  skip: z.int(),
  limit: z.int(),
})

/**
 * DutySlotUpdate
 */
export const zDutySlotUpdate = z.object({
  title: z.optional(z.union([z.string(), z.null()])),
  description: z.optional(z.union([z.string(), z.null()])),
  date: z.optional(z.union([z.iso.date(), z.null()])),
  start_time: z.optional(z.union([z.iso.time(), z.null()])),
  end_time: z.optional(z.union([z.iso.time(), z.null()])),
  location: z.optional(z.union([z.string(), z.null()])),
  category: z.optional(z.union([z.string(), z.null()])),
  max_bookings: z.optional(z.union([z.int(), z.null()])),
})

/**
 * EventBookingEntry
 * A confirmed booking with slot_id, for the bulk event bookings endpoint.
 */
export const zEventBookingEntry = z
  .object({
    id: z.uuid(),
    duty_slot_id: z.uuid(),
    user_name: z.optional(z.union([z.string(), z.null()])),
    user_phone_number: z.optional(z.union([z.string(), z.null()])),
  })
  .register(z.globalRegistry, {
    description: 'A confirmed booking with slot_id, for the bulk event bookings endpoint.',
  })

/**
 * EventCreate
 */
export const zEventCreate = z.object({
  name: z.string(),
  description: z.optional(z.union([z.string(), z.null()])),
  start_date: z.iso.date(),
  end_date: z.iso.date(),
  status: z.optional(z.enum(['draft', 'published', 'archived'])),
  created_by_id: z.optional(z.union([z.uuid(), z.null()])),
  event_group_id: z.optional(z.union([z.uuid(), z.null()])),
  location: z.optional(z.union([z.string(), z.null()])),
  category: z.optional(z.union([z.string(), z.null()])),
})

/**
 * EventGroupCreate
 */
export const zEventGroupCreate = z.object({
  name: z.string(),
  description: z.optional(z.union([z.string(), z.null()])),
  start_date: z.iso.date(),
  end_date: z.iso.date(),
  status: z.optional(z.enum(['draft', 'published', 'archived'])),
  created_by_id: z.optional(z.union([z.uuid(), z.null()])),
})

/**
 * EventCreateWithSlots
 */
export const zEventCreateWithSlots = z.object({
  name: z.string(),
  description: z.optional(z.union([z.string(), z.null()])),
  start_date: z.iso.date(),
  end_date: z.iso.date(),
  location: z.optional(z.union([z.string(), z.null()])),
  category: z.optional(z.union([z.string(), z.null()])),
  event_group_id: z.optional(z.union([z.uuid(), z.null()])),
  new_event_group: z.optional(z.union([zEventGroupCreate, z.null()])),
  schedule: zSlotGenerationConfig,
})

/**
 * EventGroupRead
 */
export const zEventGroupRead = z.object({
  name: z.string(),
  description: z.optional(z.union([z.string(), z.null()])),
  start_date: z.iso.date(),
  end_date: z.iso.date(),
  status: z.optional(z.enum(['draft', 'published', 'archived'])),
  id: z.uuid(),
  created_by_id: z.optional(z.union([z.uuid(), z.null()])),
  created_at: z.iso.datetime(),
  updated_at: z.iso.datetime(),
})

/**
 * EventCreateWithSlotsResponse
 */
export const zEventCreateWithSlotsResponse = z.object({
  event: zEventRead,
  duty_slots_created: z.int(),
  event_group: z.optional(z.union([zEventGroupRead, z.null()])),
})

/**
 * FeedSlotEntry
 * Lightweight slot for the feed — no title/description, just booking info.
 */
export const zFeedSlotEntry = z
  .object({
    id: z.uuid(),
    date: z.iso.date(),
    start_time: z.optional(z.union([z.iso.time(), z.null()])),
    end_time: z.optional(z.union([z.iso.time(), z.null()])),
    max_bookings: z.optional(z.int()).default(1),
    current_bookings: z.optional(z.int()).default(0),
    is_booked_by_me: z.optional(z.boolean()).default(false),
  })
  .register(z.globalRegistry, {
    description: 'Lightweight slot for the feed — no title/description, just booking info.',
  })

/**
 * FeedEventItem
 * Event with view-dependent embedded data.
 */
export const zFeedEventItem = z
  .object({
    name: z.string(),
    description: z.optional(z.union([z.string(), z.null()])),
    start_date: z.iso.date(),
    end_date: z.iso.date(),
    status: z.optional(z.enum(['draft', 'published', 'archived'])),
    created_by_id: z.optional(z.union([z.uuid(), z.null()])),
    event_group_id: z.optional(z.union([z.uuid(), z.null()])),
    location: z.optional(z.union([z.string(), z.null()])),
    category: z.optional(z.union([z.string(), z.null()])),
    id: z.uuid(),
    created_at: z.iso.datetime(),
    updated_at: z.iso.datetime(),
    slot_duration_minutes: z.optional(z.union([z.int(), z.null()])),
    default_start_time: z.optional(z.union([z.iso.time(), z.null()])),
    default_end_time: z.optional(z.union([z.iso.time(), z.null()])),
    people_per_slot: z.optional(z.union([z.int(), z.null()])),
    schedule_overrides: z.optional(z.union([z.array(z.object({})), z.null()])),
    slots: z.optional(z.union([z.array(zFeedSlotEntry), z.null()])),
    slot_window_start: z.optional(z.union([z.iso.date(), z.null()])),
    total_slots: z.optional(z.union([z.int(), z.null()])),
    available_slots: z.optional(z.union([z.int(), z.null()])),
  })
  .register(z.globalRegistry, {
    description: 'Event with view-dependent embedded data.',
  })

/**
 * EventFeedResponse
 */
export const zEventFeedResponse = z.object({
  items: z.array(zFeedEventItem),
  total: z.int(),
  skip: z.int(),
  limit: z.int(),
})

/**
 * EventFillRate
 */
export const zEventFillRate = z.object({
  event_id: z.uuid(),
  event_name: z.string(),
  total_capacity: z.int(),
  confirmed_bookings: z.int(),
  fill_rate: z.number(),
})

/**
 * EventGroupListResponse
 */
export const zEventGroupListResponse = z.object({
  items: z.array(zEventGroupRead),
  total: z.int(),
  skip: z.int(),
  limit: z.int(),
})

/**
 * EventGroupUpdate
 */
export const zEventGroupUpdate = z.object({
  name: z.optional(z.union([z.string(), z.null()])),
  description: z.optional(z.union([z.string(), z.null()])),
  start_date: z.optional(z.union([z.iso.date(), z.null()])),
  end_date: z.optional(z.union([z.iso.date(), z.null()])),
  status: z.optional(z.union([z.enum(['draft', 'published', 'archived']), z.null()])),
})

/**
 * EventListResponse
 */
export const zEventListResponse = z.object({
  items: z.array(zEventRead),
  total: z.int(),
  skip: z.int(),
  limit: z.int(),
})

/**
 * EventUpdate
 */
export const zEventUpdate = z.object({
  name: z.optional(z.union([z.string(), z.null()])),
  description: z.optional(z.union([z.string(), z.null()])),
  start_date: z.optional(z.union([z.iso.date(), z.null()])),
  end_date: z.optional(z.union([z.iso.date(), z.null()])),
  status: z.optional(z.union([z.enum(['draft', 'published', 'archived']), z.null()])),
  event_group_id: z.optional(z.union([z.uuid(), z.null()])),
  location: z.optional(z.union([z.string(), z.null()])),
  category: z.optional(z.union([z.string(), z.null()])),
})

/**
 * EventUpdateWithSlots
 */
export const zEventUpdateWithSlots = z.object({
  name: z.optional(z.union([z.string(), z.null()])),
  description: z.optional(z.union([z.string(), z.null()])),
  start_date: z.optional(z.union([z.iso.date(), z.null()])),
  end_date: z.optional(z.union([z.iso.date(), z.null()])),
  location: z.optional(z.union([z.string(), z.null()])),
  category: z.optional(z.union([z.string(), z.null()])),
  schedule: zSlotGenerationConfig,
})

/**
 * GlobalChannelSettingsRead
 */
export const zGlobalChannelSettingsRead = z.object({
  notify_email: z.boolean(),
  notify_push: z.boolean(),
  notify_telegram: z.boolean(),
})

/**
 * GlobalChannelSettingsUpdate
 */
export const zGlobalChannelSettingsUpdate = z.object({
  notify_email: z.optional(z.union([z.boolean(), z.null()])),
  notify_push: z.optional(z.union([z.boolean(), z.null()])),
  notify_telegram: z.optional(z.union([z.boolean(), z.null()])),
})

/**
 * MyBookingsListResponse
 */
export const zMyBookingsListResponse = z.object({
  items: z.array(zBookingReadWithSlot),
  total: z.int(),
  skip: z.int(),
  limit: z.int(),
})

/**
 * NotificationRead
 */
export const zNotificationRead = z.object({
  id: z.uuid(),
  recipient_id: z.uuid(),
  notification_type_code: z.string(),
  title: z.string(),
  body: z.string(),
  data: z.optional(z.union([z.object({}), z.null()])),
  is_read: z.boolean(),
  read_at: z.optional(z.union([z.iso.datetime(), z.null()])),
  channels_sent: z.array(z.string()),
  channels_failed: z.array(z.string()),
  created_at: z.iso.datetime(),
})

/**
 * NotificationListResponse
 */
export const zNotificationListResponse = z.object({
  items: z.array(zNotificationRead),
  total: z.int(),
  unread_count: z.int(),
  skip: z.int(),
  limit: z.int(),
})

/**
 * NotificationSubscriptionCreate
 */
export const zNotificationSubscriptionCreate = z.object({
  notification_type_id: z.uuid(),
  email_enabled: z.optional(z.boolean()).default(true),
  push_enabled: z.optional(z.boolean()).default(true),
  telegram_enabled: z.optional(z.boolean()).default(false),
  scope_type: z.optional(z.enum(['global', 'event_group', 'event', 'duty_slot'])),
  scope_id: z.optional(z.union([z.uuid(), z.null()])),
  is_muted: z.optional(z.boolean()).default(false),
})

/**
 * NotificationPreferencesBulkUpdate
 * Full matrix of preferences sent from the frontend.
 */
export const zNotificationPreferencesBulkUpdate = z
  .object({
    preferences: z.array(zNotificationSubscriptionCreate),
  })
  .register(z.globalRegistry, {
    description: 'Full matrix of preferences sent from the frontend.',
  })

/**
 * NotificationSubscriptionRead
 */
export const zNotificationSubscriptionRead = z.object({
  id: z.uuid(),
  user_id: z.uuid(),
  notification_type_id: z.uuid(),
  email_enabled: z.boolean(),
  push_enabled: z.boolean(),
  telegram_enabled: z.boolean(),
  scope_type: z.string(),
  scope_id: z.optional(z.union([z.uuid(), z.null()])),
  is_muted: z.boolean(),
  created_at: z.iso.datetime(),
  updated_at: z.iso.datetime(),
})

/**
 * NotificationSubscriptionUpdate
 */
export const zNotificationSubscriptionUpdate = z.object({
  email_enabled: z.optional(z.union([z.boolean(), z.null()])),
  push_enabled: z.optional(z.union([z.boolean(), z.null()])),
  telegram_enabled: z.optional(z.union([z.boolean(), z.null()])),
  is_muted: z.optional(z.union([z.boolean(), z.null()])),
})

/**
 * NotificationTypeRead
 */
export const zNotificationTypeRead = z.object({
  id: z.uuid(),
  code: z.string(),
  name: z.string(),
  description: z.optional(z.union([z.string(), z.null()])),
  category: z.string(),
  is_admin_only: z.boolean(),
  default_channels: z.array(z.string()),
  is_active: z.boolean(),
  is_user_configurable: z.boolean(),
})

/**
 * ProfileInit
 * Profile data from Auth0 ID token for user initialization.
 */
export const zProfileInit = z
  .object({
    email: z.optional(z.union([z.email(), z.null()])),
    name: z.optional(z.union([z.string(), z.null()])),
    nickname: z.optional(z.union([z.string(), z.null()])),
    picture: z.optional(z.union([z.string(), z.null()])),
    email_verified: z.optional(z.union([z.boolean(), z.null()])),
    preferred_language: z.optional(z.union([z.string(), z.null()])),
  })
  .register(z.globalRegistry, {
    description: 'Profile data from Auth0 ID token for user initialization.',
  })

/**
 * PushSubscriptionCreate
 */
export const zPushSubscriptionCreate = z.object({
  endpoint: z.string(),
  p256dh_key: z.string(),
  auth_key: z.string(),
  user_agent: z.optional(z.union([z.string(), z.null()])),
})

/**
 * PushSubscriptionRead
 */
export const zPushSubscriptionRead = z.object({
  id: z.uuid(),
  endpoint: z.string(),
  user_agent: z.optional(z.union([z.string(), z.null()])),
  created_at: z.iso.datetime(),
})

/**
 * ReportingOverviewStats
 */
export const zReportingOverviewStats = z.object({
  total_bookings: z.int(),
  confirmed_bookings: z.int(),
  cancelled_bookings: z.int(),
  cancellation_rate: z.number(),
  total_events: z.int(),
  total_slots: z.int(),
  total_slot_capacity: z.int(),
  filled_slots: z.int(),
  fill_rate: z.number(),
  active_volunteers: z.int(),
  total_volunteers: z.int(),
})

/**
 * TopVolunteer
 */
export const zTopVolunteer = z.object({
  user_id: z.uuid(),
  name: z.union([z.string(), z.null()]),
  email: z.union([z.string(), z.null()]),
  booking_count: z.int(),
})

/**
 * ReportingResponse
 */
export const zReportingResponse = z.object({
  overview: zReportingOverviewStats,
  bookings_trend: z.array(zBookingsTrendPoint),
  top_volunteers: z.array(zTopVolunteer),
  category_breakdown: z.array(zCategoryBreakdown),
  bookings_by_hour: z.array(zBookingsByHour),
  event_fill_rates: z.array(zEventFillRate),
})

/**
 * SelfApproveRequest
 */
export const zSelfApproveRequest = z.object({
  password: z.string().register(z.globalRegistry, {
    description: 'The approval password to verify',
  }),
})

/**
 * SidebarBooking
 */
export const zSidebarBooking = z.object({
  id: z.uuid(),
  slot_id: z.uuid(),
  event_id: z.uuid(),
  slot_title: z.string(),
  slot_date: z.iso.date(),
  slot_start_time: z.optional(z.union([z.iso.time(), z.null()])),
})

/**
 * SidebarEvent
 */
export const zSidebarEvent = z.object({
  id: z.uuid(),
  name: z.string(),
  open_slots: z.int(),
  next_slot_date: z.optional(z.union([z.iso.date(), z.null()])),
  next_slot_start_time: z.optional(z.union([z.iso.time(), z.null()])),
})

/**
 * SidebarEventGroup
 */
export const zSidebarEventGroup = z.object({
  id: z.uuid(),
  name: z.string(),
})

/**
 * SidebarResponse
 */
export const zSidebarResponse = z.object({
  event_groups: z.array(zSidebarEventGroup),
  events: z.array(zSidebarEvent),
  bookings: z.array(zSidebarBooking),
})

/**
 * SiteSettingsRead
 */
export const zSiteSettingsRead = z.object({
  has_approval_password: z
    .optional(
      z.boolean().register(z.globalRegistry, {
        description: 'Whether an approval password is currently configured',
      }),
    )
    .default(false),
})

/**
 * SiteSettingsUpdate
 */
export const zSiteSettingsUpdate = z.object({
  approval_password: z.optional(z.union([z.string(), z.null()])),
})

/**
 * SlotBatchRead
 */
export const zSlotBatchRead = z.object({
  event_id: z.uuid(),
  label: z.optional(z.union([z.string(), z.null()])),
  start_date: z.iso.date(),
  end_date: z.iso.date(),
  location: z.optional(z.union([z.string(), z.null()])),
  category: z.optional(z.union([z.string(), z.null()])),
  default_start_time: z.optional(z.union([z.iso.time(), z.null()])),
  default_end_time: z.optional(z.union([z.iso.time(), z.null()])),
  slot_duration_minutes: z.optional(z.union([z.int(), z.null()])),
  people_per_slot: z.optional(z.union([z.int(), z.null()])),
  remainder_mode: z.optional(z.union([z.enum(['drop', 'short', 'extend']), z.null()])),
  schedule_overrides: z.optional(z.union([z.array(z.object({})), z.null()])),
  id: z.uuid(),
  created_at: z.iso.datetime(),
  updated_at: z.iso.datetime(),
})

/**
 * SlotBookingEntry
 * A confirmed booking for a slot, with basic user info.
 */
export const zSlotBookingEntry = z
  .object({
    id: z.uuid(),
    user_id: z.uuid(),
    user_name: z.optional(z.union([z.string(), z.null()])),
    user_email: z.optional(z.union([z.string(), z.null()])),
    user_picture: z.optional(z.union([z.string(), z.null()])),
    user_phone_number: z.optional(z.union([z.string(), z.null()])),
    notes: z.optional(z.union([z.string(), z.null()])),
    created_at: z.iso.datetime(),
  })
  .register(z.globalRegistry, {
    description: 'A confirmed booking for a slot, with basic user info.',
  })

/**
 * SlotRegenerationResult
 */
export const zSlotRegenerationResult = z.object({
  event: zEventRead,
  slots_added: z.int(),
  slots_removed: z.int(),
  slots_kept: z.int(),
  affected_bookings: z.array(zAffectedBookingInfo),
})

/**
 * SlotWindowResponse
 * Response for the slot-window endpoint (next/prev day navigation).
 */
export const zSlotWindowResponse = z
  .object({
    slots: z.array(zFeedSlotEntry),
    start_date: z.iso.date(),
    days: z.int(),
  })
  .register(z.globalRegistry, {
    description: 'Response for the slot-window endpoint (next/prev day navigation).',
  })

/**
 * TelegramBindResponse
 */
export const zTelegramBindResponse = z.object({
  verification_code: z.string(),
  bot_username: z.optional(z.union([z.string(), z.null()])),
  expires_at: z.iso.datetime(),
})

/**
 * TelegramBindingRead
 */
export const zTelegramBindingRead = z.object({
  id: z.uuid(),
  telegram_chat_id: z.optional(z.union([z.string(), z.null()])),
  telegram_username: z.optional(z.union([z.string(), z.null()])),
  is_verified: z.boolean(),
  created_at: z.iso.datetime(),
})

/**
 * TelegramChat
 */
export const zTelegramChat = z.object({
  id: z.int(),
  username: z.optional(z.union([z.string(), z.null()])),
})

/**
 * TelegramConfigResponse
 */
export const zTelegramConfigResponse = z.object({
  bot_username: z.optional(z.union([z.string(), z.null()])),
  is_configured: z.boolean(),
})

/**
 * TelegramLoginData
 * Auth data returned by the Telegram Login Widget.
 */
export const zTelegramLoginData = z
  .object({
    id: z.int(),
    first_name: z.optional(z.union([z.string(), z.null()])),
    last_name: z.optional(z.union([z.string(), z.null()])),
    username: z.optional(z.union([z.string(), z.null()])),
    photo_url: z.optional(z.union([z.string(), z.null()])),
    auth_date: z.int(),
    hash: z.string(),
  })
  .register(z.globalRegistry, {
    description: 'Auth data returned by the Telegram Login Widget.',
  })

/**
 * TelegramMessage
 */
export const zTelegramMessage = z.object({
  text: z.optional(z.union([z.string(), z.null()])),
  chat: z.optional(z.union([zTelegramChat, z.null()])),
})

/**
 * TelegramVerifyRequest
 */
export const zTelegramVerifyRequest = z.object({
  verification_code: z.string(),
  telegram_chat_id: z.string(),
  telegram_username: z.optional(z.union([z.string(), z.null()])),
})

/**
 * TelegramWebhookUpdate
 * Subset of the Telegram Bot API Update object we actually use.
 */
export const zTelegramWebhookUpdate = z
  .object({
    message: z.optional(z.union([zTelegramMessage, z.null()])),
  })
  .register(z.globalRegistry, {
    description: 'Subset of the Telegram Bot API Update object we actually use.',
  })

/**
 * TestUserSeed
 */
export const zTestUserSeed = z.object({
  email: z.email(),
  name: z.string(),
  roles: z.optional(z.array(z.string())).default([]),
  is_active: z.optional(z.boolean()).default(true),
  preferred_language: z.optional(z.string()).default('en'),
})

/**
 * UnreadCountResponse
 */
export const zUnreadCountResponse = z.object({
  unread_count: z.int(),
})

/**
 * UserAvailabilityDateInput
 */
export const zUserAvailabilityDateInput = z.object({
  date: z.iso.date(),
  start_time: z.optional(z.union([z.iso.time(), z.null()])),
  end_time: z.optional(z.union([z.iso.time(), z.null()])),
})

/**
 * UserAvailabilityCreate
 */
export const zUserAvailabilityCreate = z.object({
  availability_type: z.enum(['fully_available', 'specific_dates', 'time_range']),
  notes: z.optional(z.union([z.string(), z.null()])),
  default_start_time: z.optional(z.union([z.iso.time(), z.null()])),
  default_end_time: z.optional(z.union([z.iso.time(), z.null()])),
  dates: z.optional(z.array(z.union([z.iso.date(), zUserAvailabilityDateInput]))).default([]),
})

/**
 * UserAvailabilityDateRead
 */
export const zUserAvailabilityDateRead = z.object({
  id: z.uuid(),
  slot_date: z.iso.date(),
  start_time: z.optional(z.union([z.iso.time(), z.null()])),
  end_time: z.optional(z.union([z.iso.time(), z.null()])),
})

/**
 * UserAvailabilityRead
 */
export const zUserAvailabilityRead = z.object({
  availability_type: z.enum(['fully_available', 'specific_dates', 'time_range']),
  notes: z.optional(z.union([z.string(), z.null()])),
  default_start_time: z.optional(z.union([z.iso.time(), z.null()])),
  default_end_time: z.optional(z.union([z.iso.time(), z.null()])),
  id: z.uuid(),
  user_id: z.uuid(),
  event_group_id: z.uuid(),
  available_dates: z.optional(z.array(zUserAvailabilityDateRead)).default([]),
  created_at: z.iso.datetime(),
  updated_at: z.iso.datetime(),
})

/**
 * UserAvailabilityWithUser
 * Extended read schema for admin view — includes basic user info.
 */
export const zUserAvailabilityWithUser = z
  .object({
    availability_type: z.enum(['fully_available', 'specific_dates', 'time_range']),
    notes: z.optional(z.union([z.string(), z.null()])),
    default_start_time: z.optional(z.union([z.iso.time(), z.null()])),
    default_end_time: z.optional(z.union([z.iso.time(), z.null()])),
    id: z.uuid(),
    user_id: z.uuid(),
    event_group_id: z.uuid(),
    available_dates: z.optional(z.array(zUserAvailabilityDateRead)).default([]),
    created_at: z.iso.datetime(),
    updated_at: z.iso.datetime(),
    user_full_name: z.optional(z.union([z.string(), z.null()])),
    user_email: z.optional(z.union([z.string(), z.null()])),
  })
  .register(z.globalRegistry, {
    description: 'Extended read schema for admin view — includes basic user info.',
  })

/**
 * UserCreate
 */
export const zUserCreate = z.object({
  auth0_sub: z.string().register(z.globalRegistry, {
    description: 'Auth0 subject identifier',
  }),
  email: z.optional(z.union([z.email(), z.null()])),
  name: z.optional(z.union([z.string(), z.null()])),
  picture: z.optional(z.union([z.string(), z.null()])),
  email_verified: z
    .optional(
      z.boolean().register(z.globalRegistry, {
        description: "Whether the user's email is verified",
      }),
    )
    .default(false),
  roles: z.optional(
    z.array(z.string()).register(z.globalRegistry, {
      description: 'List of role identifiers',
    }),
  ),
  is_active: z
    .optional(
      z.boolean().register(z.globalRegistry, {
        description: 'Whether the user is active',
      }),
    )
    .default(true),
  preferred_language: z
    .optional(
      z.string().register(z.globalRegistry, {
        description: 'Preferred language',
      }),
    )
    .default('en'),
})

/**
 * UserProfile
 */
export const zUserProfile = z.object({
  sub: z.string(),
  name: z.optional(z.union([z.string(), z.null()])),
  nickname: z.optional(z.union([z.string(), z.null()])),
  email: z.optional(z.union([z.string(), z.null()])),
  picture: z.optional(z.union([z.string(), z.null()])),
  bio: z.optional(z.union([z.string(), z.null()])),
  phone_number: z.optional(z.union([z.string(), z.null()])),
  preferred_language: z.optional(z.string()).default('en'),
  email_verified: z.optional(z.boolean()).default(false),
  roles: z.optional(
    z.array(z.string()).register(z.globalRegistry, {
      description: "User's roles",
    }),
  ),
  is_admin: z
    .optional(
      z.boolean().register(z.globalRegistry, {
        description: 'Whether user has admin role',
      }),
    )
    .default(false),
  is_active: z
    .optional(
      z.boolean().register(z.globalRegistry, {
        description: 'Whether user is active',
      }),
    )
    .default(true),
  rejection_reason: z.optional(z.union([z.string(), z.null()])),
})

/**
 * UserProfileUpdate
 */
export const zUserProfileUpdate = z.object({
  name: z.optional(z.union([z.string().max(100), z.null()])),
  nickname: z.optional(z.union([z.string().max(50), z.null()])),
  picture: z.optional(z.union([z.url().min(1).max(2083), z.null()])),
  bio: z.optional(z.union([z.string().max(500), z.null()])),
  phone_number: z.optional(z.union([z.string().max(30), z.null()])),
  preferred_language: z.optional(z.union([z.string().regex(/^(en|de)$/), z.null()])),
})

/**
 * UserRead
 */
export const zUserRead = z.object({
  id: z.uuid(),
  auth0_sub: z.string(),
  email: z.optional(z.union([z.email(), z.null()])),
  name: z.optional(z.union([z.string(), z.null()])),
  picture: z.optional(z.union([z.string(), z.null()])),
  phone_number: z.optional(z.union([z.string(), z.null()])),
  preferred_language: z.optional(z.string()).default('en'),
  roles: z.array(z.string()),
  is_active: z.boolean(),
  rejection_reason: z.optional(z.union([z.string(), z.null()])),
  created_at: z.iso.datetime(),
  updated_at: z.iso.datetime(),
})

/**
 * UserUpdate
 */
export const zUserUpdate = z.object({
  email: z.optional(z.union([z.email(), z.null()])),
  name: z.optional(z.union([z.string(), z.null()])),
  roles: z.optional(z.union([z.array(z.string()), z.null()])),
  is_active: z.optional(z.union([z.boolean(), z.null()])),
  rejection_reason: z.optional(z.union([z.string(), z.null()])),
  preferred_language: z.optional(z.union([z.string(), z.null()])),
})

export const zValidationErrorItem = z.object({
  loc: z.array(z.union([z.string(), z.int()])),
  msg: z.string(),
  type: z.string(),
})

export const zProblemDetails = z.object({
  type: z.url().default('about:blank'),
  code: z.optional(z.string()),
  title: z.string(),
  status: z.int(),
  detail: z.optional(z.string()),
  instance: z.optional(z.string()),
  errors: z.optional(z.array(zValidationErrorItem)),
})

export const zHealthHealthCheckData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

export const zHealthReadinessCheckData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

export const zUsersDeleteCurrentUserData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zUsersDeleteCurrentUserResponse = z.void().register(z.globalRegistry, {
  description: 'Successful Response',
})

export const zUsersUpdateUserProfileData = z.object({
  body: zUserProfileUpdate,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zUsersUpdateUserProfileResponse = zUserProfile

export const zUsersGetCurrentUserProfileData = z.object({
  body: z.optional(z.union([zProfileInit, z.null()])),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zUsersGetCurrentUserProfileResponse = zUserProfile

export const zUsersGetApprovalPasswordStatusData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Response Users-Get Approval Password Status
 * Successful Response
 */
export const zUsersGetApprovalPasswordStatusResponse = z.object({}).register(z.globalRegistry, {
  description: 'Successful Response',
})

export const zUsersSelfApproveData = z.object({
  body: zSelfApproveRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zUsersSelfApproveResponse = zUserProfile

export const zUsersGetAuth0ManagementUrlData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Response Users-Get Auth0 Management Url
 * Successful Response
 */
export const zUsersGetAuth0ManagementUrlResponse = z.object({}).register(z.globalRegistry, {
  description: 'Successful Response',
})

export const zUsersListUsersData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      skip: z.optional(z.int()).default(0),
      limit: z.optional(z.int()).default(100),
    }),
  ),
})

/**
 * Response Users-List Users
 * Successful Response
 */
export const zUsersListUsersResponse = z.array(zUserRead).register(z.globalRegistry, {
  description: 'Successful Response',
})

export const zUsersCreateUserData = z.object({
  body: zUserCreate,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zUsersCreateUserResponse = zUserRead

export const zUsersDeleteUserData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    user_id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zUsersDeleteUserResponse = zUserRead

export const zUsersGetUserData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    user_id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zUsersGetUserResponse = zUserRead

export const zUsersUpdateUserData = z.object({
  body: zUserUpdate,
  path: z.object({
    user_id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zUsersUpdateUserResponse = zUserRead

export const zUsersExportUserDataData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Response Users-Export User Data
 * Successful Response
 */
export const zUsersExportUserDataResponse = z.object({}).register(z.globalRegistry, {
  description: 'Successful Response',
})

export const zSettingsGetSiteSettingsData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zSettingsGetSiteSettingsResponse = zSiteSettingsRead

export const zSettingsUpdateSiteSettingsData = z.object({
  body: zSiteSettingsUpdate,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zSettingsUpdateSiteSettingsResponse = zSiteSettingsRead

export const zEventsEventFeedData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      view: z.optional(z.enum(['list', 'cards', 'calendar'])),
      focus_mode: z.optional(z.enum(['today', 'first_available'])),
      search: z.optional(z.union([z.string(), z.null()])),
      skip: z.optional(z.int().gte(0)).default(0),
      limit: z.optional(z.int().gte(1).lte(200)).default(100),
      date_from: z.optional(z.union([z.iso.date(), z.null()])),
      date_to: z.optional(z.union([z.iso.date(), z.null()])),
      my_bookings: z.optional(z.boolean()).default(false),
      days: z.optional(z.int().gte(1).lte(31)).default(5),
    }),
  ),
})

/**
 * Successful Response
 */
export const zEventsEventFeedResponse = zEventFeedResponse

export const zEventsEventActiveDatesData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.object({
    date_from: z.iso.date(),
    date_to: z.iso.date(),
  }),
})

/**
 * Response Events-Event Active Dates
 * Successful Response
 */
export const zEventsEventActiveDatesResponse = z.array(z.iso.date()).register(z.globalRegistry, {
  description: 'Successful Response',
})

export const zEventsGetSlotWindowData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    event_id: z.string(),
  }),
  query: z.object({
    start_date: z.iso.date(),
    days: z.optional(z.int().gte(1).lte(31)).default(5),
  }),
})

/**
 * Successful Response
 */
export const zEventsGetSlotWindowResponse = zSlotWindowResponse

export const zEventsListEventsData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      skip: z.optional(z.int().gte(0)).default(0),
      limit: z.optional(z.int().gte(1).lte(200)).default(100),
      search: z.optional(z.union([z.string(), z.null()])),
      status: z.optional(z.union([z.enum(['draft', 'published', 'archived']), z.null()])),
      my_bookings: z.optional(z.boolean()).default(false),
    }),
  ),
})

/**
 * Successful Response
 */
export const zEventsListEventsResponse = zEventListResponse

export const zEventsCreateEventData = z.object({
  body: zEventCreate,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zEventsCreateEventResponse = zEventRead

export const zEventsDeleteEventData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    event_id: z.string(),
  }),
  query: z.optional(
    z.object({
      cancellation_reason: z.optional(z.union([z.string(), z.null()])),
    }),
  ),
})

/**
 * Successful Response
 */
export const zEventsDeleteEventResponse = z.void().register(z.globalRegistry, {
  description: 'Successful Response',
})

export const zEventsGetEventData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    event_id: z.string(),
  }),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zEventsGetEventResponse = zEventRead

export const zEventsUpdateEventData = z.object({
  body: zEventUpdate,
  path: z.object({
    event_id: z.string(),
  }),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zEventsUpdateEventResponse = zEventRead

export const zEventsListEventBookingsData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    event_id: z.string(),
  }),
  query: z.optional(z.never()),
})

/**
 * Response Events-List Event Bookings
 * Successful Response
 */
export const zEventsListEventBookingsResponse = z
  .array(zEventBookingEntry)
  .register(z.globalRegistry, {
    description: 'Successful Response',
  })

export const zEventsCreateEventWithSlotsData = z.object({
  body: zEventCreateWithSlots,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zEventsCreateEventWithSlotsResponse = zEventCreateWithSlotsResponse

export const zEventsAddSlotsToEventData = z.object({
  body: zAddSlotsToEvent,
  path: z.object({
    event_id: z.string(),
  }),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zEventsAddSlotsToEventResponse = zAddSlotsResponse

export const zEventsRegenerateEventSlotsData = z.object({
  body: zEventUpdateWithSlots,
  path: z.object({
    event_id: z.string(),
  }),
  query: z.optional(
    z.object({
      dry_run: z.optional(z.boolean()).default(false),
      batch_id: z.optional(z.union([z.string(), z.null()])),
    }),
  ),
})

/**
 * Successful Response
 */
export const zEventsRegenerateEventSlotsResponse = zSlotRegenerationResult

export const zEventsListBatchesData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    event_id: z.string(),
  }),
  query: z.optional(z.never()),
})

/**
 * Response Events-List Batches
 * Successful Response
 */
export const zEventsListBatchesResponse = z.array(zSlotBatchRead).register(z.globalRegistry, {
  description: 'Successful Response',
})

export const zEventsDeleteBatchData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    event_id: z.string(),
    batch_id: z.string(),
  }),
  query: z.optional(
    z.object({
      cancellation_reason: z.optional(z.union([z.string(), z.null()])),
    }),
  ),
})

/**
 * Successful Response
 */
export const zEventsDeleteBatchResponse = z.void().register(z.globalRegistry, {
  description: 'Successful Response',
})

export const zDutySlotsListDutySlotsData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      event_id: z.optional(z.union([z.string(), z.null()])),
      category: z.optional(z.union([z.string(), z.null()])),
      search: z.optional(z.union([z.string(), z.null()])),
      skip: z.optional(z.int().gte(0)).default(0),
      limit: z.optional(z.int().gte(1).lte(200)).default(100),
    }),
  ),
})

/**
 * Successful Response
 */
export const zDutySlotsListDutySlotsResponse = zDutySlotListResponse

export const zDutySlotsCreateDutySlotData = z.object({
  body: zDutySlotCreate,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zDutySlotsCreateDutySlotResponse = zDutySlotRead

export const zDutySlotsDeleteDutySlotData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    slot_id: z.string(),
  }),
  query: z.optional(
    z.object({
      cancellation_reason: z.optional(z.union([z.string(), z.null()])),
    }),
  ),
})

/**
 * Successful Response
 */
export const zDutySlotsDeleteDutySlotResponse = z.void().register(z.globalRegistry, {
  description: 'Successful Response',
})

export const zDutySlotsGetDutySlotData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    slot_id: z.union([z.string(), z.null()]),
  }),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zDutySlotsGetDutySlotResponse = zDutySlotRead

export const zDutySlotsUpdateDutySlotData = z.object({
  body: zDutySlotUpdate,
  path: z.object({
    slot_id: z.string(),
  }),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zDutySlotsUpdateDutySlotResponse = zDutySlotRead

export const zDutySlotsListSlotBookingsData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    slot_id: z.string(),
  }),
  query: z.optional(z.never()),
})

/**
 * Response Duty-Slots-List Slot Bookings
 * Successful Response
 */
export const zDutySlotsListSlotBookingsResponse = z
  .array(zSlotBookingEntry)
  .register(z.globalRegistry, {
    description: 'Successful Response',
  })

export const zBookingsListMyBookingsData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      skip: z.optional(z.int().gte(0)).default(0),
      limit: z.optional(z.int().gte(1).lte(200)).default(100),
      status: z.optional(z.union([z.string(), z.null()])),
      date_from: z.optional(z.union([z.iso.date(), z.null()])),
      date_to: z.optional(z.union([z.iso.date(), z.null()])),
    }),
  ),
})

/**
 * Successful Response
 */
export const zBookingsListMyBookingsResponse = zMyBookingsListResponse

export const zBookingsMyBookingActiveDatesData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.object({
    date_from: z.iso.date(),
    date_to: z.iso.date(),
  }),
})

/**
 * Response Bookings-My Booking Active Dates
 * Successful Response
 */
export const zBookingsMyBookingActiveDatesResponse = z
  .array(z.iso.date())
  .register(z.globalRegistry, {
    description: 'Successful Response',
  })

export const zBookingsCreateBookingData = z.object({
  body: zBookingCreate,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zBookingsCreateBookingResponse = zBookingRead

export const zBookingsCancelBookingData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    booking_id: z.string(),
  }),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zBookingsCancelBookingResponse = zBookingRead

export const zBookingsGetBookingData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    booking_id: z.string(),
  }),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zBookingsGetBookingResponse = zBookingRead

export const zBookingsUpdateBookingData = z.object({
  body: zBookingUpdate,
  path: z.object({
    booking_id: z.string(),
  }),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zBookingsUpdateBookingResponse = zBookingRead

export const zBookingsDismissBookingData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    booking_id: z.string(),
  }),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zBookingsDismissBookingResponse = z.void().register(z.globalRegistry, {
  description: 'Successful Response',
})

export const zBookingRemindersGetReminderDefaultsData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zBookingRemindersGetReminderDefaultsResponse = zDefaultReminderOffsetsRead

export const zBookingRemindersUpdateReminderDefaultsData = z.object({
  body: zDefaultReminderOffsetsUpdate,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zBookingRemindersUpdateReminderDefaultsResponse = zDefaultReminderOffsetsRead

export const zBookingRemindersListBookingRemindersData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    booking_id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zBookingRemindersListBookingRemindersResponse = zBookingReminderListResponse

export const zBookingRemindersAddBookingReminderData = z.object({
  body: zBookingReminderCreate,
  path: z.object({
    booking_id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zBookingRemindersAddBookingReminderResponse = zBookingReminderRead

export const zBookingRemindersDeleteReminderData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    reminder_id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zBookingRemindersDeleteReminderResponse = z.void().register(z.globalRegistry, {
  description: 'Successful Response',
})

export const zCalendarDisableFeedData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zCalendarDisableFeedResponse = z.void().register(z.globalRegistry, {
  description: 'Successful Response',
})

export const zCalendarGetFeedSettingsData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Response Calendar-Get Feed Settings
 * Successful Response
 */
export const zCalendarGetFeedSettingsResponse = z.union([zCalendarFeedRead, z.null()])

export const zCalendarEnableFeedData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zCalendarEnableFeedResponse = zCalendarFeedRead

export const zCalendarRegenerateFeedData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zCalendarRegenerateFeedResponse = zCalendarFeedRead

export const zEventGroupsListEventGroupsData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      skip: z.optional(z.int().gte(0)).default(0),
      limit: z.optional(z.int().gte(1).lte(200)).default(100),
      search: z.optional(z.union([z.string(), z.null()])),
      status: z.optional(z.union([z.enum(['draft', 'published', 'archived']), z.null()])),
      date_from: z.optional(z.union([z.iso.date(), z.null()])),
      date_to: z.optional(z.union([z.iso.date(), z.null()])),
    }),
  ),
})

/**
 * Successful Response
 */
export const zEventGroupsListEventGroupsResponse = zEventGroupListResponse

export const zEventGroupsCreateEventGroupData = z.object({
  body: zEventGroupCreate,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zEventGroupsCreateEventGroupResponse = zEventGroupRead

export const zEventGroupsDeleteEventGroupData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    group_id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zEventGroupsDeleteEventGroupResponse = z.void().register(z.globalRegistry, {
  description: 'Successful Response',
})

export const zEventGroupsGetEventGroupData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    group_id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zEventGroupsGetEventGroupResponse = zEventGroupRead

export const zEventGroupsUpdateEventGroupData = z.object({
  body: zEventGroupUpdate,
  path: z.object({
    group_id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zEventGroupsUpdateEventGroupResponse = zEventGroupRead

export const zEventGroupsListGroupAvailabilitiesData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    group_id: z.uuid(),
  }),
  query: z.optional(
    z.object({
      skip: z.optional(z.int().gte(0)).default(0),
      limit: z.optional(z.int().gte(1).lte(500)).default(200),
    }),
  ),
})

/**
 * Response Event-Groups-List Group Availabilities
 * Successful Response
 */
export const zEventGroupsListGroupAvailabilitiesResponse = z
  .array(zUserAvailabilityWithUser)
  .register(z.globalRegistry, {
    description: 'Successful Response',
  })

export const zEventGroupsDeleteMyAvailabilityData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    group_id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zEventGroupsDeleteMyAvailabilityResponse = z.void().register(z.globalRegistry, {
  description: 'Successful Response',
})

export const zEventGroupsGetMyAvailabilityData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    group_id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zEventGroupsGetMyAvailabilityResponse = zUserAvailabilityRead

export const zEventGroupsSetMyAvailabilityData = z.object({
  body: zUserAvailabilityCreate,
  path: z.object({
    group_id: z.uuid(),
  }),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zEventGroupsSetMyAvailabilityResponse = zUserAvailabilityRead

export const zNotificationsListNotificationTypesData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Response Notifications-List Notification Types
 * Successful Response
 */
export const zNotificationsListNotificationTypesResponse = z
  .array(zNotificationTypeRead)
  .register(z.globalRegistry, {
    description: 'Successful Response',
  })

export const zNotificationsNotificationStreamData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.object({
    token: z.string().register(z.globalRegistry, {
      description: 'Bearer token for auth',
    }),
  }),
})

export const zNotificationsListNotificationsData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      skip: z.optional(z.int().gte(0)).default(0),
      limit: z.optional(z.int().gte(1).lte(200)).default(50),
      unread_only: z.optional(z.boolean()).default(false),
    }),
  ),
})

/**
 * Successful Response
 */
export const zNotificationsListNotificationsResponse = zNotificationListResponse

export const zNotificationsGetUnreadCountData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zNotificationsGetUnreadCountResponse = zUnreadCountResponse

export const zNotificationsMarkNotificationReadData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    notification_id: z.string(),
  }),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zNotificationsMarkNotificationReadResponse = zNotificationRead

export const zNotificationsMarkAllNotificationsReadData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Response Notifications-Mark All Notifications Read
 * Successful Response
 */
export const zNotificationsMarkAllNotificationsReadResponse = z
  .object({})
  .register(z.globalRegistry, {
    description: 'Successful Response',
  })

export const zNotificationsDismissNotificationData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    notification_id: z.string(),
  }),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zNotificationsDismissNotificationResponse = z.void().register(z.globalRegistry, {
  description: 'Successful Response',
})

export const zNotificationsListPreferencesData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Response Notifications-List Preferences
 * Successful Response
 */
export const zNotificationsListPreferencesResponse = z
  .array(zNotificationSubscriptionRead)
  .register(z.globalRegistry, {
    description: 'Successful Response',
  })

export const zNotificationsCreatePreferenceData = z.object({
  body: zNotificationSubscriptionCreate,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zNotificationsCreatePreferenceResponse = zNotificationSubscriptionRead

export const zNotificationsBulkUpdatePreferencesData = z.object({
  body: zNotificationPreferencesBulkUpdate,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Response Notifications-Bulk Update Preferences
 * Successful Response
 */
export const zNotificationsBulkUpdatePreferencesResponse = z
  .array(zNotificationSubscriptionRead)
  .register(z.globalRegistry, {
    description: 'Successful Response',
  })

export const zNotificationsDeletePreferenceData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    preference_id: z.string(),
  }),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zNotificationsDeletePreferenceResponse = z.void().register(z.globalRegistry, {
  description: 'Successful Response',
})

export const zNotificationsUpdatePreferenceData = z.object({
  body: zNotificationSubscriptionUpdate,
  path: z.object({
    preference_id: z.string(),
  }),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zNotificationsUpdatePreferenceResponse = zNotificationSubscriptionRead

export const zNotificationsGetChannelSettingsData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zNotificationsGetChannelSettingsResponse = zGlobalChannelSettingsRead

export const zNotificationsUpdateChannelSettingsData = z.object({
  body: zGlobalChannelSettingsUpdate,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zNotificationsUpdateChannelSettingsResponse = zGlobalChannelSettingsRead

export const zNotificationsListPushSubscriptionsData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Response Notifications-List Push Subscriptions
 * Successful Response
 */
export const zNotificationsListPushSubscriptionsResponse = z
  .array(zPushSubscriptionRead)
  .register(z.globalRegistry, {
    description: 'Successful Response',
  })

export const zNotificationsRegisterPushSubscriptionData = z.object({
  body: zPushSubscriptionCreate,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zNotificationsRegisterPushSubscriptionResponse = zPushSubscriptionRead

export const zNotificationsRemovePushSubscriptionData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    subscription_id: z.string(),
  }),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zNotificationsRemovePushSubscriptionResponse = z.void().register(z.globalRegistry, {
  description: 'Successful Response',
})

export const zNotificationsGetVapidPublicKeyData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Response Notifications-Get Vapid Public Key
 * Successful Response
 */
export const zNotificationsGetVapidPublicKeyResponse = z.object({}).register(z.globalRegistry, {
  description: 'Successful Response',
})

export const zNotificationsSendTestPushData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Response Notifications-Send Test Push
 * Successful Response
 */
export const zNotificationsSendTestPushResponse = z.object({}).register(z.globalRegistry, {
  description: 'Successful Response',
})

export const zNotificationsGetTelegramConfigData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zNotificationsGetTelegramConfigResponse = zTelegramConfigResponse

export const zNotificationsUnbindTelegramData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zNotificationsUnbindTelegramResponse = z.void().register(z.globalRegistry, {
  description: 'Successful Response',
})

export const zNotificationsGetTelegramBindingData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Response Notifications-Get Telegram Binding
 * Successful Response
 */
export const zNotificationsGetTelegramBindingResponse = z.union([zTelegramBindingRead, z.null()])

export const zNotificationsTelegramLoginData = z.object({
  body: zTelegramLoginData,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zNotificationsTelegramLoginResponse = zTelegramBindingRead

export const zNotificationsStartTelegramBindingData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zNotificationsStartTelegramBindingResponse = zTelegramBindResponse

export const zNotificationsVerifyTelegramBindingData = z.object({
  body: zTelegramVerifyRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zNotificationsVerifyTelegramBindingResponse = zTelegramBindingRead

export const zNotificationsTelegramWebhookData = z.object({
  body: zTelegramWebhookUpdate,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Response Notifications-Telegram Webhook
 * Successful Response
 */
export const zNotificationsTelegramWebhookResponse = z.object({}).register(z.globalRegistry, {
  description: 'Successful Response',
})

export const zDashboardDashboardFeedData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zDashboardDashboardFeedResponse = zDashboardFeedResponse

export const zDashboardDashboardSidebarData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zDashboardDashboardSidebarResponse = zSidebarResponse

export const zReportingReportingOverviewData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      date_from: z.optional(z.union([z.iso.date(), z.null()])),
      date_to: z.optional(z.union([z.iso.date(), z.null()])),
    }),
  ),
})

/**
 * Successful Response
 */
export const zReportingReportingOverviewResponse = zReportingResponse

export const zReportingReportingExportData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      date_from: z.optional(z.union([z.iso.date(), z.null()])),
      date_to: z.optional(z.union([z.iso.date(), z.null()])),
    }),
  ),
})

export const zDemoDataDeleteDemoDataData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zDemoDataDeleteDemoDataResponse = zDemoDataDeletedResponse

export const zDemoDataCreateDemoDataData = z.object({
  body: zDemoDataParams,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zDemoDataCreateDemoDataResponse = zDemoDataCreatedResponse

export const zDebugStartLogCaptureData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Response Debug-Start Log Capture
 * Successful Response
 */
export const zDebugStartLogCaptureResponse = z.object({}).register(z.globalRegistry, {
  description: 'Successful Response',
})

export const zDebugStopLogCaptureData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Response Debug-Stop Log Capture
 * Successful Response
 */
export const zDebugStopLogCaptureResponse = z.object({}).register(z.globalRegistry, {
  description: 'Successful Response',
})

export const zTestingSeedTestUserData = z.object({
  body: zTestUserSeed,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zTestingSeedTestUserResponse = zUserRead

export const zTestingResetTestDataData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Response Testing-Reset Test Data
 * Successful Response
 */
export const zTestingResetTestDataResponse = z.object({}).register(z.globalRegistry, {
  description: 'Successful Response',
})
