// This file is auto-generated by @hey-api/openapi-ts
import * as z from 'zod'

/**
 * AffectedBookingInfo
 */
export const zAffectedBookingInfo = z.object({
  booking_id: z.uuid(),
  user_id: z.uuid(),
  slot_title: z.string(),
  slot_date: z.iso.date(),
  slot_start_time: z.iso.time().nullish(),
  slot_end_time: z.iso.time().nullish(),
})

/**
 * AuthSessionRead
 *
 * One signed-in device, as shown in the Security settings card.
 *
 * Nothing secret is exposed: the refresh token hash stays server-side, and
 * what is left is only enough for the owner to recognise a device they no
 * longer want signed in.
 */
export const zAuthSessionRead = z
  .object({
    id: z.uuid(),
    created_at: z.iso.datetime().register(z.globalRegistry, {
      description: 'When this device signed in',
    }),
    last_used_at: z.iso.datetime().nullish(),
    expires_at: z.iso.datetime().register(z.globalRegistry, {
      description: 'When the session lapses without being used',
    }),
    user_agent: z.string().nullish(),
    ip_address: z.string().nullish(),
    is_current: z
      .boolean()
      .register(z.globalRegistry, {
        description: 'True for the session the current request is authenticated by',
      })
      .optional()
      .default(false),
  })
  .register(z.globalRegistry, {
    description:
      'One signed-in device, as shown in the Security settings card.\n\nNothing secret is exposed: the refresh token hash stays server-side, and\nwhat is left is only enough for the owner to recognise a device they no\nlonger want signed in.',
  })

/**
 * AvatarUploadResponse
 */
export const zAvatarUploadResponse = z.object({
  etag: z.string(),
})

/**
 * Body_users-upload_my_avatar
 */
export const zBodyUsersUploadMyAvatar = z.object({
  file: z.string(),
})

/**
 * BookingCreate
 *
 * User only provides the shift and optional notes. user_id is set server-side.
 */
export const zBookingCreate = z
  .object({
    shift_id: z.uuid(),
    notes: z.string().nullish(),
  })
  .register(z.globalRegistry, {
    description: 'User only provides the shift and optional notes. user_id is set server-side.',
  })

/**
 * BookingRead
 */
export const zBookingRead = z.object({
  shift_id: z.uuid().nullish(),
  user_id: z.uuid(),
  status: z.enum(['confirmed', 'cancelled']).optional().default('confirmed'),
  notes: z.string().nullish(),
  id: z.uuid(),
  created_at: z.iso.datetime(),
  updated_at: z.iso.datetime(),
  cancellation_reason: z.string().nullish(),
  cancelled_shift_title: z.string().nullish(),
  cancelled_shift_date: z.iso.date().nullish(),
  cancelled_shift_start_time: z.iso.time().nullish(),
  cancelled_shift_end_time: z.iso.time().nullish(),
  cancelled_task_name: z.string().nullish(),
})

/**
 * BookingReminderCreate
 *
 * User provides the offset and channels; remind_at is computed server-side.
 */
export const zBookingReminderCreate = z
  .object({
    offset_minutes: z.union([
      z.literal(15),
      z.literal(30),
      z.literal(60),
      z.literal(120),
      z.literal(180),
      z.literal(360),
      z.literal(720),
      z.literal(1440),
      z.literal(2880),
    ]),
    channels: z
      .array(z.enum(['email', 'push', 'telegram']))
      .min(1)
      .optional()
      .default(['push']),
  })
  .register(z.globalRegistry, {
    description: 'User provides the offset and channels; remind_at is computed server-side.',
  })

/**
 * BookingReminderRead
 */
export const zBookingReminderRead = z.object({
  id: z.uuid(),
  booking_id: z.uuid(),
  offset_minutes: z.int(),
  channels: z.array(z.string()),
  remind_at: z.iso.datetime(),
  status: z.enum(['pending', 'sent', 'cancelled', 'expired']),
  created_at: z.iso.datetime(),
})

/**
 * BookingReminderListResponse
 */
export const zBookingReminderListResponse = z.object({
  items: z.array(zBookingReminderRead),
})

/**
 * BookingUpdate
 */
export const zBookingUpdate = z.object({
  status: z.enum(['confirmed', 'cancelled']).nullish(),
  notes: z.string().nullish(),
  cancellation_reason: z.string().nullish(),
})

/**
 * BookingsByHour
 */
export const zBookingsByHour = z.object({
  hour: z.int(),
  booking_count: z.int(),
})

/**
 * BookingsTrendPoint
 */
export const zBookingsTrendPoint = z.object({
  date: z.iso.date(),
  confirmed: z.int(),
  cancelled: z.int(),
})

/**
 * CalendarFeedRead
 *
 * Response for calendar feed management endpoints.
 */
export const zCalendarFeedRead = z
  .object({
    id: z.uuid(),
    feed_url: z.string(),
    is_enabled: z.boolean(),
    last_accessed_at: z.iso.datetime().nullish(),
    created_at: z.iso.datetime(),
  })
  .register(z.globalRegistry, {
    description: 'Response for calendar feed management endpoints.',
  })

/**
 * CategoryBreakdown
 */
export const zCategoryBreakdown = z.object({
  category: z.string().nullable(),
  slot_count: z.int(),
  total_capacity: z.int(),
  confirmed_bookings: z.int(),
  fill_rate: z.number(),
})

/**
 * ChangePasswordRequest
 *
 * Change the password of the signed-in account.
 *
 * The current password is required even though the caller is already
 * authenticated: it is what stops a borrowed, unlocked browser from becoming a
 * permanent takeover.
 */
export const zChangePasswordRequest = z
  .object({
    current_password: z.string().register(z.globalRegistry, {
      description: 'The password in use right now',
    }),
    new_password: z.string().register(z.globalRegistry, {
      description: 'Replacement password',
    }),
  })
  .register(z.globalRegistry, {
    description:
      'Change the password of the signed-in account.\n\nThe current password is required even though the caller is already\nauthenticated: it is what stops a borrowed, unlocked browser from becoming a\npermanent takeover.',
  })

/**
 * DashboardAttention
 *
 * The organiser's to-do list, counted rather than listed.
 *
 * Only populated for someone who administers the event in scope; a plain
 * member gets ``None`` and never sees the block.
 */
export const zDashboardAttention = z
  .object({
    pending_join_requests: z.int().optional().default(0),
    draft_tasks: z.int().optional().default(0),
    empty_shifts_soon: z.int().optional().default(0),
    short_shifts_soon: z.int().optional().default(0),
    horizon_days: z.int().optional().default(7),
  })
  .register(z.globalRegistry, {
    description:
      "The organiser's to-do list, counted rather than listed.\n\nOnly populated for someone who administers the event in scope; a plain\nmember gets ``None`` and never sees the block.",
  })

/**
 * DashboardOpenShift
 *
 * A shift that still has room, offered to the user to pick up.
 */
export const zDashboardOpenShift = z
  .object({
    shift_id: z.uuid(),
    task_id: z.uuid(),
    task_name: z.string(),
    event_id: z.uuid().nullish(),
    event_name: z.string().nullish(),
    title: z.string(),
    date: z.iso.date(),
    start_time: z.iso.time().nullish(),
    end_time: z.iso.time().nullish(),
    location: z.string().nullish(),
    taken: z.int(),
    capacity: z.int(),
    places_left: z.int(),
  })
  .register(z.globalRegistry, {
    description: 'A shift that still has room, offered to the user to pick up.',
  })

/**
 * DashboardShift
 *
 * A shift the signed-in user has already committed to.
 */
export const zDashboardShift = z
  .object({
    booking_id: z.uuid(),
    shift_id: z.uuid(),
    task_id: z.uuid(),
    task_name: z.string(),
    event_id: z.uuid().nullish(),
    event_name: z.string().nullish(),
    title: z.string(),
    date: z.iso.date(),
    start_time: z.iso.time().nullish(),
    end_time: z.iso.time().nullish(),
    location: z.string().nullish(),
    taken: z.int(),
    capacity: z.int(),
  })
  .register(z.globalRegistry, {
    description: 'A shift the signed-in user has already committed to.',
  })

/**
 * DashboardFeedResponse
 *
 * Everything /app/home renders, in one request.
 */
export const zDashboardFeedResponse = z
  .object({
    event_id: z.uuid().nullish(),
    event_name: z.string().nullish(),
    my_shifts: z.array(zDashboardShift),
    my_shift_count: z.int(),
    my_minutes: z.int(),
    open_shifts: z.array(zDashboardOpenShift),
    open_shift_count: z.int(),
    open_places: z.int(),
    attention: zDashboardAttention.nullish(),
    pending_join_request_count: z.int().optional().default(0),
  })
  .register(z.globalRegistry, {
    description: 'Everything /app/home renders, in one request.',
  })

/**
 * DemoDataCreatedResponse
 */
export const zDemoDataCreatedResponse = z.object({
  events_created: z.int(),
  tasks_created: z.int(),
  users_created: z.int(),
  shifts_created: z.int(),
  bookings_created: z.int(),
  availabilities_created: z.int(),
})

/**
 * DemoDataDeletedResponse
 */
export const zDemoDataDeletedResponse = z.object({
  tasks_deleted: z.int(),
  events_deleted: z.int(),
  users_deleted: z.int(),
  shifts_deleted: z.int(),
  bookings_deleted: z.int(),
})

/**
 * DemoDataParams
 */
export const zDemoDataParams = z.object({
  num_tasks: z.int().gte(1).lte(50).optional().default(10),
  num_events: z.int().gte(0).lte(10).optional().default(3),
  num_users: z.int().gte(0).lte(20).optional().default(5),
  num_shifts_per_task: z.int().gte(1).lte(20).optional().default(4),
  publish_tasks: z.boolean().optional().default(true),
})

/**
 * EventCloneAnnounce
 *
 * Whether to tell the new event's members about it, and what to add.
 */
export const zEventCloneAnnounce = z
  .object({
    send: z.boolean().optional().default(false),
    note: z.string().max(500).nullish(),
  })
  .register(z.globalRegistry, {
    description: "Whether to tell the new event's members about it, and what to add.",
  })

/**
 * EventCloneTask
 *
 * One source task to reproduce in the clone, with optional overrides.
 *
 * Every override is optional; omitting one keeps the source value (dates keep
 * the source value *plus the clone's date offset*).
 */
export const zEventCloneTask = z
  .object({
    source_task_id: z.uuid(),
    mode: z.enum(['copy', 'regenerate']).optional().default('copy'),
    name: z.string().nullish(),
    status: z.enum(['draft', 'published', 'archived']).nullish(),
    location: z.string().nullish(),
    category: z.string().nullish(),
    start_date: z.iso.date().nullish(),
    end_date: z.iso.date().nullish(),
    default_start_time: z.iso.time().nullish(),
    default_end_time: z.iso.time().nullish(),
    shift_duration_minutes: z.int().nullish(),
    people_per_shift: z.int().nullish(),
  })
  .register(z.globalRegistry, {
    description:
      "One source task to reproduce in the clone, with optional overrides.\n\nEvery override is optional; omitting one keeps the source value (dates keep\nthe source value *plus the clone's date offset*).",
  })

/**
 * EventCloneRequest
 */
export const zEventCloneRequest = z.object({
  name: z.string(),
  start_date: z.iso.date(),
  end_date: z.iso.date().nullish(),
  description: z.string().nullish(),
  visibility: z.enum(['public', 'private']).optional().default('private'),
  copy_defaults: z.boolean().optional().default(true),
  copy_members: z.boolean().optional().default(false),
  tasks: z.array(zEventCloneTask).max(50).optional().default([]),
  announce: zEventCloneAnnounce.nullish(),
})

/**
 * EventCreate
 */
export const zEventCreate = z.object({
  name: z.string(),
  description: z.string().nullish(),
  start_date: z.iso.date(),
  end_date: z.iso.date(),
  default_start_time: z.iso.time().nullish(),
  default_end_time: z.iso.time().nullish(),
  status: z.enum(['draft', 'published', 'archived']).optional().default('draft'),
  visibility: z.enum(['public', 'private']).optional().default('private'),
  created_by_id: z.uuid().nullish(),
})

/**
 * EventInvitationBulkCreate
 *
 * Invite several addresses in one go, all with the same role.
 */
export const zEventInvitationBulkCreate = z
  .object({
    emails: z.array(z.email()).min(1).max(100),
    role: z.enum(['admin', 'member']).optional().default('member'),
    expires_in_days: z.int().gte(1).lte(365).nullish().default(14),
  })
  .register(z.globalRegistry, {
    description: 'Invite several addresses in one go, all with the same role.',
  })

/**
 * EventInvitationCreate
 *
 * Create either a targeted invite (``email`` set) or a share link.
 */
export const zEventInvitationCreate = z
  .object({
    email: z.email().nullish(),
    role: z.enum(['admin', 'member']).optional().default('member'),
    expires_in_days: z.int().gte(1).lte(365).nullish().default(14),
  })
  .register(z.globalRegistry, {
    description: 'Create either a targeted invite (``email`` set) or a share link.',
  })

/**
 * EventInvitationPreview
 *
 * What an invitee sees before deciding to accept.
 *
 * Deliberately narrow: it is reachable by anyone holding the token, so it
 * exposes the event's identity and nothing about its members or contents.
 */
export const zEventInvitationPreview = z
  .object({
    event_id: z.uuid(),
    event_name: z.string(),
    event_description: z.string().nullish(),
    start_date: z.iso.date(),
    end_date: z.iso.date(),
    role: z.enum(['admin', 'member']),
    invited_by_name: z.string().nullish(),
    is_valid: z.boolean(),
    invalid_reason: z.string().nullish(),
    already_member: z.boolean().optional().default(false),
  })
  .register(z.globalRegistry, {
    description:
      "What an invitee sees before deciding to accept.\n\nDeliberately narrow: it is reachable by anyone holding the token, so it\nexposes the event's identity and nothing about its members or contents.",
  })

/**
 * EventInvitationRead
 */
export const zEventInvitationRead = z.object({
  id: z.uuid(),
  event_id: z.uuid(),
  email: z.string().nullish(),
  role: z.enum(['admin', 'member']),
  token: z.string(),
  invited_by_id: z.uuid().nullish(),
  expires_at: z.iso.datetime().nullish(),
  revoked_at: z.iso.datetime().nullish(),
  accepted_at: z.iso.datetime().nullish(),
  use_count: z.int().optional().default(0),
})

/**
 * EventInvitationBulkResult
 */
export const zEventInvitationBulkResult = z.object({
  created: z.array(zEventInvitationRead),
  skipped_existing_members: z.array(z.string()).optional(),
  skipped_already_invited: z.array(z.string()).optional(),
})

/**
 * EventJoinRequestCreate
 */
export const zEventJoinRequestCreate = z.object({
  message: z.string().max(500).nullish(),
})

/**
 * EventJoinRequestDecision
 */
export const zEventJoinRequestDecision = z.object({
  approve: z.boolean(),
  role: z.enum(['admin', 'member']).optional().default('member'),
})

/**
 * EventJoinRequestRead
 */
export const zEventJoinRequestRead = z.object({
  id: z.uuid(),
  event_id: z.uuid(),
  user_id: z.uuid(),
  status: z.enum(['pending', 'approved', 'declined']),
  message: z.string().nullish(),
  created_at: z.iso.datetime(),
  decided_at: z.iso.datetime().nullish(),
  user_name: z.string().nullish(),
  user_email: z.string().nullish(),
  user_avatar_etag: z.string().nullish(),
})

/**
 * EventMemberRead
 *
 * A membership joined with the display fields of its user.
 */
export const zEventMemberRead = z
  .object({
    user_id: z.uuid(),
    event_id: z.uuid(),
    role: z.enum(['owner', 'admin', 'member']),
    joined_at: z.iso.datetime(),
    name: z.string().nullish(),
    email: z.string().nullish(),
    avatar_etag: z.string().nullish(),
  })
  .register(z.globalRegistry, {
    description: 'A membership joined with the display fields of its user.',
  })

/**
 * EventMemberRoleUpdate
 */
export const zEventMemberRoleUpdate = z.object({
  role: z.enum(['admin', 'member']),
})

/**
 * EventOwnershipTransfer
 *
 * Hand ownership of an event to another member.
 *
 * The outgoing owner is demoted to ``admin`` so they keep working access.
 */
export const zEventOwnershipTransfer = z
  .object({
    new_owner_id: z.uuid(),
  })
  .register(z.globalRegistry, {
    description:
      'Hand ownership of an event to another member.\n\nThe outgoing owner is demoted to ``admin`` so they keep working access.',
  })

/**
 * EventRead
 */
export const zEventRead = z.object({
  name: z.string(),
  description: z.string().nullish(),
  start_date: z.iso.date(),
  end_date: z.iso.date(),
  default_start_time: z.iso.time().nullish(),
  default_end_time: z.iso.time().nullish(),
  status: z.enum(['draft', 'published', 'archived']).optional().default('draft'),
  visibility: z.enum(['public', 'private']).optional().default('private'),
  id: z.uuid(),
  created_by_id: z.uuid().nullish(),
  is_featured: z.boolean().optional().default(false),
  is_sandbox: z.boolean().optional().default(false),
  sandbox_expires_at: z.iso.datetime().nullish(),
  created_at: z.iso.datetime(),
  updated_at: z.iso.datetime(),
  my_role: z.enum(['owner', 'admin', 'member']).nullish(),
  member_count: z.int().optional().default(0),
  join_request_status: z.string().nullish(),
  pending_request_count: z.int().optional().default(0),
  can_manage: z.boolean().readonly(),
  is_expired: z.boolean().readonly(),
})

/**
 * EventCloneResponse
 */
export const zEventCloneResponse = z.object({
  event: zEventRead,
  tasks_created: z.int(),
  shifts_created: z.int(),
  members_copied: z.int(),
  notified: z.boolean(),
})

/**
 * EventListResponse
 */
export const zEventListResponse = z.object({
  items: z.array(zEventRead),
  total: z.int(),
  skip: z.int(),
  limit: z.int(),
})

/**
 * EventUpdate
 */
export const zEventUpdate = z.object({
  name: z.string().nullish(),
  description: z.string().nullish(),
  start_date: z.iso.date().nullish(),
  end_date: z.iso.date().nullish(),
  default_start_time: z.iso.time().nullish(),
  default_end_time: z.iso.time().nullish(),
  status: z.enum(['draft', 'published', 'archived']).nullish(),
  visibility: z.enum(['public', 'private']).nullish(),
})

/**
 * ExcludedShift
 */
export const zExcludedShift = z.object({
  date: z.iso.date(),
  start_time: z.iso.time(),
  end_time: z.iso.time(),
})

/**
 * FeaturedUpdate
 */
export const zFeaturedUpdate = z.object({
  is_featured: z.boolean(),
})

/**
 * FeedShiftEntry
 *
 * Lightweight shift for the feed — no title/description, just booking info.
 */
export const zFeedShiftEntry = z
  .object({
    id: z.uuid(),
    date: z.iso.date(),
    start_time: z.iso.time().nullish(),
    end_time: z.iso.time().nullish(),
    max_bookings: z.int().optional().default(1),
    current_bookings: z.int().optional().default(0),
    is_booked_by_me: z.boolean().optional().default(false),
  })
  .register(z.globalRegistry, {
    description: 'Lightweight shift for the feed — no title/description, just booking info.',
  })

/**
 * FeedTaskItem
 *
 * Task with view-dependent embedded data.
 */
export const zFeedTaskItem = z
  .object({
    name: z.string(),
    description: z.string().nullish(),
    start_date: z.iso.date(),
    end_date: z.iso.date(),
    status: z.enum(['draft', 'published', 'archived']).optional().default('draft'),
    created_by_id: z.uuid().nullish(),
    event_id: z.uuid().nullish(),
    location: z.string().nullish(),
    category: z.string().nullish(),
    id: z.uuid(),
    created_at: z.iso.datetime(),
    updated_at: z.iso.datetime(),
    shift_duration_minutes: z.int().nullish(),
    default_start_time: z.iso.time().nullish(),
    default_end_time: z.iso.time().nullish(),
    people_per_shift: z.int().nullish(),
    schedule_overrides: z.array(z.record(z.string(), z.unknown())).nullish(),
    shifts: z.array(zFeedShiftEntry).nullish(),
    slot_window_start: z.iso.date().nullish(),
    total_shifts: z.int().nullish(),
    available_shifts: z.int().nullish(),
  })
  .register(z.globalRegistry, {
    description: 'Task with view-dependent embedded data.',
  })

/**
 * ForgotPasswordRequest
 *
 * Ask for a reset link.
 *
 * The endpoint answers 202 whether or not the address exists, so this schema
 * is also the whole of what an attacker learns from it.
 */
export const zForgotPasswordRequest = z
  .object({
    email: z.email().register(z.globalRegistry, {
      description: 'Address to send the reset link to',
    }),
  })
  .register(z.globalRegistry, {
    description:
      'Ask for a reset link.\n\nThe endpoint answers 202 whether or not the address exists, so this schema\nis also the whole of what an attacker learns from it.',
  })

/**
 * GlobalChannelSettingsRead
 */
export const zGlobalChannelSettingsRead = z.object({
  notify_email: z.boolean(),
  notify_push: z.boolean(),
  notify_telegram: z.boolean(),
})

/**
 * GlobalChannelSettingsUpdate
 */
export const zGlobalChannelSettingsUpdate = z.object({
  notify_email: z.boolean().nullish(),
  notify_push: z.boolean().nullish(),
  notify_telegram: z.boolean().nullish(),
})

/**
 * LoginRequest
 *
 * Credentials for an existing account.
 */
export const zLoginRequest = z
  .object({
    email: z.email().register(z.globalRegistry, {
      description: 'Address the account was registered with',
    }),
    password: z.string().register(z.globalRegistry, {
      description: 'Password as typed; never stored or logged',
    }),
  })
  .register(z.globalRegistry, {
    description: 'Credentials for an existing account.',
  })

/**
 * NotificationRead
 */
export const zNotificationRead = z.object({
  id: z.uuid(),
  recipient_id: z.uuid(),
  notification_type_code: z.string(),
  classification: z.enum(['reminder', 'change', 'match', 'announcement']),
  title: z.string(),
  body: z.string(),
  data: z.record(z.string(), z.union([z.string(), z.int()]).nullable()).nullish(),
  is_read: z.boolean(),
  read_at: z.iso.datetime().nullish(),
  channels_sent: z.array(z.string()),
  channels_failed: z.array(z.string()),
  created_at: z.iso.datetime(),
})

/**
 * NotificationListResponse
 */
export const zNotificationListResponse = z.object({
  items: z.array(zNotificationRead),
  total: z.int(),
  unread_count: z.int(),
  skip: z.int(),
  limit: z.int(),
})

/**
 * NotificationSubscriptionCreate
 */
export const zNotificationSubscriptionCreate = z.object({
  notification_type_id: z.uuid(),
  email_enabled: z.boolean().optional().default(true),
  push_enabled: z.boolean().optional().default(true),
  telegram_enabled: z.boolean().optional().default(false),
  scope_type: z.enum(['global', 'event', 'task', 'shift']).optional().default('global'),
  scope_id: z.uuid().nullish(),
  is_muted: z.boolean().optional().default(false),
})

/**
 * NotificationPreferencesBulkUpdate
 *
 * Full matrix of preferences sent from the frontend.
 */
export const zNotificationPreferencesBulkUpdate = z
  .object({
    preferences: z.array(zNotificationSubscriptionCreate),
  })
  .register(z.globalRegistry, {
    description: 'Full matrix of preferences sent from the frontend.',
  })

/**
 * NotificationSubscriptionRead
 */
export const zNotificationSubscriptionRead = z.object({
  id: z.uuid(),
  user_id: z.uuid(),
  notification_type_id: z.uuid(),
  email_enabled: z.boolean(),
  push_enabled: z.boolean(),
  telegram_enabled: z.boolean(),
  scope_type: z.string(),
  scope_id: z.uuid().nullish(),
  is_muted: z.boolean(),
  created_at: z.iso.datetime(),
  updated_at: z.iso.datetime(),
})

/**
 * NotificationSubscriptionUpdate
 */
export const zNotificationSubscriptionUpdate = z.object({
  email_enabled: z.boolean().nullish(),
  push_enabled: z.boolean().nullish(),
  telegram_enabled: z.boolean().nullish(),
  is_muted: z.boolean().nullish(),
})

/**
 * NotificationTypeRead
 */
export const zNotificationTypeRead = z.object({
  id: z.uuid(),
  code: z.string(),
  name: z.string(),
  description: z.string().nullish(),
  category: z.string(),
  classification: z.enum(['reminder', 'change', 'match', 'announcement']),
  is_admin_only: z.boolean(),
  default_channels: z.array(z.string()),
  is_active: z.boolean(),
  is_user_configurable: z.boolean(),
})

/**
 * OwnershipTransferRequest
 *
 * Request body for transferring a user's owned content to another user.
 */
export const zOwnershipTransferRequest = z
  .object({
    target_user_id: z.uuid().register(z.globalRegistry, {
      description: 'User who takes over ownership of all events and tasks',
    }),
  })
  .register(z.globalRegistry, {
    description: "Request body for transferring a user's owned content to another user.",
  })

/**
 * OwnershipTransferResult
 *
 * Summary of a completed ownership transfer.
 */
export const zOwnershipTransferResult = z
  .object({
    events_transferred: z.int().register(z.globalRegistry, {
      description: 'Number of events reassigned to the target user',
    }),
    tasks_transferred: z.int().register(z.globalRegistry, {
      description: 'Number of tasks reassigned to the target user',
    }),
  })
  .register(z.globalRegistry, {
    description: 'Summary of a completed ownership transfer.',
  })

/**
 * PushSubscriptionCreate
 */
export const zPushSubscriptionCreate = z.object({
  endpoint: z.string(),
  p256dh_key: z.string(),
  auth_key: z.string(),
  user_agent: z.string().nullish(),
})

/**
 * PushSubscriptionRead
 */
export const zPushSubscriptionRead = z.object({
  id: z.uuid(),
  endpoint: z.string(),
  user_agent: z.string().nullish(),
  created_at: z.iso.datetime(),
})

/**
 * RefreshResponse
 *
 * A fresh access token, minted from the refresh cookie.
 *
 * Carries no user object: the client already knows who it is by the time it
 * refreshes, and re-serialising the full profile on a call that fires every
 * fifteen minutes would be pure overhead.
 */
export const zRefreshResponse = z
  .object({
    access_token: z.string().register(z.globalRegistry, {
      description: 'Short-lived HS256 JWT, bearer token',
    }),
    token_type: z
      .literal('bearer')
      .register(z.globalRegistry, {
        description: "Always 'bearer'; present for RFC 6750 clients",
      })
      .optional()
      .default('bearer'),
    expires_in: z.int().register(z.globalRegistry, {
      description: 'Seconds until the access token stops being accepted',
    }),
  })
  .register(z.globalRegistry, {
    description:
      'A fresh access token, minted from the refresh cookie.\n\nCarries no user object: the client already knows who it is by the time it\nrefreshes, and re-serialising the full profile on a call that fires every\nfifteen minutes would be pure overhead.',
  })

/**
 * RegisterRequest
 *
 * Everything an account needs, in one round trip.
 *
 * Registration is open — anyone who signs up gets an active account, and that
 * account grants nothing on its own until an event admits them. So there is no
 * approval field here and nothing that hints at one.
 */
export const zRegisterRequest = z
  .object({
    email: z.email().register(z.globalRegistry, {
      description: 'Address that becomes the login credential',
    }),
    password: z.string().register(z.globalRegistry, {
      description: 'Chosen password, hashed before storage',
    }),
    name: z.string().min(1).max(100).register(z.globalRegistry, {
      description: 'Display name shown to other participants',
    }),
    preferred_language: z
      .string()
      .regex(/^(en|de)$/)
      .register(z.globalRegistry, {
        description: 'Language for the verification mail and later notifications',
      })
      .optional()
      .default('en'),
    turnstile_token: z.string().nullish(),
  })
  .register(z.globalRegistry, {
    description:
      'Everything an account needs, in one round trip.\n\nRegistration is open — anyone who signs up gets an active account, and that\naccount grants nothing on its own until an event admits them. So there is no\napproval field here and nothing that hints at one.',
  })

/**
 * ReminderOffsetEntry
 *
 * A single default reminder: offset + which channels to use.
 */
export const zReminderOffsetEntry = z
  .object({
    offset_minutes: z.union([
      z.literal(15),
      z.literal(30),
      z.literal(60),
      z.literal(120),
      z.literal(180),
      z.literal(360),
      z.literal(720),
      z.literal(1440),
      z.literal(2880),
    ]),
    channels: z
      .array(z.enum(['email', 'push', 'telegram']))
      .min(1)
      .optional()
      .default(['push']),
  })
  .register(z.globalRegistry, {
    description: 'A single default reminder: offset + which channels to use.',
  })

/**
 * DefaultReminderOffsetsRead
 */
export const zDefaultReminderOffsetsRead = z.object({
  default_reminder_offsets: z.array(zReminderOffsetEntry),
})

/**
 * DefaultReminderOffsetsUpdate
 */
export const zDefaultReminderOffsetsUpdate = z.object({
  default_reminder_offsets: z.array(zReminderOffsetEntry).max(5),
})

/**
 * ReportingOverviewStats
 */
export const zReportingOverviewStats = z.object({
  total_bookings: z.int(),
  confirmed_bookings: z.int(),
  cancelled_bookings: z.int(),
  cancellation_rate: z.number(),
  total_tasks: z.int(),
  total_shifts: z.int(),
  total_shift_capacity: z.int(),
  filled_shifts: z.int(),
  fill_rate: z.number(),
  active_volunteers: z.int(),
  total_volunteers: z.int(),
})

/**
 * ResetPasswordRequest
 *
 * Redeem a reset link and choose a new password.
 */
export const zResetPasswordRequest = z
  .object({
    token: z.string().min(1).max(255).register(z.globalRegistry, {
      description: 'Secret from the reset link; only its sha256 is stored server-side',
    }),
    password: z.string().register(z.globalRegistry, {
      description: 'New password',
    }),
  })
  .register(z.globalRegistry, {
    description: 'Redeem a reset link and choose a new password.',
  })

/**
 * SandboxCreate
 *
 * Ask for a demo session.
 *
 * Deliberately tiny and entirely anonymous: no address, no password, nothing
 * to verify. The language is carried so the seeded event reads in the same
 * language as the page the visitor clicked from — a German landing page that
 * opens an English demo is a jarring first impression.
 */
export const zSandboxCreate = z
  .object({
    role: z
      .enum(['helper', 'manager'])
      .register(z.globalRegistry, {
        description:
          "'helper' joins the demo event as a member and sees the volunteer side; 'manager' owns it and sees the organiser side",
      })
      .optional()
      .default('helper'),
    language: z
      .enum(['en', 'de'])
      .register(z.globalRegistry, {
        description: 'UI language the visitor is currently reading',
      })
      .optional()
      .default('en'),
  })
  .register(z.globalRegistry, {
    description:
      'Ask for a demo session.\n\nDeliberately tiny and entirely anonymous: no address, no password, nothing\nto verify. The language is carried so the seeded event reads in the same\nlanguage as the page the visitor clicked from — a German landing page that\nopens an English demo is a jarring first impression.',
  })

/**
 * ScheduleOverride
 */
export const zScheduleOverride = z.object({
  date: z.iso.date(),
  start_time: z.iso.time(),
  end_time: z.iso.time(),
})

/**
 * SelectedEventUpdate
 *
 * Request body for PUT /users/me/selected-event.
 */
export const zSelectedEventUpdate = z
  .object({
    selected_event_id: z.uuid().nullish(),
  })
  .register(z.globalRegistry, {
    description: 'Request body for PUT /users/me/selected-event.',
  })

/**
 * ShiftBatchRead
 */
export const zShiftBatchRead = z.object({
  task_id: z.uuid(),
  label: z.string().nullish(),
  start_date: z.iso.date(),
  end_date: z.iso.date(),
  location: z.string().nullish(),
  category: z.string().nullish(),
  default_start_time: z.iso.time().nullish(),
  default_end_time: z.iso.time().nullish(),
  shift_duration_minutes: z.int().nullish(),
  people_per_shift: z.int().nullish(),
  remainder_mode: z.enum(['drop', 'short', 'extend']).nullish().default('drop'),
  schedule_overrides: z.array(z.record(z.string(), z.unknown())).nullish(),
  id: z.uuid(),
  created_at: z.iso.datetime(),
  updated_at: z.iso.datetime(),
})

/**
 * ShiftBookingEntry
 *
 * A confirmed booking for a shift, with basic user info.
 */
export const zShiftBookingEntry = z
  .object({
    id: z.uuid(),
    user_id: z.uuid(),
    user_name: z.string().nullish(),
    user_email: z.string().nullish(),
    user_avatar_etag: z.string().nullish(),
    user_phone_number: z.string().nullish(),
    notes: z.string().nullish(),
    created_at: z.iso.datetime(),
  })
  .register(z.globalRegistry, {
    description: 'A confirmed booking for a shift, with basic user info.',
  })

/**
 * ShiftCreate
 */
export const zShiftCreate = z.object({
  task_id: z.uuid(),
  title: z.string(),
  description: z.string().nullish(),
  date: z.iso.date(),
  start_time: z.iso.time().nullish(),
  end_time: z.iso.time().nullish(),
  location: z.string().nullish(),
  category: z.string().nullish(),
  max_bookings: z.int().optional().default(1),
  batch_id: z.uuid().nullish(),
})

/**
 * ShiftDatesRequest
 */
export const zShiftDatesRequest = z.object({
  new_start_date: z.iso.date(),
})

/**
 * ShiftGenerationConfig
 */
export const zShiftGenerationConfig = z.object({
  default_start_time: z.iso.time(),
  default_end_time: z.iso.time(),
  shift_duration_minutes: z.int(),
  people_per_shift: z.int().optional().default(1),
  remainder_mode: z.enum(['drop', 'short', 'extend']).optional().default('drop'),
  overrides: z.array(zScheduleOverride).optional().default([]),
  excluded_shifts: z.array(zExcludedShift).optional().default([]),
  specific_dates: z.array(z.iso.date()).nullish(),
})

/**
 * AddShiftsToTask
 */
export const zAddShiftsToTask = z.object({
  start_date: z.iso.date(),
  end_date: z.iso.date(),
  location: z.string().nullish(),
  category: z.string().nullish(),
  schedule: zShiftGenerationConfig,
})

/**
 * ShiftRead
 */
export const zShiftRead = z.object({
  task_id: z.uuid(),
  title: z.string(),
  description: z.string().nullish(),
  date: z.iso.date(),
  start_time: z.iso.time().nullish(),
  end_time: z.iso.time().nullish(),
  location: z.string().nullish(),
  category: z.string().nullish(),
  max_bookings: z.int().optional().default(1),
  batch_id: z.uuid().nullish(),
  id: z.uuid(),
  created_at: z.iso.datetime(),
  updated_at: z.iso.datetime(),
  current_bookings: z.int().optional().default(0),
  is_booked_by_me: z.boolean().optional().default(false),
})

/**
 * ShiftListResponse
 */
export const zShiftListResponse = z.object({
  items: z.array(zShiftRead),
  total: z.int(),
  skip: z.int(),
  limit: z.int(),
})

/**
 * ShiftSummary
 *
 * Lightweight shift info nested inside a booking response.
 */
export const zShiftSummary = z
  .object({
    id: z.uuid(),
    task_id: z.uuid(),
    title: z.string(),
    date: z.iso.date(),
    start_time: z.iso.time().nullish(),
    end_time: z.iso.time().nullish(),
    location: z.string().nullish(),
    category: z.string().nullish(),
    task_name: z.string().nullish(),
  })
  .register(z.globalRegistry, {
    description: 'Lightweight shift info nested inside a booking response.',
  })

/**
 * BookingReadWithShift
 *
 * BookingRead enriched with nested shift + task name (for /me endpoint).
 */
export const zBookingReadWithShift = z
  .object({
    shift_id: z.uuid().nullish(),
    user_id: z.uuid(),
    status: z.enum(['confirmed', 'cancelled']).optional().default('confirmed'),
    notes: z.string().nullish(),
    id: z.uuid(),
    created_at: z.iso.datetime(),
    updated_at: z.iso.datetime(),
    cancellation_reason: z.string().nullish(),
    cancelled_shift_title: z.string().nullish(),
    cancelled_shift_date: z.iso.date().nullish(),
    cancelled_shift_start_time: z.iso.time().nullish(),
    cancelled_shift_end_time: z.iso.time().nullish(),
    cancelled_task_name: z.string().nullish(),
    shift: zShiftSummary.nullish(),
  })
  .register(z.globalRegistry, {
    description: 'BookingRead enriched with nested shift + task name (for /me endpoint).',
  })

/**
 * MyBookingsListResponse
 */
export const zMyBookingsListResponse = z.object({
  items: z.array(zBookingReadWithShift),
  total: z.int(),
  skip: z.int(),
  limit: z.int(),
})

/**
 * ShiftUpdate
 */
export const zShiftUpdate = z.object({
  title: z.string().nullish(),
  description: z.string().nullish(),
  date: z.iso.date().nullish(),
  start_time: z.iso.time().nullish(),
  end_time: z.iso.time().nullish(),
  location: z.string().nullish(),
  category: z.string().nullish(),
  max_bookings: z.int().nullish(),
})

/**
 * ShiftWindowResponse
 *
 * Response for the shift-window endpoint (next/prev day navigation).
 */
export const zShiftWindowResponse = z
  .object({
    shifts: z.array(zFeedShiftEntry),
    start_date: z.iso.date(),
    days: z.int(),
  })
  .register(z.globalRegistry, {
    description: 'Response for the shift-window endpoint (next/prev day navigation).',
  })

/**
 * SidebarBooking
 */
export const zSidebarBooking = z.object({
  id: z.uuid(),
  slot_id: z.uuid(),
  task_id: z.uuid(),
  slot_title: z.string(),
  slot_date: z.iso.date(),
  slot_start_time: z.iso.time().nullish(),
})

/**
 * SidebarEvent
 */
export const zSidebarEvent = z.object({
  id: z.uuid(),
  name: z.string(),
  status: z.string().optional().default('published'),
})

/**
 * SidebarTask
 */
export const zSidebarTask = z.object({
  id: z.uuid(),
  name: z.string(),
  status: z.string().optional().default('published'),
  open_shifts: z.int(),
  next_shift_date: z.iso.date().nullish(),
  next_shift_start_time: z.iso.time().nullish(),
})

/**
 * SidebarResponse
 */
export const zSidebarResponse = z.object({
  events: z.array(zSidebarEvent),
  tasks: z.array(zSidebarTask),
  bookings: z.array(zSidebarBooking),
})

/**
 * TaskBookingEntry
 *
 * A confirmed booking with slot_id, for the bulk task bookings endpoint.
 */
export const zTaskBookingEntry = z
  .object({
    id: z.uuid(),
    shift_id: z.uuid(),
    user_name: z.string().nullish(),
    user_phone_number: z.string().nullish(),
  })
  .register(z.globalRegistry, {
    description: 'A confirmed booking with slot_id, for the bulk task bookings endpoint.',
  })

/**
 * TaskCreate
 */
export const zTaskCreate = z.object({
  name: z.string(),
  description: z.string().nullish(),
  start_date: z.iso.date(),
  end_date: z.iso.date(),
  status: z.enum(['draft', 'published', 'archived']).optional().default('draft'),
  created_by_id: z.uuid().nullish(),
  event_id: z.uuid().nullish(),
  location: z.string().nullish(),
  category: z.string().nullish(),
})

/**
 * TaskCreateWithShifts
 */
export const zTaskCreateWithShifts = z.object({
  name: z.string(),
  description: z.string().nullish(),
  start_date: z.iso.date(),
  end_date: z.iso.date(),
  status: z.enum(['draft', 'published', 'archived']).optional().default('draft'),
  location: z.string().nullish(),
  category: z.string().nullish(),
  event_id: z.uuid().nullish(),
  new_event: zEventCreate.nullish(),
  schedule: zShiftGenerationConfig,
})

/**
 * TaskFeedResponse
 */
export const zTaskFeedResponse = z.object({
  items: z.array(zFeedTaskItem),
  total: z.int(),
  skip: z.int(),
  limit: z.int(),
})

/**
 * TaskFillRate
 */
export const zTaskFillRate = z.object({
  task_id: z.uuid(),
  task_name: z.string(),
  total_capacity: z.int(),
  confirmed_bookings: z.int(),
  fill_rate: z.number(),
})

/**
 * TaskRead
 */
export const zTaskRead = z.object({
  name: z.string(),
  description: z.string().nullish(),
  start_date: z.iso.date(),
  end_date: z.iso.date(),
  status: z.enum(['draft', 'published', 'archived']).optional().default('draft'),
  created_by_id: z.uuid().nullish(),
  event_id: z.uuid().nullish(),
  location: z.string().nullish(),
  category: z.string().nullish(),
  id: z.uuid(),
  created_at: z.iso.datetime(),
  updated_at: z.iso.datetime(),
  shift_duration_minutes: z.int().nullish(),
  default_start_time: z.iso.time().nullish(),
  default_end_time: z.iso.time().nullish(),
  people_per_shift: z.int().nullish(),
  schedule_overrides: z.array(z.record(z.string(), z.unknown())).nullish(),
})

/**
 * AddShiftsResponse
 */
export const zAddShiftsResponse = z.object({
  task: zTaskRead,
  shifts_added: z.int(),
})

/**
 * ShiftRegenerationResult
 */
export const zShiftRegenerationResult = z.object({
  task: zTaskRead,
  shifts_added: z.int(),
  shifts_removed: z.int(),
  shifts_kept: z.int(),
  affected_bookings: z.array(zAffectedBookingInfo),
})

/**
 * TaskCreateWithShiftsResponse
 */
export const zTaskCreateWithShiftsResponse = z.object({
  task: zTaskRead,
  shifts_created: z.int(),
  event: zEventRead.nullish(),
})

/**
 * TaskListResponse
 */
export const zTaskListResponse = z.object({
  items: z.array(zTaskRead),
  total: z.int(),
  skip: z.int(),
  limit: z.int(),
})

/**
 * TaskUpdate
 */
export const zTaskUpdate = z.object({
  name: z.string().nullish(),
  description: z.string().nullish(),
  start_date: z.iso.date().nullish(),
  end_date: z.iso.date().nullish(),
  status: z.enum(['draft', 'published', 'archived']).nullish(),
  event_id: z.uuid().nullish(),
  location: z.string().nullish(),
  category: z.string().nullish(),
})

/**
 * TaskUpdateWithShifts
 */
export const zTaskUpdateWithShifts = z.object({
  name: z.string().nullish(),
  description: z.string().nullish(),
  start_date: z.iso.date().nullish(),
  end_date: z.iso.date().nullish(),
  location: z.string().nullish(),
  category: z.string().nullish(),
  schedule: zShiftGenerationConfig,
})

/**
 * TelegramBindResponse
 */
export const zTelegramBindResponse = z.object({
  verification_code: z.string(),
  bot_username: z.string().nullish(),
  expires_at: z.iso.datetime(),
})

/**
 * TelegramBindingRead
 */
export const zTelegramBindingRead = z.object({
  id: z.uuid(),
  telegram_chat_id: z.string().nullish(),
  telegram_username: z.string().nullish(),
  is_verified: z.boolean(),
  created_at: z.iso.datetime(),
})

/**
 * TelegramChat
 */
export const zTelegramChat = z.object({
  id: z.int(),
  username: z.string().nullish(),
})

/**
 * TelegramConfigResponse
 */
export const zTelegramConfigResponse = z.object({
  bot_username: z.string().nullish(),
  is_configured: z.boolean(),
})

/**
 * TelegramLoginData
 *
 * Auth data returned by the Telegram Login Widget.
 */
export const zTelegramLoginData = z
  .object({
    id: z.int(),
    first_name: z.string().nullish(),
    last_name: z.string().nullish(),
    username: z.string().nullish(),
    photo_url: z.string().nullish(),
    auth_date: z.int(),
    hash: z.string(),
  })
  .register(z.globalRegistry, {
    description: 'Auth data returned by the Telegram Login Widget.',
  })

/**
 * TelegramMessage
 */
export const zTelegramMessage = z.object({
  text: z.string().nullish(),
  chat: zTelegramChat.nullish(),
})

/**
 * TelegramVerifyRequest
 */
export const zTelegramVerifyRequest = z.object({
  verification_code: z.string(),
  telegram_chat_id: z.string(),
  telegram_username: z.string().nullish(),
})

/**
 * TelegramWebhookUpdate
 *
 * Subset of the Telegram Bot API Update object we actually use.
 */
export const zTelegramWebhookUpdate = z
  .object({
    message: zTelegramMessage.nullish(),
  })
  .register(z.globalRegistry, {
    description: 'Subset of the Telegram Bot API Update object we actually use.',
  })

/**
 * TestUserSeed
 */
export const zTestUserSeed = z.object({
  email: z.email(),
  name: z.string(),
  roles: z.array(z.string()).optional().default([]),
  is_active: z.boolean().optional().default(true),
  preferred_language: z.string().optional().default('en'),
})

/**
 * TopVolunteer
 */
export const zTopVolunteer = z.object({
  user_id: z.uuid(),
  name: z.string().nullable(),
  email: z.string().nullable(),
  booking_count: z.int(),
})

/**
 * ReportingResponse
 */
export const zReportingResponse = z.object({
  overview: zReportingOverviewStats,
  bookings_trend: z.array(zBookingsTrendPoint),
  top_volunteers: z.array(zTopVolunteer),
  category_breakdown: z.array(zCategoryBreakdown),
  bookings_by_hour: z.array(zBookingsByHour),
  task_fill_rates: z.array(zTaskFillRate),
})

/**
 * UnreadCountResponse
 */
export const zUnreadCountResponse = z.object({
  unread_count: z.int(),
})

/**
 * UserAvailabilityDateInput
 */
export const zUserAvailabilityDateInput = z.object({
  date: z.iso.date(),
  start_time: z.iso.time().nullish(),
  end_time: z.iso.time().nullish(),
})

/**
 * UserAvailabilityCreate
 */
export const zUserAvailabilityCreate = z.object({
  availability_type: z.enum(['fully_available', 'specific_dates', 'time_range']),
  notes: z.string().nullish(),
  default_start_time: z.iso.time().nullish(),
  default_end_time: z.iso.time().nullish(),
  dates: z
    .array(z.union([z.iso.date(), zUserAvailabilityDateInput]))
    .optional()
    .default([]),
})

/**
 * UserAvailabilityDateRead
 */
export const zUserAvailabilityDateRead = z.object({
  id: z.uuid(),
  slot_date: z.iso.date(),
  start_time: z.iso.time().nullish(),
  end_time: z.iso.time().nullish(),
})

/**
 * UserAvailabilityRead
 */
export const zUserAvailabilityRead = z.object({
  availability_type: z.enum(['fully_available', 'specific_dates', 'time_range']),
  notes: z.string().nullish(),
  default_start_time: z.iso.time().nullish(),
  default_end_time: z.iso.time().nullish(),
  id: z.uuid(),
  user_id: z.uuid(),
  event_id: z.uuid(),
  available_dates: z.array(zUserAvailabilityDateRead).optional().default([]),
  created_at: z.iso.datetime(),
  updated_at: z.iso.datetime(),
})

/**
 * UserAvailabilityWithUser
 *
 * Extended read schema for admin view — includes basic user info.
 */
export const zUserAvailabilityWithUser = z
  .object({
    availability_type: z.enum(['fully_available', 'specific_dates', 'time_range']),
    notes: z.string().nullish(),
    default_start_time: z.iso.time().nullish(),
    default_end_time: z.iso.time().nullish(),
    id: z.uuid(),
    user_id: z.uuid(),
    event_id: z.uuid(),
    available_dates: z.array(zUserAvailabilityDateRead).optional().default([]),
    created_at: z.iso.datetime(),
    updated_at: z.iso.datetime(),
    user_full_name: z.string().nullish(),
    user_email: z.string().nullish(),
  })
  .register(z.globalRegistry, {
    description: 'Extended read schema for admin view — includes basic user info.',
  })

/**
 * UserCounts
 */
export const zUserCounts = z.object({
  all: z.int(),
  active: z.int(),
  pending: z.int(),
  rejected: z.int(),
})

/**
 * UserCreate
 */
export const zUserCreate = z.object({
  subject: z.string().register(z.globalRegistry, {
    description: 'Opaque local identity string',
  }),
  email: z.email().nullish(),
  name: z.string().nullish(),
  email_verified: z
    .boolean()
    .register(z.globalRegistry, {
      description: "Whether the user's email is verified",
    })
    .optional()
    .default(false),
  roles: z
    .array(z.string())
    .register(z.globalRegistry, {
      description: 'List of role identifiers',
    })
    .optional(),
  is_active: z
    .boolean()
    .register(z.globalRegistry, {
      description: 'Whether the user is active',
    })
    .optional()
    .default(true),
  preferred_language: z
    .string()
    .register(z.globalRegistry, {
      description: 'Preferred language',
    })
    .optional()
    .default('en'),
  time_format: z
    .string()
    .register(z.globalRegistry, {
      description: 'Display preference for times',
    })
    .optional()
    .default('locale'),
  theme: z
    .string()
    .register(z.globalRegistry, {
      description: 'Selected color palette',
    })
    .optional()
    .default('default'),
})

/**
 * UserOwnedContent
 *
 * Counts of content created (owned) by a user.
 */
export const zUserOwnedContent = z
  .object({
    events: z.int().register(z.globalRegistry, {
      description: 'Number of events created by the user',
    }),
    tasks: z.int().register(z.globalRegistry, {
      description: 'Number of tasks created by the user',
    }),
    total: z.int().register(z.globalRegistry, {
      description: 'Total number of owned items',
    }),
  })
  .register(z.globalRegistry, {
    description: 'Counts of content created (owned) by a user.',
  })

/**
 * UserProfile
 */
export const zUserProfile = z.object({
  id: z.uuid(),
  sub: z.string(),
  name: z.string().nullish(),
  nickname: z.string().nullish(),
  email: z.string().nullish(),
  avatar_etag: z.string().nullish(),
  bio: z.string().nullish(),
  phone_number: z.string().nullish(),
  preferred_language: z.string().optional().default('en'),
  time_format: z.enum(['locale', 'h12', 'h24']).optional().default('locale'),
  theme: z.enum(['default', 'classic']).optional().default('default'),
  show_event_switcher_in_nav: z.boolean().optional().default(false),
  email_verified: z.boolean().optional().default(false),
  roles: z
    .array(z.string())
    .register(z.globalRegistry, {
      description: "User's roles",
    })
    .optional(),
  is_admin: z
    .boolean()
    .register(z.globalRegistry, {
      description: 'Whether user is a platform superadmin',
    })
    .optional()
    .default(false),
  is_active: z
    .boolean()
    .register(z.globalRegistry, {
      description: 'Whether user is active',
    })
    .optional()
    .default(true),
  rejection_reason: z.string().nullish(),
  event_roles: z
    .record(z.string(), z.string())
    .register(z.globalRegistry, {
      description:
        "This user's role in each event they belong to, keyed by event id: owner, admin or member",
    })
    .optional(),
  selected_event_id: z.uuid().nullish(),
  is_sandbox: z
    .boolean()
    .register(z.globalRegistry, {
      description:
        "This is a throwaway guest account from the 'try a test event' button, not a real registration",
    })
    .optional()
    .default(false),
  sandbox_expires_at: z.iso.datetime().nullish(),
})

/**
 * SandboxSessionResponse
 *
 * A real signed-in session, pointed at a demo that will not outlive the day.
 *
 * Extends the normal login response rather than inventing a parallel one, so
 * the client installs it through exactly the same code path — the demo is not
 * a special rendering mode, it is an ordinary session that happens to belong
 * to a guest.
 */
export const zSandboxSessionResponse = z
  .object({
    access_token: z.string().register(z.globalRegistry, {
      description: 'Short-lived HS256 JWT, bearer token',
    }),
    token_type: z
      .literal('bearer')
      .register(z.globalRegistry, {
        description: "Always 'bearer'; present for RFC 6750 clients",
      })
      .optional()
      .default('bearer'),
    expires_in: z.int().register(z.globalRegistry, {
      description: 'Seconds until the access token stops being accepted',
    }),
    user: zUserProfile,
    event_id: z.uuid().register(z.globalRegistry, {
      description: "The seeded event, already set as the guest's selection",
    }),
    role: z.enum(['helper', 'manager']).register(z.globalRegistry, {
      description: 'Which side of the app was requested',
    }),
    expires_at: z.iso.datetime().register(z.globalRegistry, {
      description:
        'Naive UTC instant at which the sweep may purge this demo. The banner counts down to it; the server does not enforce it early.',
    }),
  })
  .register(z.globalRegistry, {
    description:
      'A real signed-in session, pointed at a demo that will not outlive the day.\n\nExtends the normal login response rather than inventing a parallel one, so\nthe client installs it through exactly the same code path — the demo is not\na special rendering mode, it is an ordinary session that happens to belong\nto a guest.',
  })

/**
 * TokenResponse
 *
 * What a successful register or login hands back.
 *
 * The refresh token is *not* in here — it goes out as an httpOnly cookie the
 * JavaScript can never read. This body holds only what the client is meant to
 * keep in memory.
 *
 * The profile rides along so the app can render a signed-in shell without a
 * second round trip on the one screen where latency is most visible.
 */
export const zTokenResponse = z
  .object({
    access_token: z.string().register(z.globalRegistry, {
      description: 'Short-lived HS256 JWT, bearer token',
    }),
    token_type: z
      .literal('bearer')
      .register(z.globalRegistry, {
        description: "Always 'bearer'; present for RFC 6750 clients",
      })
      .optional()
      .default('bearer'),
    expires_in: z.int().register(z.globalRegistry, {
      description: 'Seconds until the access token stops being accepted',
    }),
    user: zUserProfile,
  })
  .register(z.globalRegistry, {
    description:
      'What a successful register or login hands back.\n\nThe refresh token is *not* in here — it goes out as an httpOnly cookie the\nJavaScript can never read. This body holds only what the client is meant to\nkeep in memory.\n\nThe profile rides along so the app can render a signed-in shell without a\nsecond round trip on the one screen where latency is most visible.',
  })

/**
 * UserProfileUpdate
 */
export const zUserProfileUpdate = z.object({
  name: z.string().max(100).nullish(),
  nickname: z.string().max(50).nullish(),
  bio: z.string().max(500).nullish(),
  phone_number: z.string().max(30).nullish(),
  preferred_language: z
    .string()
    .regex(/^(en|de)$/)
    .nullish(),
  time_format: z.enum(['locale', 'h12', 'h24']).nullish(),
  theme: z.enum(['default', 'classic']).nullish(),
  show_event_switcher_in_nav: z.boolean().nullish(),
})

/**
 * UserRead
 */
export const zUserRead = z.object({
  id: z.uuid(),
  subject: z.string(),
  email: z.email().nullish(),
  name: z.string().nullish(),
  avatar_etag: z.string().nullish(),
  phone_number: z.string().nullish(),
  preferred_language: z.string().optional().default('en'),
  time_format: z.string().optional().default('locale'),
  theme: z.string().optional().default('default'),
  roles: z.array(z.string()),
  is_active: z.boolean(),
  rejection_reason: z.string().nullish(),
  created_at: z.iso.datetime(),
  updated_at: z.iso.datetime(),
})

/**
 * UserListResponse
 */
export const zUserListResponse = z.object({
  items: z.array(zUserRead),
  skip: z.int(),
  limit: z.int(),
  counts: zUserCounts,
})

/**
 * UserUpdate
 */
export const zUserUpdate = z.object({
  email: z.email().nullish(),
  name: z.string().nullish(),
  roles: z.array(z.string()).nullish(),
  is_active: z.boolean().nullish(),
  rejection_reason: z.string().nullish(),
  preferred_language: z.string().nullish(),
  time_format: z.string().nullish(),
  theme: z.string().nullish(),
})

/**
 * VerifyEmailRequest
 *
 * Redeem a verification link.
 */
export const zVerifyEmailRequest = z
  .object({
    token: z.string().min(1).max(255).register(z.globalRegistry, {
      description: 'Secret from the verification link',
    }),
  })
  .register(z.globalRegistry, {
    description: 'Redeem a verification link.',
  })

export const zValidationErrorItem = z.object({
  loc: z.array(z.union([z.string(), z.int()])),
  msg: z.string(),
  type: z.string(),
})

export const zProblemDetails = z.object({
  type: z.url().default('about:blank'),
  code: z.string().optional(),
  title: z.string(),
  status: z.int(),
  detail: z.string().optional(),
  instance: z.string().optional(),
  errors: z.array(zValidationErrorItem).optional(),
})

/**
 * EventRead
 */
export const zEventReadWritable = z.object({
  name: z.string(),
  description: z.string().nullish(),
  start_date: z.iso.date(),
  end_date: z.iso.date(),
  default_start_time: z.iso.time().nullish(),
  default_end_time: z.iso.time().nullish(),
  status: z.enum(['draft', 'published', 'archived']).optional().default('draft'),
  visibility: z.enum(['public', 'private']).optional().default('private'),
  id: z.uuid(),
  created_by_id: z.uuid().nullish(),
  is_featured: z.boolean().optional().default(false),
  is_sandbox: z.boolean().optional().default(false),
  sandbox_expires_at: z.iso.datetime().nullish(),
  created_at: z.iso.datetime(),
  updated_at: z.iso.datetime(),
  my_role: z.enum(['owner', 'admin', 'member']).nullish(),
  member_count: z.int().optional().default(0),
  join_request_status: z.string().nullish(),
  pending_request_count: z.int().optional().default(0),
})

/**
 * EventCloneResponse
 */
export const zEventCloneResponseWritable = z.object({
  event: zEventReadWritable,
  tasks_created: z.int(),
  shifts_created: z.int(),
  members_copied: z.int(),
  notified: z.boolean(),
})

/**
 * EventListResponse
 */
export const zEventListResponseWritable = z.object({
  items: z.array(zEventReadWritable),
  total: z.int(),
  skip: z.int(),
  limit: z.int(),
})

/**
 * TaskCreateWithShiftsResponse
 */
export const zTaskCreateWithShiftsResponseWritable = z.object({
  task: zTaskRead,
  shifts_created: z.int(),
  event: zEventReadWritable.nullish(),
})

export const zAuthRegisterBody = zRegisterRequest

/**
 * Successful Response
 */
export const zAuthRegisterResponse = zTokenResponse

export const zAuthLoginBody = zLoginRequest

/**
 * Successful Response
 */
export const zAuthLoginResponse = zTokenResponse

/**
 * Successful Response
 */
export const zAuthRefreshResponse = zRefreshResponse

/**
 * Successful Response
 */
export const zAuthLogoutResponse = z.void().register(z.globalRegistry, {
  description: 'Successful Response',
})

/**
 * Successful Response
 */
export const zAuthExitSandboxResponse = z.void().register(z.globalRegistry, {
  description: 'Successful Response',
})

export const zAuthSandboxBody = zSandboxCreate

/**
 * Successful Response
 */
export const zAuthSandboxResponse = zSandboxSessionResponse

export const zAuthForgotPasswordBody = zForgotPasswordRequest

export const zAuthResetPasswordBody = zResetPasswordRequest

/**
 * Successful Response
 */
export const zAuthResetPasswordResponse = z.void().register(z.globalRegistry, {
  description: 'Successful Response',
})

export const zAuthVerifyEmailBody = zVerifyEmailRequest

/**
 * Successful Response
 */
export const zAuthVerifyEmailResponse = z.void().register(z.globalRegistry, {
  description: 'Successful Response',
})

export const zAuthChangePasswordBody = zChangePasswordRequest

/**
 * Successful Response
 */
export const zAuthChangePasswordResponse = z.void().register(z.globalRegistry, {
  description: 'Successful Response',
})

/**
 * Response Auth-List Sessions
 *
 * Successful Response
 */
export const zAuthListSessionsResponse = z.array(zAuthSessionRead).register(z.globalRegistry, {
  description: 'Successful Response',
})

export const zAuthRevokeSessionPath = z.object({
  session_id: z.uuid(),
})

/**
 * Successful Response
 */
export const zAuthRevokeSessionResponse = z.void().register(z.globalRegistry, {
  description: 'Successful Response',
})

/**
 * Successful Response
 */
export const zUsersDeleteCurrentUserResponse = z.void().register(z.globalRegistry, {
  description: 'Successful Response',
})

/**
 * Successful Response
 */
export const zUsersGetCurrentUserProfileResponse = zUserProfile

export const zUsersUpdateUserProfileBody = zUserProfileUpdate

/**
 * Successful Response
 */
export const zUsersUpdateUserProfileResponse = zUserProfile

export const zUsersUpdateSelectedEventBody = zSelectedEventUpdate

/**
 * Successful Response
 */
export const zUsersUpdateSelectedEventResponse = zUserProfile

export const zUsersListUsersQuery = z.object({
  q: z.string().nullish(),
  status_filter: z.enum(['all', 'active', 'pending', 'rejected']).optional().default('all'),
  skip: z.int().optional().default(0),
  limit: z.int().optional().default(20),
})

/**
 * Successful Response
 */
export const zUsersListUsersResponse = zUserListResponse

export const zUsersCreateUserBody = zUserCreate

/**
 * Successful Response
 */
export const zUsersCreateUserResponse = zUserRead

export const zUsersDeleteUserPath = z.object({
  user_id: z.uuid(),
})

export const zUsersDeleteUserQuery = z.object({
  transfer_to_user_id: z.uuid().nullish(),
})

/**
 * Successful Response
 */
export const zUsersDeleteUserResponse = zUserRead

export const zUsersGetUserPath = z.object({
  user_id: z.uuid(),
})

/**
 * Successful Response
 */
export const zUsersGetUserResponse = zUserRead

export const zUsersUpdateUserBody = zUserUpdate

export const zUsersUpdateUserPath = z.object({
  user_id: z.uuid(),
})

/**
 * Successful Response
 */
export const zUsersUpdateUserResponse = zUserRead

/**
 * Response Users-Export User Data
 *
 * Successful Response
 */
export const zUsersExportUserDataResponse = z
  .record(z.string(), z.unknown())
  .register(z.globalRegistry, {
    description: 'Successful Response',
  })

export const zUsersGetUserOwnedContentPath = z.object({
  user_id: z.uuid(),
})

/**
 * Successful Response
 */
export const zUsersGetUserOwnedContentResponse = zUserOwnedContent

export const zUsersTransferUserOwnershipBody = zOwnershipTransferRequest

export const zUsersTransferUserOwnershipPath = z.object({
  user_id: z.uuid(),
})

/**
 * Successful Response
 */
export const zUsersTransferUserOwnershipResponse = zOwnershipTransferResult

/**
 * Successful Response
 */
export const zUsersDeleteMyAvatarResponse = z.void().register(z.globalRegistry, {
  description: 'Successful Response',
})

export const zUsersUploadMyAvatarBody = zBodyUsersUploadMyAvatar

/**
 * Successful Response
 */
export const zUsersUploadMyAvatarResponse = zAvatarUploadResponse

export const zUsersGetUserAvatarPath = z.object({
  user_id: z.uuid(),
})

export const zTasksTaskFeedQuery = z.object({
  view: z.enum(['list', 'cards', 'calendar']).optional().default('list'),
  focus_mode: z.enum(['today', 'first_available']).optional().default('today'),
  search: z.string().nullish(),
  skip: z.int().gte(0).optional().default(0),
  limit: z.int().gte(1).lte(200).optional().default(100),
  date_from: z.iso.date().nullish(),
  date_to: z.iso.date().nullish(),
  my_bookings: z.boolean().optional().default(false),
  days: z.int().gte(1).lte(31).optional().default(5),
  event_id: z.uuid().nullish(),
  all_events: z.boolean().optional().default(false),
})

/**
 * Successful Response
 */
export const zTasksTaskFeedResponse = zTaskFeedResponse

export const zTasksTaskActiveDatesQuery = z.object({
  date_from: z.iso.date(),
  date_to: z.iso.date(),
})

/**
 * Response Tasks-Task Active Dates
 *
 * Successful Response
 */
export const zTasksTaskActiveDatesResponse = z.array(z.iso.date()).register(z.globalRegistry, {
  description: 'Successful Response',
})

export const zTasksGetShiftWindowPath = z.object({
  task_id: z.string(),
})

export const zTasksGetShiftWindowQuery = z.object({
  start_date: z.iso.date(),
  days: z.int().gte(1).lte(31).optional().default(5),
})

/**
 * Successful Response
 */
export const zTasksGetShiftWindowResponse = zShiftWindowResponse

export const zTasksListTasksQuery = z.object({
  skip: z.int().gte(0).optional().default(0),
  limit: z.int().gte(1).lte(200).optional().default(100),
  search: z.string().nullish(),
  status: z.enum(['draft', 'published', 'archived']).nullish(),
  my_bookings: z.boolean().optional().default(false),
  event_id: z.uuid().nullish(),
  all_events: z.boolean().optional().default(false),
})

/**
 * Successful Response
 */
export const zTasksListTasksResponse = zTaskListResponse

export const zTasksCreateTaskBody = zTaskCreate

/**
 * Successful Response
 */
export const zTasksCreateTaskResponse = zTaskRead

export const zTasksDeleteTaskPath = z.object({
  task_id: z.string(),
})

export const zTasksDeleteTaskQuery = z.object({
  cancellation_reason: z.string().nullish(),
})

/**
 * Successful Response
 */
export const zTasksDeleteTaskResponse = z.void().register(z.globalRegistry, {
  description: 'Successful Response',
})

export const zTasksGetTaskPath = z.object({
  task_id: z.string(),
})

/**
 * Successful Response
 */
export const zTasksGetTaskResponse = zTaskRead

export const zTasksUpdateTaskBody = zTaskUpdate

export const zTasksUpdateTaskPath = z.object({
  task_id: z.string(),
})

/**
 * Successful Response
 */
export const zTasksUpdateTaskResponse = zTaskRead

export const zTasksListTaskBookingsPath = z.object({
  task_id: z.string(),
})

/**
 * Response Tasks-List Task Bookings
 *
 * Successful Response
 */
export const zTasksListTaskBookingsResponse = z
  .array(zTaskBookingEntry)
  .register(z.globalRegistry, {
    description: 'Successful Response',
  })

export const zTasksCreateTaskWithShiftsBody = zTaskCreateWithShifts

/**
 * Successful Response
 */
export const zTasksCreateTaskWithShiftsResponse = zTaskCreateWithShiftsResponse

export const zTasksAddShiftsToTaskBody = zAddShiftsToTask

export const zTasksAddShiftsToTaskPath = z.object({
  task_id: z.string(),
})

/**
 * Successful Response
 */
export const zTasksAddShiftsToTaskResponse = zAddShiftsResponse

export const zTasksRegenerateTaskShiftsBody = zTaskUpdateWithShifts

export const zTasksRegenerateTaskShiftsPath = z.object({
  task_id: z.string(),
})

export const zTasksRegenerateTaskShiftsQuery = z.object({
  dry_run: z.boolean().optional().default(false),
  batch_id: z.string().nullish(),
})

/**
 * Successful Response
 */
export const zTasksRegenerateTaskShiftsResponse = zShiftRegenerationResult

export const zTasksListBatchesPath = z.object({
  task_id: z.string(),
})

/**
 * Response Tasks-List Batches
 *
 * Successful Response
 */
export const zTasksListBatchesResponse = z.array(zShiftBatchRead).register(z.globalRegistry, {
  description: 'Successful Response',
})

export const zTasksDeleteBatchPath = z.object({
  task_id: z.string(),
  batch_id: z.string(),
})

export const zTasksDeleteBatchQuery = z.object({
  cancellation_reason: z.string().nullish(),
})

/**
 * Successful Response
 */
export const zTasksDeleteBatchResponse = z.void().register(z.globalRegistry, {
  description: 'Successful Response',
})

export const zShiftsListShiftsQuery = z.object({
  task_id: z.string().nullish(),
  category: z.string().nullish(),
  search: z.string().nullish(),
  skip: z.int().gte(0).optional().default(0),
  limit: z.int().gte(1).lte(200).optional().default(100),
})

/**
 * Successful Response
 */
export const zShiftsListShiftsResponse = zShiftListResponse

export const zShiftsCreateShiftBody = zShiftCreate

/**
 * Successful Response
 */
export const zShiftsCreateShiftResponse = zShiftRead

export const zShiftsDeleteShiftPath = z.object({
  slot_id: z.string(),
})

export const zShiftsDeleteShiftQuery = z.object({
  cancellation_reason: z.string().nullish(),
})

/**
 * Successful Response
 */
export const zShiftsDeleteShiftResponse = z.void().register(z.globalRegistry, {
  description: 'Successful Response',
})

export const zShiftsGetShiftPath = z.object({
  slot_id: z.string().nullable(),
})

/**
 * Successful Response
 */
export const zShiftsGetShiftResponse = zShiftRead

export const zShiftsUpdateShiftBody = zShiftUpdate

export const zShiftsUpdateShiftPath = z.object({
  slot_id: z.string(),
})

/**
 * Successful Response
 */
export const zShiftsUpdateShiftResponse = zShiftRead

export const zShiftsListShiftBookingsPath = z.object({
  slot_id: z.string(),
})

/**
 * Response Shifts-List Shift Bookings
 *
 * Successful Response
 */
export const zShiftsListShiftBookingsResponse = z
  .array(zShiftBookingEntry)
  .register(z.globalRegistry, {
    description: 'Successful Response',
  })

export const zBookingsListMyBookingsQuery = z.object({
  skip: z.int().gte(0).optional().default(0),
  limit: z.int().gte(1).lte(200).optional().default(100),
  status: z.string().nullish(),
  date_from: z.iso.date().nullish(),
  date_to: z.iso.date().nullish(),
  event_id: z.uuid().nullish(),
  all_events: z.boolean().optional().default(false),
})

/**
 * Successful Response
 */
export const zBookingsListMyBookingsResponse = zMyBookingsListResponse

export const zBookingsMyBookingActiveDatesQuery = z.object({
  date_from: z.iso.date(),
  date_to: z.iso.date(),
})

/**
 * Response Bookings-My Booking Active Dates
 *
 * Successful Response
 */
export const zBookingsMyBookingActiveDatesResponse = z
  .array(z.iso.date())
  .register(z.globalRegistry, {
    description: 'Successful Response',
  })

export const zBookingsCreateBookingBody = zBookingCreate

/**
 * Successful Response
 */
export const zBookingsCreateBookingResponse = zBookingRead

export const zBookingsCancelBookingPath = z.object({
  booking_id: z.string(),
})

/**
 * Successful Response
 */
export const zBookingsCancelBookingResponse = zBookingRead

export const zBookingsGetBookingPath = z.object({
  booking_id: z.string(),
})

/**
 * Successful Response
 */
export const zBookingsGetBookingResponse = zBookingRead

export const zBookingsUpdateBookingBody = zBookingUpdate

export const zBookingsUpdateBookingPath = z.object({
  booking_id: z.string(),
})

/**
 * Successful Response
 */
export const zBookingsUpdateBookingResponse = zBookingRead

export const zBookingsDismissBookingPath = z.object({
  booking_id: z.string(),
})

/**
 * Successful Response
 */
export const zBookingsDismissBookingResponse = z.void().register(z.globalRegistry, {
  description: 'Successful Response',
})

/**
 * Successful Response
 */
export const zBookingRemindersGetReminderDefaultsResponse = zDefaultReminderOffsetsRead

export const zBookingRemindersUpdateReminderDefaultsBody = zDefaultReminderOffsetsUpdate

/**
 * Successful Response
 */
export const zBookingRemindersUpdateReminderDefaultsResponse = zDefaultReminderOffsetsRead

export const zBookingRemindersListBookingRemindersPath = z.object({
  booking_id: z.uuid(),
})

/**
 * Successful Response
 */
export const zBookingRemindersListBookingRemindersResponse = zBookingReminderListResponse

export const zBookingRemindersAddBookingReminderBody = zBookingReminderCreate

export const zBookingRemindersAddBookingReminderPath = z.object({
  booking_id: z.uuid(),
})

/**
 * Successful Response
 */
export const zBookingRemindersAddBookingReminderResponse = zBookingReminderRead

export const zBookingRemindersDeleteReminderPath = z.object({
  reminder_id: z.uuid(),
})

/**
 * Successful Response
 */
export const zBookingRemindersDeleteReminderResponse = z.void().register(z.globalRegistry, {
  description: 'Successful Response',
})

/**
 * Successful Response
 */
export const zCalendarDisableFeedResponse = z.void().register(z.globalRegistry, {
  description: 'Successful Response',
})

/**
 * Response Calendar-Get Feed Settings
 *
 * Successful Response
 */
export const zCalendarGetFeedSettingsResponse = zCalendarFeedRead.nullable()

/**
 * Successful Response
 */
export const zCalendarEnableFeedResponse = zCalendarFeedRead

/**
 * Successful Response
 */
export const zCalendarRegenerateFeedResponse = zCalendarFeedRead

export const zEventsListEventsQuery = z.object({
  skip: z.int().gte(0).optional().default(0),
  limit: z.int().gte(1).lte(200).optional().default(100),
  scope: z
    .enum(['mine', 'discover', 'featured', 'all'])
    .register(z.globalRegistry, {
      description:
        'mine — events you belong to; discover — public events you could join; featured — the curated home selection; all — superadmin only',
    })
    .optional()
    .default('mine'),
  search: z.string().nullish(),
  status: z.enum(['draft', 'published', 'archived']).nullish(),
  visibility: z.enum(['public', 'private']).nullish(),
  date_from: z.iso.date().nullish(),
  date_to: z.iso.date().nullish(),
  is_expired: z.boolean().nullish(),
})

/**
 * Successful Response
 */
export const zEventsListEventsResponse = zEventListResponse

export const zEventsCreateEventBody = zEventCreate

/**
 * Successful Response
 */
export const zEventsCreateEventResponse = zEventRead

export const zEventsDeleteEventPath = z.object({
  event_id: z.uuid(),
})

/**
 * Successful Response
 */
export const zEventsDeleteEventResponse = z.void().register(z.globalRegistry, {
  description: 'Successful Response',
})

export const zEventsGetEventPath = z.object({
  event_id: z.uuid(),
})

/**
 * Successful Response
 */
export const zEventsGetEventResponse = zEventRead

export const zEventsUpdateEventBody = zEventUpdate

export const zEventsUpdateEventPath = z.object({
  event_id: z.uuid(),
})

/**
 * Successful Response
 */
export const zEventsUpdateEventResponse = zEventRead

export const zEventsSetEventFeaturedBody = zFeaturedUpdate

export const zEventsSetEventFeaturedPath = z.object({
  event_id: z.uuid(),
})

/**
 * Successful Response
 */
export const zEventsSetEventFeaturedResponse = zEventRead

export const zEventsGetTaskDateBoundsPath = z.object({
  event_id: z.uuid(),
})

/**
 * Response Events-Get Task Date Bounds
 *
 * Successful Response
 */
export const zEventsGetTaskDateBoundsResponse = z
  .record(z.string(), z.iso.date().nullable())
  .register(z.globalRegistry, {
    description: 'Successful Response',
  })

export const zEventsShiftEventDatesBody = zShiftDatesRequest

export const zEventsShiftEventDatesPath = z.object({
  event_id: z.uuid(),
})

/**
 * Successful Response
 */
export const zEventsShiftEventDatesResponse = zEventRead

export const zEventsCloneEventBody = zEventCloneRequest

export const zEventsCloneEventPath = z.object({
  event_id: z.uuid(),
})

/**
 * Successful Response
 */
export const zEventsCloneEventResponse = zEventCloneResponse

export const zEventsListEventAvailabilitiesPath = z.object({
  event_id: z.uuid(),
})

export const zEventsListEventAvailabilitiesQuery = z.object({
  skip: z.int().gte(0).optional().default(0),
  limit: z.int().gte(1).lte(500).optional().default(200),
})

/**
 * Response Events-List Event Availabilities
 *
 * Successful Response
 */
export const zEventsListEventAvailabilitiesResponse = z
  .array(zUserAvailabilityWithUser)
  .register(z.globalRegistry, {
    description: 'Successful Response',
  })

export const zEventsDeleteMyAvailabilityPath = z.object({
  event_id: z.uuid(),
})

/**
 * Successful Response
 */
export const zEventsDeleteMyAvailabilityResponse = z.void().register(z.globalRegistry, {
  description: 'Successful Response',
})

export const zEventsGetMyAvailabilityPath = z.object({
  event_id: z.uuid(),
})

/**
 * Successful Response
 */
export const zEventsGetMyAvailabilityResponse = zUserAvailabilityRead

export const zEventsSetMyAvailabilityBody = zUserAvailabilityCreate

export const zEventsSetMyAvailabilityPath = z.object({
  event_id: z.uuid(),
})

/**
 * Successful Response
 */
export const zEventsSetMyAvailabilityResponse = zUserAvailabilityRead

export const zEventsListEventMembersPath = z.object({
  event_id: z.uuid(),
})

/**
 * Response Events-List Event Members
 *
 * Successful Response
 */
export const zEventsListEventMembersResponse = z
  .array(zEventMemberRead)
  .register(z.globalRegistry, {
    description: 'Successful Response',
  })

export const zEventsRemoveMemberPath = z.object({
  event_id: z.uuid(),
  user_id: z.uuid(),
})

/**
 * Successful Response
 */
export const zEventsRemoveMemberResponse = z.void().register(z.globalRegistry, {
  description: 'Successful Response',
})

export const zEventsUpdateMemberRoleBody = zEventMemberRoleUpdate

export const zEventsUpdateMemberRolePath = z.object({
  event_id: z.uuid(),
  user_id: z.uuid(),
})

/**
 * Successful Response
 */
export const zEventsUpdateMemberRoleResponse = zEventMemberRead

export const zEventsTransferEventOwnershipBody = zEventOwnershipTransfer

export const zEventsTransferEventOwnershipPath = z.object({
  event_id: z.uuid(),
})

/**
 * Response Events-Transfer Event Ownership
 *
 * Successful Response
 */
export const zEventsTransferEventOwnershipResponse = z
  .array(zEventMemberRead)
  .register(z.globalRegistry, {
    description: 'Successful Response',
  })

export const zEventsListEventInvitationsPath = z.object({
  event_id: z.uuid(),
})

/**
 * Response Events-List Event Invitations
 *
 * Successful Response
 */
export const zEventsListEventInvitationsResponse = z
  .array(zEventInvitationRead)
  .register(z.globalRegistry, {
    description: 'Successful Response',
  })

export const zEventsCreateEventInvitationBody = zEventInvitationCreate

export const zEventsCreateEventInvitationPath = z.object({
  event_id: z.uuid(),
})

/**
 * Successful Response
 */
export const zEventsCreateEventInvitationResponse = zEventInvitationRead

export const zEventsCreateEventInvitationsBulkBody = zEventInvitationBulkCreate

export const zEventsCreateEventInvitationsBulkPath = z.object({
  event_id: z.uuid(),
})

/**
 * Successful Response
 */
export const zEventsCreateEventInvitationsBulkResponse = zEventInvitationBulkResult

export const zEventsRevokeEventInvitationPath = z.object({
  event_id: z.uuid(),
  invitation_id: z.uuid(),
})

/**
 * Successful Response
 */
export const zEventsRevokeEventInvitationResponse = z.void().register(z.globalRegistry, {
  description: 'Successful Response',
})

export const zEventsWithdrawJoinRequestPath = z.object({
  event_id: z.uuid(),
})

/**
 * Successful Response
 */
export const zEventsWithdrawJoinRequestResponse = z.void().register(z.globalRegistry, {
  description: 'Successful Response',
})

export const zEventsRequestToJoinEventBody = zEventJoinRequestCreate

export const zEventsRequestToJoinEventPath = z.object({
  event_id: z.uuid(),
})

/**
 * Successful Response
 */
export const zEventsRequestToJoinEventResponse = zEventJoinRequestRead

export const zEventsListJoinRequestsPath = z.object({
  event_id: z.uuid(),
})

export const zEventsListJoinRequestsQuery = z.object({
  status: z.string().nullish().default('pending'),
})

/**
 * Response Events-List Join Requests
 *
 * Successful Response
 */
export const zEventsListJoinRequestsResponse = z
  .array(zEventJoinRequestRead)
  .register(z.globalRegistry, {
    description: 'Successful Response',
  })

export const zEventsDecideJoinRequestBody = zEventJoinRequestDecision

export const zEventsDecideJoinRequestPath = z.object({
  event_id: z.uuid(),
  request_id: z.uuid(),
})

/**
 * Successful Response
 */
export const zEventsDecideJoinRequestResponse = zEventJoinRequestRead

export const zInvitationsPreviewInvitationPath = z.object({
  token: z.string(),
})

/**
 * Successful Response
 */
export const zInvitationsPreviewInvitationResponse = zEventInvitationPreview

export const zInvitationsAcceptInvitationPath = z.object({
  token: z.string(),
})

/**
 * Successful Response
 */
export const zInvitationsAcceptInvitationResponse = zEventRead

/**
 * Response Notifications-List Notification Types
 *
 * Successful Response
 */
export const zNotificationsListNotificationTypesResponse = z
  .array(zNotificationTypeRead)
  .register(z.globalRegistry, {
    description: 'Successful Response',
  })

/**
 * Response Notifications-List Preferences
 *
 * Successful Response
 */
export const zNotificationsListPreferencesResponse = z
  .array(zNotificationSubscriptionRead)
  .register(z.globalRegistry, {
    description: 'Successful Response',
  })

export const zNotificationsCreatePreferenceBody = zNotificationSubscriptionCreate

/**
 * Successful Response
 */
export const zNotificationsCreatePreferenceResponse = zNotificationSubscriptionRead

export const zNotificationsBulkUpdatePreferencesBody = zNotificationPreferencesBulkUpdate

/**
 * Response Notifications-Bulk Update Preferences
 *
 * Successful Response
 */
export const zNotificationsBulkUpdatePreferencesResponse = z
  .array(zNotificationSubscriptionRead)
  .register(z.globalRegistry, {
    description: 'Successful Response',
  })

export const zNotificationsDeletePreferencePath = z.object({
  preference_id: z.string(),
})

/**
 * Successful Response
 */
export const zNotificationsDeletePreferenceResponse = z.void().register(z.globalRegistry, {
  description: 'Successful Response',
})

export const zNotificationsUpdatePreferenceBody = zNotificationSubscriptionUpdate

export const zNotificationsUpdatePreferencePath = z.object({
  preference_id: z.string(),
})

/**
 * Successful Response
 */
export const zNotificationsUpdatePreferenceResponse = zNotificationSubscriptionRead

/**
 * Successful Response
 */
export const zNotificationsGetChannelSettingsResponse = zGlobalChannelSettingsRead

export const zNotificationsUpdateChannelSettingsBody = zGlobalChannelSettingsUpdate

/**
 * Successful Response
 */
export const zNotificationsUpdateChannelSettingsResponse = zGlobalChannelSettingsRead

/**
 * Response Notifications-List Push Subscriptions
 *
 * Successful Response
 */
export const zNotificationsListPushSubscriptionsResponse = z
  .array(zPushSubscriptionRead)
  .register(z.globalRegistry, {
    description: 'Successful Response',
  })

export const zNotificationsRegisterPushSubscriptionBody = zPushSubscriptionCreate

/**
 * Successful Response
 */
export const zNotificationsRegisterPushSubscriptionResponse = zPushSubscriptionRead

export const zNotificationsRemovePushSubscriptionPath = z.object({
  subscription_id: z.string(),
})

/**
 * Successful Response
 */
export const zNotificationsRemovePushSubscriptionResponse = z.void().register(z.globalRegistry, {
  description: 'Successful Response',
})

/**
 * Response Notifications-Get Vapid Public Key
 *
 * Successful Response
 */
export const zNotificationsGetVapidPublicKeyResponse = z
  .record(z.string(), z.string())
  .register(z.globalRegistry, {
    description: 'Successful Response',
  })

/**
 * Response Notifications-Send Test Push
 *
 * Successful Response
 */
export const zNotificationsSendTestPushResponse = z
  .record(z.string(), z.boolean())
  .register(z.globalRegistry, {
    description: 'Successful Response',
  })

/**
 * Successful Response
 */
export const zNotificationsGetTelegramConfigResponse = zTelegramConfigResponse

/**
 * Successful Response
 */
export const zNotificationsUnbindTelegramResponse = z.void().register(z.globalRegistry, {
  description: 'Successful Response',
})

/**
 * Response Notifications-Get Telegram Binding
 *
 * Successful Response
 */
export const zNotificationsGetTelegramBindingResponse = zTelegramBindingRead.nullable()

export const zNotificationsTelegramLoginBody = zTelegramLoginData

/**
 * Successful Response
 */
export const zNotificationsTelegramLoginResponse = zTelegramBindingRead

/**
 * Successful Response
 */
export const zNotificationsStartTelegramBindingResponse = zTelegramBindResponse

export const zNotificationsVerifyTelegramBindingBody = zTelegramVerifyRequest

/**
 * Successful Response
 */
export const zNotificationsVerifyTelegramBindingResponse = zTelegramBindingRead

export const zNotificationsTelegramWebhookBody = zTelegramWebhookUpdate

/**
 * Response Notifications-Telegram Webhook
 *
 * Successful Response
 */
export const zNotificationsTelegramWebhookResponse = z
  .record(z.string(), z.boolean())
  .register(z.globalRegistry, {
    description: 'Successful Response',
  })

export const zNotificationsNotificationStreamQuery = z.object({
  token: z.string().register(z.globalRegistry, {
    description: 'Bearer token for auth',
  }),
})

export const zNotificationsListNotificationsQuery = z.object({
  skip: z.int().gte(0).optional().default(0),
  limit: z.int().gte(1).lte(200).optional().default(50),
  unread_only: z.boolean().optional().default(false),
})

/**
 * Successful Response
 */
export const zNotificationsListNotificationsResponse = zNotificationListResponse

/**
 * Successful Response
 */
export const zNotificationsGetUnreadCountResponse = zUnreadCountResponse

export const zNotificationsMarkNotificationReadPath = z.object({
  notification_id: z.string(),
})

/**
 * Successful Response
 */
export const zNotificationsMarkNotificationReadResponse = zNotificationRead

/**
 * Response Notifications-Mark All Notifications Read
 *
 * Successful Response
 */
export const zNotificationsMarkAllNotificationsReadResponse = z
  .record(z.string(), z.int())
  .register(z.globalRegistry, {
    description: 'Successful Response',
  })

/**
 * Response Notifications-Dismiss All Notifications
 *
 * Successful Response
 */
export const zNotificationsDismissAllNotificationsResponse = z
  .record(z.string(), z.int())
  .register(z.globalRegistry, {
    description: 'Successful Response',
  })

export const zNotificationsDismissNotificationPath = z.object({
  notification_id: z.string(),
})

/**
 * Successful Response
 */
export const zNotificationsDismissNotificationResponse = z.void().register(z.globalRegistry, {
  description: 'Successful Response',
})

/**
 * Successful Response
 */
export const zDashboardDashboardFeedResponse = zDashboardFeedResponse

/**
 * Successful Response
 */
export const zDashboardDashboardSidebarResponse = zSidebarResponse

export const zReportingReportingOverviewQuery = z.object({
  date_from: z.iso.date().nullish(),
  date_to: z.iso.date().nullish(),
})

/**
 * Successful Response
 */
export const zReportingReportingOverviewResponse = zReportingResponse

export const zReportingReportingExportQuery = z.object({
  date_from: z.iso.date().nullish(),
  date_to: z.iso.date().nullish(),
})

/**
 * Successful Response
 */
export const zDemoDataDeleteDemoDataResponse = zDemoDataDeletedResponse

export const zDemoDataCreateDemoDataBody = zDemoDataParams

/**
 * Successful Response
 */
export const zDemoDataCreateDemoDataResponse = zDemoDataCreatedResponse

/**
 * Response Debug-Start Log Capture
 *
 * Successful Response
 */
export const zDebugStartLogCaptureResponse = z
  .record(z.string(), z.string())
  .register(z.globalRegistry, {
    description: 'Successful Response',
  })

/**
 * Response Debug-Stop Log Capture
 *
 * Successful Response
 */
export const zDebugStopLogCaptureResponse = z
  .record(z.string(), z.string())
  .register(z.globalRegistry, {
    description: 'Successful Response',
  })

export const zTestingSeedTestUserBody = zTestUserSeed

/**
 * Successful Response
 */
export const zTestingSeedTestUserResponse = zUserRead

/**
 * Response Testing-Reset Test Data
 *
 * Successful Response
 */
export const zTestingResetTestDataResponse = z
  .record(z.string(), z.int())
  .register(z.globalRegistry, {
    description: 'Successful Response',
  })
