/**
 * Product screenshots for the landing page.
 *
 * Usage:
 *   just screenshots          # English
 *   just screenshots de       # German
 *
 * Requires:
 *   - Frontend running at http://localhost:5555 with VITE_E2E_AUTH_BYPASS=true
 *   - Backend running at http://localhost:8787 with TESTING=true
 *
 * No credentials are involved. An older version drove the real login form,
 * which meant screenshots could only be regenerated by whoever held the account
 * — and when that login silently failed, it wrote captures of the login page
 * over the real screenshots. This uses the same seed-and-bypass harness the E2E
 * suite runs on, so the data on screen is deliberate rather than whatever the
 * local database happened to contain.
 *
 * Each page is captured twice, light and dark, always in the default (earthy)
 * palette, into `public/screenshots/<lang>/<name>-<mode>.png`.
 */
import { type Browser, type BrowserContext, type Page, expect, test } from '@playwright/test'

import { type Locale, type TaskSeed, WORLD } from './screenshots.data.js'

const BASE_URL = 'http://localhost:5555'
const API = process.env.VITE_API_URL ?? 'http://localhost:8787/api/v1'

const LANG: Locale = process.env.LANG === 'de' ? 'de' : 'en'
const SCREENSHOT_DIR = `public/screenshots/${LANG}`
const VIEWPORT = { width: 1440, height: 900 }
const MODES = ['light', 'dark'] as const

const EMAIL_DOMAIN = 'example.org'
const world = WORLD[LANG]

// ── Seeding (Node side, via the TESTING-only endpoints) ──────────────────────

const addressOf = (handle: string) => `${handle}@${EMAIL_DOMAIN}`

async function apiAs<T>(method: string, path: string, email: string, body?: object): Promise<T> {
  const res = await fetch(`${API}${path}`, {
    method,
    headers: { 'Content-Type': 'application/json', 'X-Test-User-Email': email },
    body: body ? JSON.stringify(body) : undefined,
  })
  if (!res.ok) {
    throw new Error(`API ${method} ${path} failed: ${res.status} ${await res.text()}`)
  }
  return res.status === 204 ? (null as T) : ((await res.json()) as T)
}

async function seedUser(handle: string, name: string): Promise<void> {
  const res = await fetch(`${API}/testing/seed`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      email: addressOf(handle),
      name,
      roles: [],
      is_active: true,
      preferred_language: LANG,
    }),
  })
  if (!res.ok) throw new Error(`Seeding ${handle} failed: ${res.status} ${await res.text()}`)
}

/** ISO date `offset` days from today. */
function isoDate(offset: number): string {
  const d = new Date()
  d.setDate(d.getDate() + offset)
  return d.toISOString().slice(0, 10)
}

/**
 * The festival starts tomorrow and runs five days.
 *
 * Every shift stays in the future — the backend filters past ones away — while
 * still falling inside the week-from-today strip the task list renders, so the
 * roster shows real occupancy instead of a row of em dashes.
 */
const EVENT_START_OFFSET = 1
const EVENT_DAYS = 5

/**
 * How many shifts the organiser takes on herself.
 *
 * The dashboard leads with "your next shift", so an organiser who has booked
 * nothing captures an empty state — accurate, but a poor description of the
 * screen. Somebody who both runs an event and helps at it is the ordinary
 * case, and three shifts across three jobs is what that looks like.
 */
const ORGANISER_SHIFTS = 3

interface SeededTask {
  seed: TaskSeed
  id: string
}

interface SeededWorld {
  organiserEmail: string
  eventId: string
  tasks: SeededTask[]
  /** Task the `task-detail` capture opens. */
  featuredTaskId: string
}

async function seedWorld(): Promise<SeededWorld> {
  // Only removes users whose subject starts with `test|`, so a real local
  // account and anything it owns is left alone.
  const reset = await fetch(`${API}/testing/reset`, { method: 'POST' })
  if (!reset.ok) throw new Error(`Reset failed: ${reset.status} ${await reset.text()}`)

  await seedUser(world.organiser.handle, world.organiser.name)
  for (const volunteer of world.volunteers) {
    await seedUser(volunteer.handle, volunteer.name)
  }

  const organiserEmail = addressOf(world.organiser.handle)

  const event = await apiAs<{ id: string }>('POST', '/events/', organiserEmail, {
    name: world.event.name,
    description: world.event.description,
    status: 'published',
    visibility: 'public',
    start_date: isoDate(EVENT_START_OFFSET),
    end_date: isoDate(EVENT_START_OFFSET + EVENT_DAYS - 1),
  })

  // Everyone joins through the real invitation flow.
  for (const volunteer of world.volunteers) {
    const invitation = await apiAs<{ token: string }>(
      'POST',
      `/events/${event.id}/invitations`,
      organiserEmail,
      { email: addressOf(volunteer.handle), role: 'member' },
    )
    await apiAs('POST', `/invitations/${invitation.token}/accept`, addressOf(volunteer.handle))
  }

  await apiAs('PUT', '/users/me/selected-event', organiserEmail, { selected_event_id: event.id })

  const tasks: SeededTask[] = []
  for (const seed of world.tasks) {
    const days = [...seed.days].sort((a, b) => a - b)
    const created = await apiAs<{ task: { id: string } }>(
      'POST',
      '/tasks/with-shifts',
      organiserEmail,
      {
        name: seed.name,
        description: seed.description,
        start_date: isoDate(EVENT_START_OFFSET + days[0]),
        end_date: isoDate(EVENT_START_OFFSET + days[days.length - 1]),
        status: 'published',
        location: seed.location,
        category: seed.category,
        event_id: event.id,
        schedule: {
          default_start_time: `${seed.startTime}:00`,
          default_end_time: `${seed.endTime}:00`,
          shift_duration_minutes: seed.shiftMinutes,
          people_per_shift: seed.peoplePerShift,
          remainder_mode: 'drop',
          overrides: [],
          excluded_shifts: [],
        },
      },
    )
    tasks.push({ seed, id: created.task.id })
  }

  await fillRoster(tasks, organiserEmail)
  await bookOrganiser(tasks, organiserEmail)

  const featured = tasks.find((t) => t.seed.key === 'welcome') ?? tasks[0]
  return { organiserEmail, eventId: event.id, tasks, featuredTaskId: featured.id }
}

/**
 * Book shifts so the roster looks lived-in.
 *
 * Volunteers are handed out round-robin and never booked onto two overlapping
 * shifts, because the backend rejects overlaps and the resulting error would
 * leave the roster half-filled in a way that differs between runs.
 */
async function fillRoster(tasks: SeededTask[], organiserEmail: string): Promise<void> {
  const busy = new Map<string, { start: number; end: number }[]>()
  const bookings: { email: string; shiftId: string }[] = []
  let nextVolunteer = 0

  const overlaps = (email: string, start: number, end: number) =>
    (busy.get(email) ?? []).some((slot) => start < slot.end && end > slot.start)

  for (const task of tasks) {
    const { items: shifts } = await apiAs<{
      items: { id: string; start_time: string; end_time: string }[]
    }>('GET', `/shifts/?task_id=${task.id}&limit=200`, organiserEmail)

    shifts.sort((a, b) => a.start_time.localeCompare(b.start_time))

    shifts.forEach((shift, index) => {
      const fraction = task.seed.fillPattern[index % task.seed.fillPattern.length]
      const wanted = Math.round(task.seed.peoplePerShift * fraction)
      const start = Date.parse(shift.start_time)
      const end = Date.parse(shift.end_time)

      const takenHere: string[] = []
      let attempts = 0
      while (takenHere.length < wanted && attempts < world.volunteers.length * 2) {
        const candidate = addressOf(
          world.volunteers[nextVolunteer % world.volunteers.length].handle,
        )
        nextVolunteer += 1
        attempts += 1
        if (takenHere.includes(candidate) || overlaps(candidate, start, end)) continue
        takenHere.push(candidate)
        busy.set(candidate, [...(busy.get(candidate) ?? []), { start, end }])
      }

      bookings.push(...takenHere.map((email) => ({ email, shiftId: shift.id })))
    })
  }

  for (const { email, shiftId } of bookings) {
    // A rejected booking is not worth failing the whole capture over; that
    // shift simply stays emptier than intended.
    await apiAs('POST', '/bookings/', email, { shift_id: shiftId }).catch(() => undefined)
  }

  console.log(`  booked ${bookings.length} places`)
}

/**
 * Put the organiser on a handful of shifts of her own, one per job.
 *
 * Runs after `fillRoster`, so it can only take places the volunteers left, and
 * it re-reads occupancy rather than assuming any: a job whose shifts all
 * filled up is skipped instead of collecting 409s.
 */
async function bookOrganiser(tasks: SeededTask[], organiserEmail: string): Promise<void> {
  interface ShiftRow {
    id: string
    date: string
    start_time: string
    end_time: string
    current_bookings: number
    max_bookings: number
  }

  const mine: { start: number; end: number }[] = []
  let booked = 0

  for (const task of tasks) {
    if (booked >= ORGANISER_SHIFTS) break

    const { items } = await apiAs<{ items: ShiftRow[] }>(
      'GET',
      `/shifts/?task_id=${task.id}&limit=200`,
      organiserEmail,
    )
    const open = items
      .filter((shift) => shift.current_bookings < shift.max_bookings)
      .sort((a, b) => `${a.date}${a.start_time}`.localeCompare(`${b.date}${b.start_time}`))

    for (const shift of open) {
      const start = Date.parse(`${shift.date}T${shift.start_time}`)
      const end = Date.parse(`${shift.date}T${shift.end_time}`)
      if (mine.some((slot) => start < slot.end && end > slot.start)) continue
      const accepted = await apiAs('POST', '/bookings/', organiserEmail, { shift_id: shift.id })
        .then(() => true)
        .catch(() => false)
      if (!accepted) continue
      mine.push({ start, end })
      booked += 1
      break
    }
  }

  console.log(`  organiser is on ${booked} shifts herself`)
}

// ── Browser setup ────────────────────────────────────────────────────────────

/**
 * A context authenticated as the organiser, pinned to one locale and colour
 * mode, with the cookie banner and "what's new" dialog pre-dismissed so neither
 * lands in a capture.
 */
async function openContext(
  browser: Browser,
  email: string,
  mode: (typeof MODES)[number],
): Promise<{ context: BrowserContext; page: Page }> {
  const context = await browser.newContext({ viewport: VIEWPORT })
  await context.addCookies([{ name: 'e2e_bypass', value: '1', domain: 'localhost', path: '/' }])

  await context.addInitScript(
    (setup: { email: string; name: string; lang: string; mode: string }) => {
      // Who the SPA believes it is. `src/testing/fake-session.ts` reads this and
      // installs a session from it without a password or a round trip; the
      // *server* is convinced separately, by the header injected below. The two
      // have to name the same address.
      localStorage.setItem(
        'wirksam-e2e-user',
        JSON.stringify({ email: setup.email, name: setup.name }),
      )
      localStorage.setItem('locale', setup.lang)
      // Screenshots always show the shipped default palette, never Classic.
      localStorage.setItem('wirksam-palette', 'default')
      localStorage.setItem('vueuse-color-scheme', setup.mode)
      localStorage.setItem('wirksam-cookie-notice-dismissed', '1')
      localStorage.setItem('wirksam-last-seen-changelog', '99.99.99')
    },
    { email, name: world.organiser.name, lang: LANG, mode },
  )

  const page = await context.newPage()
  // A selector that never resolves used to consume the entire test budget and
  // cost every capture queued behind it. Fail fast instead.
  page.setDefaultTimeout(25_000)
  await page.route('**/api/v1/**', (route) =>
    route.continue({ headers: { ...route.request().headers(), 'x-test-user-email': email } }),
  )

  return { context, page }
}

async function capture(page: Page, name: string, mode: string): Promise<void> {
  // Let data fetches and transitions settle. `networkidle` is unusable here —
  // Vite's HMR socket keeps the connection busy and would burn the timeout.
  await page.waitForTimeout(900)
  const path = `${SCREENSHOT_DIR}/${name}-${mode}.png`
  await page.screenshot({ path, type: 'png' })
  console.log(`  saved ${path}`)
}

async function open(page: Page, path: string): Promise<void> {
  await page.goto(`${BASE_URL}${path}`)
  await expect(page.getByTestId('page-heading')).toBeVisible({ timeout: 20_000 })
}

// ── Captures ─────────────────────────────────────────────────────────────────

test(`screenshots [${LANG}]`, async ({ browser }) => {
  const seeded = await seedWorld()
  console.log(`Seeded "${world.event.name}" with ${seeded.tasks.length} tasks.`)

  for (const mode of MODES) {
    const { context, page } = await openContext(browser, seeded.organiserEmail, mode)
    console.log(`\n${LANG} / ${mode}`)

    await open(page, '/app/home')
    await capture(page, 'dashboard', mode)

    await open(page, '/app/tasks')
    await capture(page, 'tasks', mode)

    await open(page, `/app/tasks/${seeded.featuredTaskId}`)
    await capture(page, 'task-detail', mode)

    await open(page, '/app/bookings')
    await capture(page, 'my-bookings', mode)

    await open(page, '/app/availability')
    await capture(page, 'availability', mode)

    await page.goto(`${BASE_URL}/app/settings/notifications`)
    await capture(page, 'notification-preferences', mode)

    await open(page, `/app/tasks/${seeded.featuredTaskId}/add-shifts`)
    await capture(page, 'shift-schedule', mode)

    // The wizard opens on its first step, which is a name and two dates. The
    // second step is the one worth advertising — last year's tasks, ticked,
    // and the list of what deliberately stays behind — so open it first. The
    // click also waits out the source load: the accordion only exists once the
    // event, its tasks and their shifts are in.
    await open(page, `/app/events/clone/${seeded.eventId}`)
    await page.locator('[data-testid="section-tasks"] [data-slot="accordion-trigger"]').click()
    await capture(page, 'clone-event', mode)

    await context.close()
  }

  console.log(`\nDone [${LANG}].`)
})
