"""Add default time fields to user availability

Revision ID: 20260309_0002
Revises: 20260309_0001
Create Date: 2026-03-09 20:40:53.489607

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = "20260309_0002"
down_revision = "20260309_0001"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_availabilities", sa.Column("default_start_time", sa.Time(), nullable=True)
    )
    op.add_column(
        "user_availabilities", sa.Column("default_end_time", sa.Time(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_availabilities", "default_end_time")
    op.drop_column("user_availabilities", "default_start_time")
    # ### end Alembic commands ###
