"""Add time fields to user_availability_dates

Revision ID: 20260309_0001
Revises: 20260308_0002
Create Date: 2026-03-09 12:58:29.759790

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = "20260309_0001"
down_revision = "20260308_0002"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_availability_dates", sa.Column("start_time", sa.Time(), nullable=True)
    )
    op.add_column(
        "user_availability_dates", sa.Column("end_time", sa.Time(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_availability_dates", "end_time")
    op.drop_column("user_availability_dates", "start_time")
    # ### end Alembic commands ###
